.github/workflows/publish-current.yml
.github/workflows/publish.yml
package-lock.json
package.json
tools/scripts/check-version.js
tools/scripts/publish-current.js
tools/scripts/upload-to-s3.js

* Updated authentication to use role with temporary credentials
* added a dry mode and test mode
* updated GA workflows accordingly

Update authentication in AWS scripts

---

CHANGELOG.md

Updated CHANGELOG with latest v1208 released version.

added v1208 to changelog

---

.github/workflows/publish.yml
tests/functional/config.test.js

The config test that checks for the default URL value was not taking into account version number.

Updated config test that checks for default URL value

---

feature/spa/aggregate/Interaction.js
feature/spa/aggregate/InteractionNode.js
feature/spa/aggregate/index.js
feature/spa/aggregate/serializer.js
feature/xhr/aggregate/deny-list.js
feature/xhr/aggregate/index.js
feature/xhr/instrument/index.js
tests/assets/spa/ajax-deny-list.html
tests/browser/xhr/deny-list.browser.js
tests/functional/spa/ajax-deny-list.test.js

This PR adds filtering of ajax events from a deny list configuration.

Ajax deny list

---

agent/harvest-scheduler.js
feature/xhr/aggregate/index.js
tests/assets/final-harvest-ajax.html
tests/assets/final-harvest-timings.html
tests/functional/final-harvest.test.js
tools/jil/util/browser-matcher.js

When page is unloading, send any buffered ajax events that have not been harvested yet.

Final harvest for ajax events

---

feature/xhr/aggregate/index.js
tests/assets/disabled-ajax.html
tests/assets/final-harvest-ajax.html
tests/browser/xhr/ajax-events.browser.js
tests/functional/spa/ajax-deny-list.test.js
tests/functional/xhr/ajax-events.test.js
tests/functional/xhr/harvest.test.js

This PR adds a flag to enable/disable `All AJAX` feature set.

add flag for disabling AJAX feature

---

feature/xhr/aggregate/index.js

Enabling ajax events by default to get ready for v1211 release.

Enable ajax events by default

---

agent/timings.js
feature/stn/aggregate/index.js
tests/browser/stn/stn.browser.js
tests/functional/timings.test.js

This PR adds PVT metrics to the STN payload. This also calculates and adds FID as an event relative to the rest of the timeline.

add pvt metrics to stn

---

feature/stn/aggregate/index.js

This PR makes the agent ignore pageHide from the window event for ST payloads, in favor of using the pageHide data from PVT.

Ignore pageHide from window in favor of PVT data

---

tools/scripts/upload-to-s3.js

This PR removes version numbers from file names if it is a dev pre-release build

remove agent version from file name if dev deploy

---

.eslintignore
cdn/package-lock.json
modules/common/config/state/info.js
modules/common/config/state/init.js
modules/common/config/state/loader-config.js
modules/common/config/state/runtime.js
modules/common/config/state/set-values.js
modules/common/window/nreum.js
modules/features/js-errors/aggregate/index.js
modules/features/js-errors/instrument/index.js
package-lock.json
packages/core/package-lock.json
packages/core/src/index.ts
packages/core/src/types.ts
packages/core/src/utils/api-defaults.ts
packages/core/src/utils/build-configs.ts
packages/core/webpack.config.js
tools/jil/package-lock.json

This PR defines the interface for the NPM module to track scoped errors, built from modular shared code.

Working example of NPM interface tracking errors

---

CHANGELOG.md

This PR updates the changelog release dates for v1216

Update changelog with release dates

---

.gitignore
cdn/agent-loader/lite.js
cdn/agent-loader/polyfills.js
cdn/agent-loader/pro.js
cdn/agent-loader/spa.js
cdn/agent-loader/utils/importAggregator.js
cdn/package-lock.json
cdn/package.json
cdn/webpack.config.js
package.json
packages/browser-agent-core/package-lock.json
tools/test-builds/build-time-mfe/component-1/package-lock.json
tools/test-builds/build-time-mfe/component-2/package-lock.json
tools/test-builds/build-time-mfe/container/package-lock.json
tools/test-builds/build-time-mfe/container/package.json

This PR adds the polyfills / transpiling to the main bundle, as decided by PM and EM, for initial release.  This process will be reevaluated over time, once we narrow the list of browsers we support, responsibility for polyfilling will be placed on customer.  But for now, we will polyfill our bundle back to IE-11.

Transpile and polyfill

---

.github/workflows/tests.yml

This PR adds max memory to GH actions, to try to alleviate the memory issues we have been seeing in recent PRs while running tests

update node max memory

---

package.json
packages/browser-agent-core/features/spa/aggregate/interaction-node.js

Preventative fix to deep traversal of interaction & interaction-node codependency.
Fixes #132 & #73.
Locally ran functional `spa/*` tests on chrome & iOS, unit of all tests on all browsers-versions.
Rebase & merge

Fix: potential interaction-node cycle

---

cdn/webpack.config.js
packages/browser-agent-core/features/jserrors/instrument/index.js

This PR adds hash numbers to chunk names for cache-busting.

Unhandledrejection

---

packages/browser-agent/README.md

Removed a duplicate paragraph from the package README
N/A
N/A

Update pkg README to remove redundant paragraph

---

cdn/agent-loader/lite.js
cdn/agent-loader/pro.js
cdn/agent-loader/spa.js
cdn/agent-loader/utils/feature-detection.js
packages/browser-agent-core/features/metrics/instrument/index.js
packages/browser-agent-core/features/metrics/instrument/workers-helper.js
tests/assets/global-count.html
tests/assets/instrumented-worker.html
tests/assets/worker-scripts/simple.js
tests/functional/metrics.test.js
tools/jil/util/browser-matcher.js

NEWRELIC-3702
Added reporting of supportability metrics for:
- Existence of required polyfill features [experimental]
- Usage of web workers API and per initialization of the combination of the following:
- flavor: {dedicated, shared, service}
- type: {classic, module}
- Appended to functional metrics test
- Manually testable

Web workers - Supportability metrics

---

tests/functional/worker/auto-instrumented-errors.test.js
tests/functional/worker/circular.test.js
tests/functional/worker/errors-have-custom-attributes.test.js
tests/functional/worker/external-error.test.js
tests/functional/worker/helpers.js
tests/functional/worker/notice-error.test.js
tools/jil/util/browser-matcher.js

Follow up PR to #286 to resolve review comments & changes.

Web workers jserrors tests - follow up

---

.github/workflows/detect-yml-change.yml
CHANGELOG.md
tools/jil/util/browsers-supported.json

This PR adds a GH action to detect if .yml files have changed
* Action runs when PR is opened, synced, or re-opened
* Action detects changes to .yml files in PR
* Action warns via comment that a workflow has changed

Detect GH Workflow changes - NEWRELIC-5328

---

CHANGELOG.md
feature/wrap-promise.js
packages/browser-agent-core/src/common/wrap/wrap-promise.js
tests/assets/third-party-compatibility/jspdf.html
tests/browser/third-party-compatibility/jspdf.browser.js
tests/functional/third-party-compatibility/jspdf.test.js

Fixing an issue with the SPA loader where wrapping of global Promise is causing a compatibility issue with the jspdf library. 
fixes https://github.com/newrelic/newrelic-browser-agent/issues/280
fixes [NEWRELIC-4683](https://issues.newrelic.com/browse/NEWRELIC-4683)

fix(promise): fix issue with jspdf library

---

CHANGELOG.md

Adds a change log entry that should have been included with PR 328.
- [NEWRELIC-5374](https://issues.newrelic.com/browse/NEWRELIC-5374)
- [PR 328](https://github.com/newrelic/newrelic-browser-agent/pull/328)
This change does not need to be tested, only reviewed.

Add log entry for babel build target changes

---

CHANGELOG.md
packages/browser-agent-core/src/common/harvest/harvest-scheduler.js
packages/browser-agent-core/src/common/harvest/harvest.js
packages/browser-agent-core/src/common/util/feature-base.js

This PR is a follow-up to #362 .  There were some QoL comments needed after merging with main.

QoL comments and touch-ups

---

CHANGELOG.md
tools/jil/util/browsers-supported.json

Adds a description of the upcoming release to `CHANGELOG.md`.

Update change log in preparation for 1223 release.

---

README.md
tools/jil/util/browsers-supported.json

This PR updates the readme to remove references to old processes.
NEWRELIC-5229
NEWRELIC-5183
N/A

Remove references to old build info in readme

---

tests/browser/xhr/fetch.browser.js

This is a minor change to some JIL unit tests where the test could possibly fail due to how much faster the tests are running.
N/A
Run the CI workflow.

Minor change for local jil unit test failures

---

README.md

This PR just adds informational badges from the release repo, and some badges about the main branch status.

Add general status badge info to readme

---

.eslintrc.js
.github/workflows/dev-pr.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-internal-prod.yml
.github/workflows/publish-release.yml
tools/jil/util/browsers-supported.json
tools/scripts/docs-website/create-docs-pr.js
tools/scripts/docs-website/git-commands.js
tools/scripts/upload-ab-to-s3.js

This PR adds minor improvements to the CI-CD actions
* Add github metadata to the internal deployment builds, to help differentiate in the dashboard charts
* Add inputs for email and username for facilitation with docs-site PRs

CI-CD Minor Improvements

---

.github/workflows/ci.yml

Fixing codecov

---

webpack.config.js

Updated the webpack config to also generate a json file for the build stats that will be stored in the build directory. These stats files will be uploaded to S3 and used in future build analysis and possible inclusion in the docs site.
This is a good start for https://issues.newrelic.com/browse/NEWRELIC-6740 but does not finish that ticket.

Adding plugin to generate build stats for upload to cdn

---

tools/scripts/diff-sizes.mjs

Fixing the percentage calculations for the size diff comment made on PRs.
https://issues.newrelic.com/browse/NEWRELIC-7767
N/A

NEWRELIC-7767: Fix diff size percent

---

CHANGELOG.md

Modifies language and links in the change log entries for v1.229.0.
N/A
No code changes in this PR.

Edits to change log for v1.229.0

---

.github/workflows/ci.yml
docs/unit-testing.md
package.json

Documentation for writing unit tests using jest.
https://issues.newrelic.com/browse/NEWRELIC-7869

chore: Documenting unit testing

---

.github/workflows/publish-release.yml
.github/workflows/raise-release-notes-pr.yml
tools/scripts/docs-website/create-docs-pr.js
tools/scripts/docs-website/git-commands.js

This PR updates the release notes GHA's to work with the shared bot user.
NR-103815
An action run was appended as a comment to this PR

Fix Docs Site PR CI - NR-103815

---

CHANGELOG.md
README.md
babel.npm.cjs.js
babel.npm.esm.js
package.json
tests/functional/npm/basic.test.js
tools/jil/util/browser-matcher.js
tools/test-builds/raw-src-wrapper/.npmrc
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/raw-src-wrapper/src/browser-agent.js
tools/test-builds/raw-src-wrapper/src/custom-agent-lite.js
tools/test-builds/raw-src-wrapper/src/custom-agent-pro.js
tools/test-builds/raw-src-wrapper/src/custom-agent-spa.js
tools/test-builds/raw-src-wrapper/src/micro-agent.js
tools/test-builds/raw-src-wrapper/src/worker-agent.js
tools/test-builds/raw-src-wrapper/src/worker-init.js
tools/test-builds/raw-src-wrapper/src/worker-wrapper.js
tools/test-builds/raw-src-wrapper/webpack.config.js

Updating the npm package build process to account for our browser support list. Also including the `src` directory in the npm package for power users.
https://issues.newrelic.com/browse/NEWRELIC-7896
Test workflow should pass

fix: npm package browser support

---

.github/workflows/publish-release.yml
tools/scripts/docs-website/create-docs-pr.js

There was a typo in the release action that prevented PRs from working with the docs site.  This fixes that.
https://issues.newrelic.com/browse/NEWRELIC-7894

Fix typo in release action - NEWRELIC-7894

---

.github/workflows/repolinter.yml
DEVELOPING.md
README.md
package-lock.json

Addressing repolint errors.
https://issues.newrelic.com/browse/NEWRELIC-7014
N/A

chore: fix readme repolint errors

---

.eslintrc.js
tools/testing-server/utils/url.js

Enabling the `no-prototype-builtins` lint rule and fixing linting errors.
https://issues.newrelic.com/browse/NR-87768

chore: Enable no-prototype-builtins lint rule

---

.eslintrc.js
src/common/event-emitter/contextual-ee.test.js
src/common/event-emitter/register-handler.test.js
src/features/page_view_timing/aggregate/index.js
src/features/spa/aggregate/index.js
src/loaders/agent.js
tests/specs/api.e2e.js
tools/scripts/check-nrdb.js
tools/scripts/upload-to-nr.js
tools/wdio/config/sauce.conf.mjs

Enabling the `dot-notation` lint rule and running auto fixes.
https://issues.newrelic.com/browse/NR-87755

chore: Enable dot-notation lint rule

---

.github/workflows/ci.yml
.github/workflows/publish-dev.yml
package-lock.json
package.json
tools/scripts/diff-sizes.mjs
tools/scripts/npm-build-stats.js

Adding PR commenting for NPM package consumption.
https://issues.newrelic.com/browse/NEWRELIC-8077
Should comment on this PR.

chore: Add build stats for NPM package

---

.github/workflows/publish-dev.yml

Fix the piblish dev workflow maybe

chore: fix publish dev workflow

---

.github/pull_request_template.md

Update the GitHub PR template to help guide release please implementation
---

chore: Update PR template for release please

---

tests/functional/err/custom-handler.test.js

The `setErrorHandler` method now supports applying custom fingerprints to exceptions. Events with the same fingerprint appear grouped together in the New Relic One errors inbox.
---
This dummy PR is for documentation purposes. The branch makes a minimal, arbitrary change so the title and header (above) get picked up in change logs and release notes for v1.232.0.
https://github.com/newrelic/newrelic-browser-agent/pull/443/
N/A

feat: Allow custom error grouping

---

.github/workflows/publish-release.yml
.github/workflows/raise-release-notes-pr.yml
tools/scripts/check-nrdb.js
tools/scripts/upload-to-nr.js

Address some blocking CI issues before cutting v1.232.0
---
This PR addresses some CI issues that were observed in v1.231.0
NEWRELIC-8375
N/A

chore: Fix basic CI issues before release - NEWRELIC-8375

---

package-lock.json
src/common/session/session-entity.js
src/features/utils/agent-session.js
tests/assets/session-entity.html
tests/specs/session-manager.e2e.js
tools/browsers-lists/browsers-supported.json

Add internal metrics to track the duration of the average session to improve estimation for future efforts.
---
- Fixes some missed cases with the session length supportability metrics.
- Creates and uses a specific `session-entity.html` test asset instead of generic `instrumented.html`.

feat: Minor changes to SMs

---

.github/workflows/dev-pr.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-experiment.yml
package-lock.json
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

Minor changes discovered while implementing the session replay experiments
---
This PR adds minor CI fixes that were discovered while working through publishing session replay experiments.

chore: Minor CI fixes

---

.github/workflows/publish-release.yml
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

This PR makes one or more changes to release-related CI/CD and should be merged just prior to the next release.
---
- Add a missing `v` in the version tag argument to the `create-docs-pr.mjs`.
N/A
If desired, specific changes can be tested piecemeal on the command line.

chore: Make fixes and changes to release workflows

---

src/common/harvest/harvest.js
tests/functional/metrics.test.js
tools/jil/runner/index.js
tools/test-builds/browser-tests/package-lock.json

Updating jsdocs for the harvest class
---
Updating jsdocs for the harvest class
N/A
N/A

chore: update jsdoc for harvest

---

package-lock.json
tools/browsers-lists/browsers-supported.json
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/builder.js
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json

Adding threading to the test-build process.
---
The build of the npm package wrappers will now be threaded.
N/A
Pull the branch and run `npm run build:all`.

chore: threaded test builds

---

README.md

This is a minor update to the README.md to reflect the lag between deployed versions and the currently released version.
---

chore: Add language about deployment version lag

---

.github/workflows/main-push.yml
.github/workflows/pull-request-checks.yml
.github/workflows/wdio-all-browsers.yml
.github/workflows/wdio-single-browser.yml
package-lock.json
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

---
Adding the full wdio test suite to the pr checks workflow and fixing the main push workflow to collect coverage from jest.
N/A
N/A

chore: update pull request workflow

---

src/features/metrics/aggregate/index.js

Adding new supportability metrics to gauge the usage of performance marks and measures by our customers.
---
Adding new supportability metrics to gauge the usage of performance marks and measures by our customers.
N/A
N/A

chore: SMs for performance marks and measures

---

tools/scripts/post-build-cleanup.js
webpack.config.js

Prevent the build process of the agent from creating minified variable names that only contain the dollar symbol. If such a variable is immediately followed by an ampersand, as could be the case in a minified logic block, it could be picked up by  string replacement logic applied to outgoing HTML within their server.
---
Prevent the build process of the agent from creating minified variable names that only contain the dollar symbol. If such a variable is immediately followed by an ampersand, as could be the case in a minified logic block, it could be picked up by  string replacement logic applied to outgoing HTML within their server.
In the one case we saw, it appears the customer is either performing their own injection logic or performing some custom string replacement or interpolation …

fix: prevent dollar symbol only variable names

---

.github/workflows/publish-dev.yml

---
Fixing the app id secret used for the staging a/b testing script.
N/A

chore: fix the a/b staging app id

---

package-lock.json
package.json
tools/browsers-lists/browsers-supported.json
tools/webpack/configs/common.mjs
tools/webpack/configs/polyfills.mjs
tools/webpack/configs/standard.mjs
tools/webpack/configs/workers.mjs

---
Fixing the webpack config so async chunks are always minified and all builds except local set the webpack mode to `production`. This will ensure our experiments and dev builds are as small as possible, better represent a production build, and will ensure our size checks will reflect what our customers will see.
N/A

chore: always minify async chunks

---

tools/browsers-lists/browsers-supported.json
tools/webpack/env.mjs

---
This fixes the version that gets injected into the build when running the dev build. We will now be able to see the difference in New Relic for data coming from the existing 1.237.1 release version and the 1.237.1-dev next release version.

chore: fix version reported for dev build

---

tools/webpack/configs/workers.mjs

---
Fixing the async chunk naming for the worker build.

chore: fix worker async asset chunk name

---

tools/webpack/configs/polyfills.mjs

---
Fixing the async chunk name for the polyfills build.

chore: fix polyfills async asset chunk name

---

tests/functional/spa/jsonp.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/browser-tests/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json

---
This fixes the flakiness of these tests.
N/A

chore: fixing flakey jsonp jil test

---

.github/workflows/publish-dev.yml
package-lock.json
tools/browsers-lists/browsers-supported.json

---
Fixing an error in the dev publish workflow that is causing the workflow to always skip.
N/A

chore: fix dev publish workflow not running

---

src/features/metrics/aggregate/index.js

---
This adds three new supportability metrics that are based on the detected runtime environment. This will defer from loader type in cases where the customer is building their own agent from source or npm.
N/A

chore: adding runtime sm

---

.github/workflows/publish-release.yml

This minor release only contains a fix to our internal release process and includes all the same changes as 1.239.0.
---
Fix release process

fix: Fix internal release process

---

.github/actions/docs-pr/action.yml
.github/actions/nr-upload/index.js
.github/actions/nr-verify/index.js
.github/actions/shared-utils/fetch-retry.js
.github/actions/update-current/index.js

chore: fixed issues in the CI pipeline

---

tests/specs/third-party-compatibility/run-test.js

---
Removing some unnecessary testing in the third party scripts that seems to have a lot of flakiness. It doesn't really have anything to do with the original issues.

chore: remove unnecessary testing in third parties

---

.github/actions/build-ab/template.js

chore: CI - add string wrapping to template

---

src/loaders/api/api.js
tests/assets/rrweb-record.html
tools/webpack/configs/standard.mjs

This adds the static definitions to include SR in pro and spa builds
---

chore: Fix sr build

---

.github/actions/build-ab/index.js
package-lock.json

chore: fix undefined typeerror in ab script

---

.github/actions/build-ab/index.js

chore: use experimental loader for experiments

---

.github/actions/docs-pr/constants.js
.github/actions/docs-pr/index.js
.github/actions/post-release-updates/action.yml
.github/actions/post-release-updates/args.js
.github/actions/post-release-updates/constants.js
.github/actions/post-release-updates/index.js
.github/actions/shared-utils/child-process.js
.github/actions/shared-utils/git-cli-runner.js
.github/workflows/post-release-updates.yml
.husky/pre-commit

---
This adds a new GH actions and workflow that will be called after a release is created to perform repository updates:
- Update caniuse-lite database
- Update saucelabse browsers lists
- Update third-party licenses
The workflow can also be ran manually to trigger these updates.
https://issues.newrelic.com/browse/NR-137669

chore: Automating post-release repo updates

---

.github/actions/build-ab/action.yml
.github/actions/internal-ab/action.yml

---
I forgot to update the wrapping composite action `internal-ab`. I also had to set the new inputs to not be required for the production deployment.

chore: fix ab deployment

---

.github/workflows/publish-release.yml

chore: Fix typo in publish release

---

tests/specs/framework-detection.e2e.js

---
Fixing the framework detection test that keeps failing while running with coverage enabled.

chore: fix integration coverage test failures

---

.github/actions/build-ab/index.js

The env argument is required for the template to set application versions in staging only 
---

chore: CI - Add back environment argument to template

---

codecov.yml

---
Adding codecov ignore rules to remove code coverage reporting on non-source code files.

chore: Updating codecov ignore rules

---

src/loaders/browser-agent.js

Add SR instrumentation entrypoint to NPM ahead of the upcoming Limited Preview window
---
This PR exposes SR to the default NPM deployed loader code.

feat: Add SR entrypoint to NPM ahead of LP

---

package-lock.json
package.json

For consistency with the UI, RRWeb should only be upgraded explicitly and with coordination with UI
---

chore: Keep rrweb on a static version until explicitly upgrading

---

.github/workflows/publish-dev.yml

chore: Fix the dev pub workflow

---

.github/workflows/wdio-all-browsers.yml

---
Splitting up the iOS wdio tests to run one version per job.

chore: split ios wdio testing

---

.github/actions/build-ab/handlebars.js
.github/actions/build-ab/index.js
.github/actions/build-ab/templates/postamble.js
.github/actions/build-ab/templates/released.js
.github/workflows/publish-internal.yml
.github/workflows/publish-release.yml

---
Added a new handlebars helper that we can use to inject different parts of the internal loader code based on the environment. This was used to set the masking options for dev and staging so no masking would occur. 
https://issues.newrelic.com/browse/NR-138408

chore: unmask sr for dev and staging internal environments

---

.github/actions/s3-upload/asset-cache.js

---
Fix the cache header application logic.

chore: Asset cache header application

---

package.json
src/.npmignore

---
Removing the unit test files from the npm package and adding the changelog.
N/A

chore: cleanup npm package

---

.github/workflows/nightly.yml

---
Adding a job to the nightly workflow to verify our internal A/B assets are accessible from our CDN.
https://issues.newrelic.com/browse/NR-162361

chore: Adding nightly job to verify A/B assets

---

.github/actions/docs-pr/index.js

---
Minor docs PR script update based on comments in last release: https://github.com/newrelic/docs-website/pull/14779#discussion_r1346190838
N/A

chore: copy over recommended docs pr changes from previous release

---

src/features/session_replay/aggregate/index.js

Add a two-step sliding window to ensure 15-30 second buffer time for applicable error replays
---
The previous implementation had the possibility to harvest shortly after a new checkout, leading to a very short error buffer.  The two-step sliding window will ensure that the shortest buffer in that scenario would be 15s instead of 0.
https://issues.newrelic.com/browse/NR-125668
Existing tests should continue to pass, as the only thing this changes is the minimum length of the buffer in the case of subsequent checkouts

feat: Ensure 15 second minimum error buffer when possible

---

src/common/util/console.js
src/loaders/agent-base.js
src/loaders/agent.js

---
This is just some minor updates to the jsdocs for the APIs.
https://issues.newrelic.com/browse/NR-141636

chore: minor jsdocs updates

---

.github/workflows/publish-experiment.yml

Experiment's public paths did not include changes for sub directory change to CI process
---

chore: fix experiment build

---

.github/actions/notify-repository/action.yml
.github/workflows/publish-release.yml

chore: Add action to notify external repos

---

src/features/ajax/aggregate/index.js

This PR adds a SM that detects GQL, to be used for internal call_count (total GQL payloads seen) and value (bytes added to payloads) evaluations
---

chore: Add SM for GQL detection

---

README.md

This PR adds a section that links to the API docs, and a section describing the current state of Session Replay
---
This PR adds a section that links to the API docs, and a section describing the current state of Session Replay
https://new-relic.atlassian.net/browse/NR-166326
No source code or tests should be affected

chore: Add API and SR notes in readme

---

THIRD_PARTY_NOTICES.md
package-lock.json
third_party_manifest.json
tools/browsers-lists/browsers-supported.json
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/browser-tests/package.json
tools/test-builds/library-wrapper/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json

When this PR is merged, caniuse-lite database is updated, latest browserslist for SauceLabs is retrieved, and third-party dependencies docs are updates.
---
This PR was generated with post-release-updates GitHub action.

chore: Post release repo updates

---

.editorconfig
CONTRIBUTING.md
README.md

---
Fixing http links to https.
https://new-relic.atlassian.net/browse/NR-175297

chore: Fixing http links to https

---

tools/wdio/plugins/mocha-globals/globals.mjs

chore: fix wdio import breaking tests

---

README.md

---
Adding a note in the README regarding executing the browser agent in a SSR app.
#802

chore: add note for ssr

---

src/loaders/api/api.js

---
The Create Tracer API does not have a tracking SM and this is required for eval of new SPA usage.
https://source.datanerd.us/agents/angler/pull/513

chore: Add Supportability Metric for CreateTracer API

---

src/features/metrics/aggregate/index.js
src/loaders/configure/nonce.js
tests/specs/csp.e2e.js

---
Adding a SM for nonce detection.
https://source.datanerd.us/agents/angler/pull/514

chore: adding nonce sm

---

src/features/spa/aggregate/index.js

---
Adding SM to track the current SPA feature interaction duration faceted by category.
https://new-relic.atlassian.net/browse/NR-167103
https://source.datanerd.us/agents/angler/pull/516

chore: adding sm for interaction duration

---

.github/actions/docs-pr/action.yml
.github/actions/docs-pr/args.js
.github/actions/docs-pr/index.js
.github/workflows/post-release-updates.yml
.github/workflows/publish-release.yml
.github/workflows/release-please.yml

---
Updating workflows to use new fine grained access tokens.

chore: update automation

---

.github/actions/docs-pr/index.js
.github/workflows/publish-release.yml

---
Split the nrdb publish up.
N/A

chore: split nr db update

---

tests/specs/api.e2e.js
tests/specs/deferred-loaders.e2e.js
tests/specs/harvesting/final-harvesting.e2e.js
tests/specs/metrics.e2e.js
tests/specs/proxy.e2e.js
tests/specs/session-replay/session-pages.e2e.js
tests/specs/stn/with-replay-error-mode.e2e.js
tests/specs/stn/with-session-replay.e2e.js
tests/specs/third-party-compatibility/jspdf.e2e.js
tests/specs/third-party-compatibility/mootools.e2e.js
tests/specs/third-party-compatibility/requirejs.e2e.js
tests/specs/xhr/retry-harvesting.e2e.js
tools/browser-matcher/common-matchers.mjs

---
Working on test flankiness.

chore: working on test flakiness

---

.github/actions/package.json
tools/test-builds/library-wrapper/package.json

---
Updating workflow dependencies and one test builds dependency.

chore: updated workflow action dependencies

---

.github/workflows/publish-dev.yml
.github/workflows/publish-release.yml

This PR comments out the staging NRDB actions from CI
---

chore: comment out stage actions

---

.github/actions/build-ab/templates/experiments.js
.github/actions/build-ab/templates/postamble.js

chore: disable SR and ST for experiments

---

.github/actions/nr-verify/action.yml
.github/workflows/publish-release.yml

chore: add env param to exclude stage in CI

---

.github/actions/docs-pr/action.yml
.github/actions/docs-pr/args.js
.github/actions/docs-pr/constants.js
.github/actions/docs-pr/index.js
.github/actions/docs-pr/templates/release-notes.handlebars
.github/actions/docs-pr/utils.js
.github/workflows/publish-release.yml

---
Updated the docs pr automation to create the branch in the docs-website repo instead of using the forks org.
https://new-relic.atlassian.net/browse/NR-221376

chore: Update docs pr automation

---

package.json

Adding typescript types mappings for the ESM distribution in the npm package.
---
Adding typescript types mappings for the ESM distribution in the npm package.
https://new-relic.atlassian.net/browse/NR-217592

feat: add types mappings for esm distribution

---

tests/specs/adblocker.e2e.js

---
Fixing adblock tests running on IE 11.

chore: fix adblock tests for ie

---

src/features/ajax/instrument/index.js

---
Adding SM to determine if customers are using deprecated CAT headers.

chore: cat header sm

---

src/features/ajax/instrument/index.js

chore: fix xhr sm introduced bug

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md

No summary
---
https://new-relic.atlassian.net/browse/NR-82178

chore: Update bug report template

---

tools/testing-server/index.js
tools/testing-server/plugins/test-handle/index.js
tools/testing-server/routes/bam-apis.js
tools/testing-server/test-handle.js

---
Adding rum response headers to support the timestamp normalization work. The test handler has been updated to allow defining scheduled replys with headers to be set or removed.
https://new-relic.atlassian.net/browse/NR-222414

chore: Adding headers and header support

---

src/loaders/api/api-methods.js
src/loaders/api/api.js
src/loaders/api/api.test.js
tests/specs/api.e2e.js
tests/specs/npm/index.e2e.js
tools/test-builds/browser-agent-wrapper/src/worker-wrapper.js
tools/test-builds/raw-src-wrapper/src/worker-wrapper.js

---
This just adds some tests to verify we are exposing the api methods correctly on the npm agent. We are not going to type the `api` property on the agent for now.
closes https://github.com/newrelic/newrelic-browser-agent/issues/895

chore: add tests to check for exposed api methods

---

.github/workflows/publish-dev.yml
.github/workflows/publish-experiment.yml
.github/workflows/publish-release.yml

---
Updated the three release workflows to incorporate purging and verifying of assets in both CDNs.

chore: add staging cdn purging

---

.github/actions/find-pull-request/index.js

---
The action was not filtering the PR list correctly for some stupid reason.

chore: fix find-pr action

---

README.md

---
Fix small typo in the README

chore: Fix Readme typo

---

README.md

---
We are changing our vuln reporting platform from HackerOne to BugCrowd hence the change

chore: Update vulnerability reporting URL

---

tests/specs/session-replay/adjacent-payloads.e2e.js
tools/testing-server/constants.js
tools/wdio/plugins/custom-commands.mjs

chore: set entityguid to a real value for better posterity

---

.github/actions/build-ab/templates/experiments.js

chore: Enable ST and SR

---

tests/assets/ajax/xhr-readystate-after-send.html
tests/assets/ajax/xhr-readystate-before-send.html
tests/specs/ajax/xhr-readystatechange-wrapping.e2e.js

chore: fix tests for IE

---

.github/actions/internal-ab/action.yml
.github/workflows/pull-request-checks.yml

---
Removed a duplicate call to start the size check assets in the pr checks workflow and added calls to purge the staging cdn cache in the internal-ab action.
https://new-relic.atlassian.net/browse/NR-254263

chore: fix workflows

---

.github/actions/build-ab/templates/postamble.js

---
Adding postamble code to set some custom properties on our internal systems in an effort to test the time keeper.

chore: ab testing timekeeper internally

---

.github/actions/internal-ab/action.yml

chore: fix the thing

---

.github/actions/build-ab/templates/postamble.js

---
Adding more properties to the timekeeper ab testing.

chore: more ab testing timekeeper

---

.github/workflows/publish-experiment.yml
.github/workflows/publish-release.yml

---
We were only purging the loader in the experiments. Tisk Tisk

chore: fix experiment publish purge

---

tools/jil/bin/server.js
tools/testing-server/README.md
tools/testing-server/index.js
tools/testing-server/routes/bam-apis.js
tools/testing-server/routes/tests-index.js
tools/testing-server/test-handle.js
tools/wdio/bin/server.js
tools/wdio/plugins/testing-server/index.mjs
tools/wdio/plugins/testing-server/launcher.mjs
tools/wdio/plugins/testing-server/test-handle-connector.mjs

---
Removing the separate CORS testing server. We use to BAM server for testing CORS support/issues.
N/A

chore: remove unused cors server

---

README.md

---
https://new-relic.atlassian.net/browse/NR-247048

chore: Update SR sections of readme ahead of GA

---

package.json

Note: To utilize this local script, you must add `STAGE_API_KEY` to your local variables
---

chore: add helper script for publishing to nrdb stage locally

---

src/loaders/api/api-methods.js
src/loaders/api/api.js
tests/components/api.test.js
tests/unit/loaders/api/api.test.js

Add Logging API interface and central handling mechanism as customer interface for capturing logging data
---
https://new-relic.atlassian.net/browse/NR-251068
https://new-relic.atlassian.net/browse/NR-251074
Jest unit tests have been updated to check for EE events.  WDIO tests to be added after feature/havesting is implemented

feat: Add Logging API entry points and central handler

---

.gitignore
package-lock.json
package.json
tools/wdio/args.mjs
tools/wdio/config/lambdatest.conf.mjs
tools/wdio/runner.mjs

---
Adding support for running wdio tests using LambdaTest. To use, pass the `--lt` flag when running wdio tests. Only desktop browsers are supported in this PR.
https://new-relic.atlassian.net/browse/NR-254273

chore: add support for lambdatest

---

.github/workflows/wdio-all-browsers.yml
.github/workflows/wdio-single-browser.yml
tools/wdio/args.mjs
tools/wdio/config/lambdatest.conf.mjs
tools/wdio/runner.mjs

---
https://new-relic.atlassian.net/browse/NR-254315

chore: Switch PR checks & wdio workflow to use LT

---

.github/actions/build-ab/templates/postamble.js
src/features/session_trace/aggregate/index.js

chore: add postamble script to wrap console.log in staging

---

.github/actions/build-ab/templates/postamble.js
src/features/logging/shared/utils.js
src/features/session_trace/aggregate/index.js
tests/assets/logs-api-wrap-logger-error-object.html
tests/components/logging/utils.test.js
tests/specs/logging/harvesting.e2e.js

chore: Internal log actions

---

src/features/logging/aggregate/index.js
src/features/logging/constants.js
src/features/logging/shared/log.js
src/features/logging/shared/utils.js
src/loaders/agent-base.js
src/loaders/api/api.js
tests/components/api.test.js
tests/components/logging/aggregate.test.js
tests/components/logging/utils.test.js
tests/specs/logging/harvesting.e2e.js
tests/unit/common/config/state/init.test.js

chore: Final Logs cleanup - entity guid and level

---

.github/workflows/wdio-all-browsers.yml
tests/specs/ajax/fetch.e2e.js
tests/specs/pvt/bfcache.e2e.js
tests/specs/rum/index.e2e.js
tests/specs/rum/retry-harvesting.e2e.js
tests/specs/rum/under-session.e2e.js
tests/specs/spa/jsonp.e2e.js
tools/wdio/config/lambdatest.conf.mjs

---
Add iOS tests back into PR checks.
https://new-relic.atlassian.net/browse/NR-277086

chore: Re-enable ios in tests

---

tools/browser-matcher/matcher-rule.mjs

chore: fix wdio - oops

---

tests/specs/ajax/index.e2e.js
tests/specs/harvesting/disable-harvesting.e2e.js
tests/specs/harvesting/final-harvesting.e2e.js
tests/specs/harvesting/index.e2e.js
tools/testing-server/network-capture.js
tools/testing-server/plugins/test-handle/index.js

---
Migrating tests in `tests/specs/harvesting` to use network capturing.

chore: migrate harvest tests to network capture

---

tools/wdio/config/lambdatest.conf.mjs

---
Removing the hard coded appium version.

chore: remove hard coded appium version

---

package.json
src/cdn/experimental.js
src/cdn/polyfills/pro.js
src/cdn/polyfills/spa.js
src/cdn/pro.js
src/cdn/spa.js
src/common/config/state/init.js
src/features/generic_events/aggregate/index.js
src/features/generic_events/constants.js
src/features/generic_events/index.js
src/features/generic_events/instrument/index.js
src/features/utils/aggregate-base.js
src/features/utils/lazy-feature-loader.js
src/index.js
src/loaders/browser-agent.js
src/loaders/features/features.js
tests/unit/common/config/state/init.test.js
tests/unit/loaders/browser-agent.test.js
tools/test-builds/browser-agent-wrapper/src/custom-agent-pro.js
tools/test-builds/browser-agent-wrapper/src/custom-agent-spa.js
tools/test-builds/raw-src-wrapper/src/custom-agent-pro.js
tools/test-builds/raw-src-wrapper/src/custom-agent-spa.js
tools/testing-server/constants.js

Create a feature that will normalize, aggregate and harvest all generic events.
---
NR-291171
Feature testing to be added when real data begins flowing through the new feature

feat: Create generic events feature

---

.github/workflows/nightly.yml

---
End of life for each version determined by the date/table stored in NRDB. If on nightly run, that date has been reached for a version, it will be deprecated. Already deprecated versions will remain as is.
https://new-relic.atlassian.net/browse/NR-178689

chore: Check for and deprecate NPM versions outside support window

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json
tools/wdio/config/lambdatest.conf.mjs

---
Updating wdio settings to enable failure messages in the lt console.

chore: update lt settings

---

docs/supportability-metrics.md
src/features/generic_events/aggregate/index.js

Record a SM when the 1,000 node limit is reached
---

chore: Add GenericEvents max sm

---

tests/specs/logging/harvesting.e2e.js

---
Migrating the logging specs to use network capturing.
https://new-relic.atlassian.net/browse/NR-287581

chore: migrate logging test to use network capture

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

---
Pinning fflate and web-vitals dependencies to the specific version that was last recorded in the package-lock.json file.
https://new-relic.atlassian.net/browse/NR-300087

chore: pinning bundled dependencies

---

tests/specs/ins/harvesting.e2e.js
tests/specs/ins/retry-harvesting.e2e.js

---
Migrating insights specs to use network capturing.
https://new-relic.atlassian.net/browse/NR-287580

chore: migrate insights specs to network capture

---

tests/specs/npm/index.e2e.js
tests/specs/npm/micro-agent.e2e.js

---
Update the npm spec files to use network capturing.
https://new-relic.atlassian.net/browse/NR-287583

chore: migrate npm tests to use network capture

---

tests/specs/pvt/bfcache.e2e.js
tests/specs/pvt/retry-harvesting.e2e.js
tests/specs/pvt/timings.e2e.js

---
Update the pvt specs to use network capturing.
https://new-relic.atlassian.net/browse/NR-287584

chore: update pvt specs to network capturing

---

.github/actions/build-ab/templates/postamble.js

chore: postamble - point queries at browser agent team

---

docs/supportability-metrics.md
src/features/metrics/aggregate/index.js
tests/assets/iframe/iframe-detection.html

Add SMs detecting whether the agent is running in an iframe or if iframes are present on the tracked context
---
https://new-relic.atlassian.net/browse/NR-300493

chore: IFrame SMs

---

tests/specs/graphql-metadata.e2e.js

---
The graphql tests are now passing in LambdaTest.
https://new-relic.atlassian.net/browse/NR-283054

chore: update graphql tests

---

tools/wdio/config/lambdatest.conf.mjs

chore: update webview app identifier

---

.github/actions/build-ab/templates/released.js

Allow M&M's to run internally via experiment by adding the flag for NR1
---

chore: add M&M config to internal template

---

.github/actions/build-ab/templates/released.js

chore: enable collection of resources in NR1

---

tests/webview-specs/ios/index.e2e.js

chore: Fix iOS webview test with LT

---

src/features/generic_events/aggregate/index.js
src/features/logging/aggregate/index.js
tests/components/logging/aggregate.test.js

This PR fixes some SMs that I noticed were not reporting to Angler.  They were missing the correct EE identifiers.
---

chore: fix sms

---

.github/actions/build-ab/templates/postamble.js

This PR adds logs to prod env to help facilitate logging platform tests
---

chore: add logs for prod

---

README.md
src/common/config/info.js
src/common/config/init.js
src/loaders/agent.js
src/loaders/browser-agent.js
src/loaders/micro-agent.js
tests/dts/agent.test-d.ts
tests/dts/agentoptions.test-d.ts
tests/dts/api.test-d.ts
tests/unit/common/config/init.test.js

---
https://new-relic.atlassian.net/browse/NR-362070
https://new-relic.atlassian.net/browse/NR-362072

chore: Add typing definition to Agent constructor options

---

docs/supportability-metrics.md
src/features/ajax/aggregate/index.js
src/features/generic_events/aggregate/index.js
src/features/jserrors/aggregate/index.js
src/features/logging/aggregate/index.js
src/features/session_replay/aggregate/index.js
src/features/soft_navigations/aggregate/index.js
src/features/utils/aggregate-base.js
src/features/utils/feature-base.js
tests/components/logging/aggregate.test.js

Fix logging analytics metrics and centralize the metrics reporter for easier use
---
This is related to the auto-logging GA effort, to evaluate successful implementation across deployments.
Please review https://source.datanerd.us/agents/angler/pull/666

fix: Add logging analytic metrics and fix browser performance metrics

---

LICENSE

see https://newrelic.slack.com/archives/C03H50EAN06/p1740672156346779 for more info
---
NR-364541

chore: update license statement

---

.github/workflows/branch-cleanup.yml

Fix duplicated workflow step id
---

chore: Fix workflow step id

---

src/common/event-emitter/contextual-ee.js
src/common/harvest/harvester.js
src/common/util/feature-flags.js
src/features/utils/aggregate-base.js
src/features/utils/event-store-manager.js
src/loaders/api/api.js
src/loaders/configure/configure.js
tests/assets/all-events.html
tests/assets/inspection-events.html
tests/components/setup-agent.js
tests/specs/inspection-events.e2e.js
tests/unit/features/utils/aggregate-base.test.js
tests/unit/features/utils/event-store-manager.test.js

Adds inspection events that detail when various agent-related events occur. These events can be listened to on the event listener 'newrelic' string type. Events include agent initialization, agent fully loaded, event buffered, event harvested, and api calls. 
---
A test file is included to test whether the global dispatch events work at all. We can get more in-depth on the testing if desired but there are a _lot_ of events that happen after agent load.
JIRA: https://new-relic.atlassian.net/browse/NR-375506

feat: Inspection events

---

.github/workflows/nightly.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request-checks.yml

chore: update to github marketplace item

---

src/loaders/api/api.js
tests/assets/soft_navigations/sequential-api.html
tests/specs/soft_navigations/integration.e2e.js

chore: change api this context to fix unit tests

---

tests/specs/ajax/xhr.e2e.js

chore: Fix random test failure

---

docs/supportability-metrics.md

---
https://new-relic.atlassian.net/browse/NR-341205

chore: Add SM notes

---

src/features/session_replay/shared/recorder.js

This fixes a bad reference to a parent function that is not accessible.
---
https://new-relic.atlassian.net/browse/NR-341205

fix: Call handle directly for submitting SM

---

src/common/constants/agent-constants.js
src/features/utils/entity-manager.js
src/features/utils/event-store-manager.js

Store all data and entity information under the same default key for better consistency
---

chore: strengthen get behavior

---

src/features/generic_events/aggregate/index.js
src/loaders/api/measure.js
tests/assets/measure-api-postload.html
tests/assets/measure-api-preload.html
tests/components/api.test.js
tests/specs/ins/measure-api.e2e.js

Add missing attribute to the event generated by the measure API as well as attempt to stabilize flaky tests with WDIO/Lambda
---
New unit and e2e tests have been added that are more explicitly testing behavior

chore: measure API tweaks

---

README.md

Updated the readme to add missed features and add a new usage example based on customer questions.
---

chore: update readme features

---

.github/actions/build-ab/templates/experiments.js
.github/actions/build-ab/templates/latest.js
.github/actions/build-ab/templates/postamble.js
.github/actions/build-ab/templates/released.js

Remove attributes from UserActions internally in NR1
--- 
https://newrelic.enterprise.slack.com/archives/C0936LENCEN

chore: remove innerText collection from NR1

---

.github/actions/build-ab/templates/experiments.js
.github/actions/build-ab/templates/latest.js

chore: allow session replay to run for ab account
