feature/spa/aggregate/index.js
tests/assets/spa/incorrect-timer.html
tests/functional/spa/timers.test.es6
tests/functional/spa/timers.test.js

Browser interactions (route changes) would wait forever if a setTimeout was called in the code without a callback (or the first argument different type than a function).
Test is included with the PR.

Fix for interaction waiting on setTimeout without callback

---

feature/err/instrument/index.js
feature/ins/instrument/index.js
feature/spa/instrument/index.js
feature/stn/instrument/index.js
feature/xhr/instrument/index.js
loader/index.js

---
Please describe the changes present in the pull request and if applicable, describe why the changes are needed.
This PR addresses a bug where the loader object is empty when opening in a file:// protocol containing the agent code. This empty object causes nested property assignment down the chain to error out.  The solution proposed here is to prevent the instrument files from executing if the protocol is invalid (file://).
Please include a link to the related …

check if protocol is allowed before execution

---

agent/harvest.js
feature/err/aggregate/index.js

---
Please describe the changes present in the pull request and if applicable, describe why the changes are needed.
The agent currently sends a call to `/jserrors/ping` every minute when there is no other harvest call made. The reason was to keep the HTTPS connection to our consumer open for old IE browsers (IE 9 and older).
The ingest team is removing the endpoint when browser ingest switches to Vortex. We need to align, and this creates a minimal impact as it only …

remove all references to pingErrors

---

contextual-ee/index.js
tests/browser/contextual-ee.browser.js

This PR addresses a memory-leak issue in the agent where an event emitter continues to buffer events even after the base event emitter has been aborted.
When the agent loads normally, the event emitter's buffer should be emptied after the aggregator has loaded and harvest cycles have begun. However, in some cases the aggregator can be blocked from loading by tools like ad blockers. If this happens, there is a timeout to ensure that after a period, the emitter is aborted and no unexpected events are emitted or buffered.
There is, however, for legacy reasons, a mechanism to override the abort behavior and force an emitter to continue to emit events after the base emitter has been aborted. The bug this PR fixes is that this forcing behavior also causes those events to be buffered. I'm adding …

Prevent buffering events if agent has been aborted

---

tools/jil/driver/TapeTestObserver.js
tools/jil/driver/TestRun.js
tools/jil/runner/index.js
tools/jil/test/tape-observer.test.js

This is a fix for retrying tests with failed child tests. The logic for observing tape tests has been extracted into a separate modules (covered by tests). 
I have extracted the logic for observing tape tests, and the main fix is in the new TapeTestObserver.js file on line 17, where I am adding child tests to be observed as well.

Retry tests with failed child tests

---

feature/ins/aggregate/index.js

Doubling the max number of page action events that can be sent per harvest.
https://github.com/newrelic/newrelic-browser-agent/issues/50

Increase the limit of page action events per harvest

---

feature/stn/aggregate/index.js
tests/functional/stn/harvest.test.js

A behavior in Session Trace's aggregation of the resourceTiming API caused an overlap in the resources collected across harvests. This showed up in the UI as certain Session Trace nodes having a duplicate on the timeline.

Prevent duplicate Session Trace 'resource' node

---

agent/timings.js
loader/timings.js
tests/browser/timings-lcp.browser.js
tests/functional/final-harvest.test.js

This PR adds a check in the final harvest on `recordUnload` to check for `pageHide`.  If `pageHide` has not already been handled, it adds it before unloading.  This will aid with future CLS queries.
[Issue](https://github.com/newrelic/newrelic-browser-agent/issues/47)

Final harvest should try pageHide

---

.github/workflows/publish-current.yml

The command line args were not getting properly passed in to the script. I have already tested it by running the action with this update to publish the 1209 version as current.

Fix publish current script

---

agent/harvest-scheduler.js
feature/xhr/aggregate/index.js
tests/assets/xhr-large-payload.html
tests/browser/xhr/ajax-events.browser.js
tests/functional/final-harvest.test.js
tests/functional/xhr/ajax-events.test.js

---
* If an app has thousands of AJAX requests in the harvest interval, the body could be too big and lots of data could be dropped.  There is a defined limit that can be placed on the agent.  We can check against that and break up the requests into multiple pieces if needed.
* Payload is evaluated in the AJAX serialization for size
* Payload is split into array items if exceeds the size limit on the loader
* The harvester loops through all array items in the harvest …

Handle max payloads

---

feature/xhr/aggregate/index.js
feature/xhr/instrument/index.js
tests/functional/xhr/ajax-events.test.js

This PR adds the attributes required to generate a Span event from an AjaxRequest event to the payloads of non-SPA AjaxRequest events.
Functional tests added to validate span attributes were created correctly 
https://github.com/newrelic/newrelic-browser-agent/blob/7ba7567e79691697f53e8d110f5269b00e0b0571/tests/functional/xhr/ajax-events.test.js

Add Span information to non-SPA AjaxRequest events

---

agent/timings.js
tests/assets/cls-multiple-big-then-small.html
tests/assets/cls-multiple-small-then-big.html
tests/browser/timings-lcp-cls.test.js
tests/browser/timings-lcp.test.js
tests/browser/timings.test.js
tests/functional/timings.test.js
tools/jil/runner/index.js

This PR modifies the way CLS is calculated to include looking at windows of time, and taking the maximum. CLS used to be cumulative for the whole page, however now we need to split it to look at a new CLS measurement after 1s between shifts or 5s total, and only keep the biggest one.
[Issue](https://github.com/newrelic/newrelic-browser-agent/issues/105)

update CLS to to max in window of time

---

.github/workflows/labels.yml
README.md

This PR points to the forked repo for the labeler, which has a change to address the issue that prevented labels from changing automatically on PRs
This should remove the `safe to test` label when a new commit is made.

update to use forked repo for label changer

---

loader/timings.js
tests/assets/lcp-pagehide.html
tests/functional/timings.test.js

Google's WebVital library does not record LCP values after the page has been hidden. This PR updates the way we capture LCP to align with that behavior.
https://github.com/newrelic/newrelic-browser-agent/issues/66
A functional has been added to validate that LCP events emitted after a pageHide are not captured.

Prevent recording LCP after pageHide

---

loader/event-listener-opts.js

This PR addresses an internal bug that was generating ierr objects.  It was expecting `addEventListener` to provide a callback `function`, while it was supplying `null`.  This just changes the compatibility test to provide a callback `function` and should cease the ierr generation.

cb function cannot be null or wrapper throws internal error

---

feature/wrap-events.js
loader/event-listener-opts.js

External code can pass in null as the second argument to the addEventListener method. When this happens, the agent throws an internal error. This change adds a check to protect against that.
This was discovered by testing with Vue, which uses the following to check if the browser supports passive listener.
https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/core/util/env.js#L33
The agent also has a similar check, which was passing in a noop function. I changed this to null, since it is now being handled.

Handle addEventListener with null function argument

---

feature/xhr/aggregate/deny-list.js
tests/browser/xhr/deny-list.browser.js

The logic for comparing domains did not work for one edge case - when the domain did not match the pattern (indexOf returning -1) and domain length was one character smaller than the pattern, then the result was evaluated as a match.

Fix for matching domain in Ajax deny list

---

feature/xhr/aggregate/index.js

Adding two supportability metrics for tracking ajax events that were excluded because of the deny list -
* `Ajax/Events/Excluded/App` for events generated by the application (excludes agent calls)
* `Ajax/Events/Excluded/Agent` for events generated by the agent
The reason there are two metrics is because the deny list by default contains the domain that the agent sends data to. Having these two metrics allows to verify the correct default behavior as well as detect changes in the deny list.

Supportability metrics for excluded Ajax events

---

agent/timings.js
tests/browser/timings-lcp-attributes.test.js
tests/functional/timings.test.js

This PR adds the [image URL](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint/url) (for LCP triggered by images) and [element.tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) attributes to LCP PageViewTiming events.
https://github.com/newrelic/newrelic-browser-agent/issues/145
Unit test was added to validate the new attributes are sent.

Add element identifying attributes to LCP

---

agent/timings.js
loader/timings.js
tests/browser/timings-fi-attributes.test.js
tests/browser/timings-lcp-attributes.test.js
tests/functional/timings.test.js

This PR adds attributes from the [NetworkInformation API](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation) to certain PageViewTiming event types (currently LargestContentfulPaint & FirstInteraction)
https://github.com/newrelic/newrelic-browser-agent/issues/144

Add NetworkInformation attributes to LCP & FI

---

agent/harvest.js
feature/stn/aggregate/index.js
tests/browser/harvest.browser.js
tests/browser/stn/stn.browser.js

This PR adds the session trace ID (`ptid`), if present, to the base querystring of harvest calls so events in that harvest can be associated with a session trace if one was active on the page.
Previously, `ptid` was added as a querystring argument to subsequent session trace (`/resources`) harvest calls, now any harvest calls after the initial session trace harvest call should include this parameter if a session trace is active.
https://github.com/newrelic/newrelic-browser-agent/issues/153
A test has been added to validate that the new querystring parameter is added.

Add Session Trace ID to other harvests

---

lib/versionify.js
tools/scripts/upload-to-s3.js

This changes the reference agent link in the loader to not include a version number

Remove dev deploy versions

---

agent/timings.js
tests/assets/instrumented-with-custom-attributes.html
tests/browser/timings-lcp-attributes.test.js
tests/functional/timings.test.js

Fixes https://github.com/newrelic/newrelic-browser-agent/issues/161
Related to https://github.com/newrelic/newrelic-browser-agent/pull/149
Renamed LCP PageViewTiming attribute from `url` to `elUrl` and `tag` to `elTag`. This makes the names less generic and as a result less likely to collide with custom attributes.

Updated LCP identifying attributes to have less generic names

---

feature/xhr/instrument/index.js
feature/xhr/instrument/parse-url.js
tests/browser/xhr/data-url.browser.js
tests/browser/xhr/parse-url.browser.js

As described in issue https://github.com/newrelic/newrelic-browser-agent/issues/163, agent harvests can fail when a data URL is fetched. This PR includes changes to identify when a request with a Data URL is made using Fetch or XMLHttpRequest and prevent those requests from aggregating telemetry.
We can revisit this change and consider adding support for Data URLs if a use-case for them comes up but currently the information in a Data URL request/response doesn't contain the information needed to create our existing AjaxRequest events or Ajax metrics.
https://github.com/newrelic/newrelic-browser-agent/issues/163
New Browser tests were created to validate that when an XHR or Fetch request is made that they do not result in an event being aggregated: …

Add handling for data URLs

---

loader/framework-detection.js

This PR fixes an issue for a niche bug that popped up in IE8.  It adds try catch fallbacks for unsupported DOM query methods.
Testing for this is difficult because IE8 is not officially supported by the browser agent, and the test suite is not ran against an instance of IE8.  IE8 emulation is also difficult to come by.  The problem changed can be found [here](https://caniuse.com/queryselector), and this should help alleviate the issue.

add try-catch blocks for compat with ie8

---

packages/scoped/src/index.ts
packages/scoped/src/index.unit.test.ts
packages/scoped/src/utils/config/build-configs.ts
packages/scoped/src/utils/features/initialize.ts

This PR adds NPM initialized features to the NREUM.initializedAgents property for debugging purposes.

add initialized features to NREUM.initializedAgents

---

cdn/webpack.config.js
packages/browser-agent-core/features/metrics/instrument/index.js

This PR points the CDN build output to `/build` folder for JIL tests

Build cdn to main build folder

---

cdn/agent-aggregator/util/featureDependencies.js
cdn/agent-loader/pro.js
feature/stn/instrument/index.js
packages/browser-agent-core/features/session-trace/aggregate/index.js
packages/browser-agent-core/features/session-trace/instrument/index.js
tests/assets/click.html
tests/assets/lotsatimers.html
tests/assets/sessiontraceerror.html
tests/assets/stn/ajax-disabled.html
tests/assets/stn/ensure-passive.html
tests/assets/xhr-monkey-patched.html
tests/functional/stn/ajax-disabled.test.js
tests/functional/stn/resource-harvest.test.js
tools/jil/driver/index.js

This migration was mostly adjusting code to account for the new scope of the class-based modules.
In session-trace aggregation, the functions passed to the HarvestScheduler needed access to class state, which I've implemented by binding the state to the function:
https://github.com/newrelic/newrelic-browser-agent/blob/81db9c2942b24a81a7bfaa166c0cb3ca6a49a0bc/packages/browser-agent-core/features/session-trace/aggregate/index.js#L84-L88
I'm very open to taking other approaches if they came up during other module migrations.
Commit 7c93c6e065d7e6f87d8097147b8556151aec9c7c handles the fact that in previous agent releases, the Ajax feature was always bundled with the Session Traces feature. The Session Trace feature currently depends on the Ajax feature's XHR decoration to generate XHR nodes …

Migrate session-trace tests for CDN agent

---

packages/browser-agent-core/common/config/config.js
packages/browser-agent-core/common/url/parse-url.js
packages/browser-agent-core/features/ajax/aggregate/index.js
packages/browser-agent-core/features/ajax/instrument/distributed-tracing.js
tests/browser/wrap-function/index.browser.js
tests/browser/wrap-function/no-events-for-recursive-wrapped-calls.browser.js
tests/browser/xhr/ajax-events.browser.js
tests/browser/xhr/data-url.browser.js
tests/browser/xhr/deny-list.browser.js
tests/browser/xhr/dt.browser.js
tests/browser/xhr/fetch.browser.js
tests/browser/xhr/index.browser.js
tests/browser/xhr/onreadystatechange.browser.js
tests/browser/xhr/parse-url.browser.js
tests/browser/xhr/response-size.browser.js
tests/browser/xhr/xhr-with-blob-body.browser.js

- `tests/browser/wrap-function/` folder migrated
- `tests/browser/xhr/` folder mgirated
Part of the "Migrate CDN Browser Tests" roadmap task.
Part of the "Migrate to NPM agent" project (tests conversion phase).
Tested both folders on local chrome@latest (macOS Monterey, .browser.js files) and,
Sauce's chrome@latest (windows 10, all files).
- 40 checks in wrap-function/
- 272 checks in xhr/

Test migration: finished browser wrap-function/ and xhr/

---

packages/browser-agent-core/common/config/state/runtime.js
packages/browser-agent-core/common/harvest/harvest.js
packages/browser-agent-core/common/window/session-storage.js
tests/browser/harvest.browser.js
tests/functional/harvest.test.js

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Details of the change can be found in [this CDD](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2522513791/JSESSIONID+Cookie+Change+Design+Document).
This commit:
- sunsets the `ck` param in harvest request URL to beacon
- creates and implement the new end-user generated `sessionId` in sessionStorage 
N/A
- `browser/harvest.browser.js` was updated to reflect this change
- `functional/harvest.test.js` was updated as well
**Other considerations:**
- (New) Unit testing deemed unnecessary at this time.
- Functionality of changes is closely tied to the functionality of sessionStorage itself. Hence, new automated functional tests are not added either.
-- Manually tested via navigation, e.g., …

Added sessionId and deprecated 'ck' param in query string

---

loader/timings.js
loader/visibility.js
packages/browser-agent-core/common/window/visibility.js
packages/browser-agent-core/features/page-view-timing/instrument/index.js
packages/browser-agent-core/features/spa/aggregate/interaction-node.js
tests/assets/pagehide-beforeload.html
tests/functional/timings.test.js

---
Previously, pages opened in the background and had a `visibilityState == 'hidden'` would continue to report the LCP metric, and an inflated one at that.
Now, in such cases the LCP will not be reported (or even buffered at all). 
Fixes #170 
- New html added to `tests/assets/`
- Test subcase appended to existing case in `tests/functional/timings.test.js`
In addition to manually pasting the Browser Agent, follow the test case in the related issue to add a basic …

Fix: LCP metric no longer reported on initially hidden pages

---

packages/browser-agent-core/features/session-trace/aggregate/index.js

A quick fix for an issue uncovered in testing the dev release. There was a case where certain session trace events would throw an error when being aggregated, caused by a nested anonymous function.

1217 Session Trace fix

---

packages/browser-agent-core/features/jserrors/instrument/index.js

This PR adds a custom attribute to unhandled promise rejection errors to add the ability to differentiate between promise rejections and window errors.

add custom attribute for unhandled promise rejections

---

cdn/agent-aggregator/aggregator.js
cdn/agent-loader/utils/configure.js
tests/assets/instrumented.html

Formerly, version 1218+ of the agent required ALL configuration blocks (nr.info, nr.init, nr.loader_config) to be present before the agent script.  This PR allows the agent nr.info block to be present after the agent script, which matches the behavior of 1216 and below.  This should allow for backwards compatibility for pre-existing custom configurations to continue to work without needing to be changed.
`instrumented.html` has been modified to include the nr.info block AFTER the agent code block.

Reconfigure config methods to allow backwards compat for nr.info placement

---

.eslintignore
.eslintrc
.eslintrc.json.nx
.husky/pre-commit
.husky/pre-push
package-lock.json
package.json
packages/browser-agent-core/.eslintrc.json
packages/browser-agent/.eslintrc.json
tools/jil/util/browsers-supported.json

Updating the husky dependency to the latest version. This newer version has changed how we manage the hooks but functionally works the same as the previous version we were using.
https://issues.newrelic.com/browse/NEWRELIC-5568
Install the dependencies using `npm i` and then run `git commit --allow-empty -m "Empty test commit"` to test the pre-commit hook. Run `git push` to test the pre-push hook.

Updating husky dependency

---

CHANGELOG.md
packages/browser-agent-core/src/features/spa/aggregate/index.js
packages/browser-agent-core/src/features/spa/aggregate/interaction.js

Primarily this changes how we treat the `initialPageLoad` interaction when the page `load` event happens. Currently, if that interaction still contains incomplete callbacks, the interaction's `finish` method will never be called. With the change, we no longer wait for any pending callbacks tied to the `initialPageLoad` interaction when the page `load` event happens.
https://issues.newrelic.com/browse/NEWRELIC-3891
To test locally, download the attached reproduction project.
1. Extract the project and open in your IDE
2. Create a new browser project in NR1-Staging
3. Use the copy/paste method and copy the generated script from NR1
4. In the reproduction project, open `config/newrelic.js` and paste in the copied script tag into the `innerHTML` field, making sure to remove the `<script>` and …

Fix initial page load harvest with Nuxt

---

tests/functional/xhr/xhr-dt-header.test.js
tools/jil/server/asset-server.js

Modifies usage of Buffer to address warning during JIL test runs: `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` See [info on porting](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/) in Node.js docs.
N/A
N/A

Change usage of Buffer to address test-run warning.

---

CHANGELOG.md
packages/browser-agent-core/src/features/jserrors/aggregate/index.js
tests/assets/js-error-column-bucketing.html
tests/functional/err/assertion-helpers.js
tests/functional/err/bucketing.test.js

This PR reverts the changes to the canonical stack hash in #303 and instead updates the bucket hash to account for the error name/type, message, and original stack trace.
https://issues.newrelic.com/browse/NR-40043
https://issues.newrelic.com/browse/NEWRELIC-3359
To test locally, download the attached reproduction project.
1. Extract the project and open in your IDE
2. Create a new browser project in NR1-Staging
3. Use the copy/paste method and copy the generated script from NR1
4. In the reproduction project, open `index.html`
5. Paste in the code from NR1 into the head
6. Run `python3 -m http.server`, a local web server should start at http://localhost:8000
7. Open the test page and wait for the errors to report
8. In NR1 for your test browser app, open the js errors screen
9. You …

Update jserror bucketing

---

CHANGELOG.md
cdn/agent-aggregator/aggregator.js
tests/assets/custom-attribute-race-condition.html
tests/assets/pre-existing-custom-attribute-race-condition-precedence.html
tests/assets/pre-existing-custom-attribute-race-condition.html
tests/functional/err/attributes.test.js

---
This PR Addresses a bug introduced in v1220, where a race condition between the loader and the info object could overwrite the jsAttributes object. See NEWRELIC-5682 for more info
https://issues.newrelic.com/browse/NEWRELIC-5682
https://issues.newrelic.com/browse/NEWRELIC-5717
3 Tests have been added to validate the case, and precedence conditions.

handle setInfo more gracefully to account for existing jsAttributes

---

.github/workflows/publish-apm.yml
tools/scripts/upload-to-nr.js

This PR updates the `publish-apm` flow to pull data from the CDN instead of building on the fly.  This is to ensure that changes in the trunk branch are not accidentally pulled in at execution time.  CDN assets need to be published to the CDN before running this script. The intended browser agent version needs to be included as an input to the workflow, ie "1221".

update upload NR script to grab from CDN instead of build folder

---

README.md

This change updates the open source software header required on newrelic OS projects.
Closes https://issues.newrelic.com/browse/NEWRELIC-5153 #298

Updating OSS readme header

---

CHANGELOG.md
packages/browser-agent-core/src/common/deny-list/deny-list.js
tests/assets/xhr-data-url.html
tests/functional/xhr/xhr-data-url.test.js

We've seen support tickets where the expected hostname doesn't exist on XHR request events. In our deny-list.js, we try to get the .length of the hostname, causing an exception and our agent to fail.
- Added a fix for errors on string comparison of undefined hostname.
- Created a functional test for the one known reproduction of the bug condition (data URLs).
- Add JSDoc blocks to deny-list.js.
[NR-63240](https://issues.newrelic.com/browse/NR-63240)
Functional test `xhr-data-url.test.js` relies on asset `xhr-data-url.html`.

Handle XHR events with undefined hostnames - NR-63240

---

.gitignore
cdn/package.json
cdn/webpack.config.js
tools/jil/server/asset-server.js

- Replaced parameter-driven splitting of entries with distinct composable config objects.
- Ended up with three composed objects (`standardConfig`, `polyfillConfig`, `webworkerConfig`) based on `commonConfig`.
- Explicitly specified `target` config property for each build (was a parameter before).
- Changed webpack target to `web` for modern browsers.
- For standard build, targeted modern browsers with babel-loader: last ten versions of Chrome, Firefox, Edge, and Safari.
- For polyfill build, targeted only IE 11 with babel-loader (not older versions of modern browsers also as story proposes).
- Differentiated filenames of chunk outputs for polyfill build to prevent overwriting dependency modules shared with other builds.
- Modified `asset-server.js` logic to split browserify babel targets …

Differentiate babel targets for polyfill and non-polyfill builds (NEWRELIC-5374)

---

.github/actions/test-setup/action.yml
.github/workflows/tests-polyfill.yml
.github/workflows/tests.yml

Re-do of #337 that was unwounded on trunk due to failure.
The previous reusable workflow is converted to a composite action instead.
[NR-72380](https://issues.newrelic.com/browse/NR-72380)
Since the new action does not yet exist in `main`, you can only test `workflow_dispatch` works. But you may have to add the proper `ref` to the initial checkout step for each job of the launched workflow:

Checkout & test future merge when adding "safe to test" - take #2

---

.github/workflows/publish-internal-prod.yml
tools/scripts/upload-ab-to-s3.js

This PR updates the action to add our builds to NR Internal Prod.  A manual workflow dispatch must be triggered (this can be tied to cutting a GH release later).  The output of this action uploads `2` scripts to `https://js-agent.newrelic.com/internal/prod.js` and `https://js-agent.newrelic.com/internal/eu-prod.js`.  These scripts have a 50/50 chance of loading `current` agent version or the `next` version code (which are inputs to the GH action), for the purpose of A/B testing. 
1. Upload build to CDN
2. Trigger a build in Grand Central + Jenkins
4. Use Grand Central to link and release the new build for each env (dev, staging, prod, eu-prod)
*New Notes* `dev` and `staging` are now auto-released on PR builds and merges to main respectively.
1. Evaluate `dev` and `staging` status.
2. Cut …

Update publish to internal prod envs script

---

tools/jil/server/asset-server.js
tools/jil/server/router.js
tools/jil/util/browsers-supported.json
tools/jil/util/external-services.js

Adding additional properties to the sauce connect launch script:
- tunnelName: tunnelIdentifier is deprecated in the sauce connect binary, this is just a rename
- logger: connecting the sauce connect launcher logger to console.log so we actually get output
- tunnelDomains: adding our internal test domain so only traffic for that domain is routed through the tunnel to the local server
- Without this, SL forwards all network traffic through the tunnel. Setting this to our domain only will cut down on the amount of traffic coming through the tunnel and may help with performance and stability in the tests.
None
Start sauce connect with `npm run sauce:connect -- -v` to see the log output. To test the change in general, run some of the JIL tests.

Adding props to sauce connect

---

CHANGELOG.md
cdn/webpack.config.js
tests/functional/err/event-listener.test.js
tests/functional/err/ignore-error.test.js
tests/functional/err/set-immediate.test.js
tests/functional/err/set-interval.test.js
tests/functional/err/set-timeout.test.js
tests/functional/err/uncaught.test.js
tests/functional/err/xhr.test.js
tools/jil/server/asset-server.js

Updating the webpack config so the `nrWrapper` method is not mangled. This was preventing the `jserrors` feature from properly excluding the `nrWrapper` and subsequent agent code from error stack traces.
Also including an update to the debug script the asset test server injects that was causing errors in IE11. IE does not support template strings.
https://issues.newrelic.com/browse/NEWRELIC-5929
Run the JIL test suite in GH. Optionally, should probably also run the polyfills tests.

Prevent webpack mangling nrWrapper method

---

.github/workflows/tests.yml
cdn/webpack.config.js
third_party_manifest.json
tools/jil/util/browsers-supported.json
tools/jil/util/sauce-browsers.js
tools/testing-server/src/asset-server.js

Our working support statement is `last 10 versions of Chrome, Safari, Firefox, and Edge on mobile and desktop`. This PR:
- Updates the babel targets in the webpack configuration and JIL asset server to include missing ChromeAndroid and iOS specs.
- Modifies `sauce-browsers.js` to generate `browsers-supported.json` using the same browserslist source that we use to calculate version targets for babel transpilation--ensuring version-range parity.
- Enables Android functional and unit tests. Previously these were disabled, but [specifying Android 9 ensures that Sauce defaults to JSON Wire Protocol](https://changelog.saucelabs.com/en/update-to-google-chrome-version-100-on-android-emulators), which works with our current JIL.
[NEWRELIC-5417](https://issues.newrelic.com/browse/NEWRELIC-5417) …

Update babel targets and tests to match support statement (NEWRELIC-5417)

---

CHANGELOG.md
packages/browser-agent-core/src/common/harvest/harvest-scheduler.js
packages/browser-agent-core/src/common/harvest/harvest.js
packages/browser-agent-core/src/common/util/feature-base.js
packages/browser-agent-core/src/features/ajax/aggregate/index.js
packages/browser-agent-core/src/features/jserrors/aggregate/index.js
packages/browser-agent-core/src/features/metrics/aggregate/index.js
packages/browser-agent-core/src/features/page-action/aggregate/index.js
packages/browser-agent-core/src/features/page-view-timing/aggregate/index.js
packages/browser-agent-core/src/features/session-trace/aggregate/index.js
tests/functional/disable-harvest.test.js

This PR adds functionality to kill running features if a 403 response is received from ingest.  Features should be blocked from aggregating data, as well as harvesting data.  Other feature functionality should remain in place, and events emitted to be used by other features should still occur.
https://issues.newrelic.com/browse/NR-70879
A new test has been added to check that features stop reporting after 403 is detected.

Kill features on 403

---

.github/workflows/smoke-test.yml
cdn/agent-loader/lite.js
cdn/agent-loader/pro.js
cdn/agent-loader/spa.js
cdn/agent-loader/utils/configure.js
packages/browser-agent-core/src/common/config/state/runtime.js
packages/browser-agent-core/src/features/metrics/instrument/index.js
tests/browser/protocol.browser.js
tests/functional/metrics.test.js

This PR adds supportability metrics (SM) that report what build type was loaded on the page (lite, pro, spa).  This behavior should happen only once, at metric feature inst runtime.
NEWRELIC-6163
Tests have been updated to account for the new metric

Add SMs for detecting build type

---

packages/browser-agent-core/src/common/unload/eol.js
packages/browser-agent-core/src/features/page-view-timing/aggregate/index.js
packages/browser-agent-core/src/features/page-view-timing/instrument/index.js
tests/browser/timings-lcp-cls.browser.js
tests/browser/timings-lcp.browser.js

Under the previous PR, our `pageHide` and `unload` had become synonymous in that doc vis change would cause both to be triggered and sent. This was not the intention, as there is a distinct difference between their triggers.
Specifically, `pageHide` can be emitted multiple times in the lifespan of one page load/restore, but `unload` should only signify the end of a load/restore's span and occur once per.
**`subscribeToEOL` also had its limiter removed under the flag to, e.g., allow multiple final harvests as either event can cause one and the total number of "final harvest" is indeterministic. (It's also necessary to decouple the two events.)
Patch to work done in #308 
When `init.allow_bfcache` is enabled, document vis change (tab, minimize, etc.) should emit `pageHide` still but _not_ …

[Patch] Distinguish reporting of windowUnload from pageHide to NR

---

CHANGELOG.md
packages/browser-agent-core/src/common/window/session-storage.js
tests/assets/api/session-storage-disallowed.html
tests/functional/api.test.js
tools/jil/util/browsers-supported.json

Wrapping our access of and write to sessionStorage in a `try..catch` to ensure it does not cause the agent to crash when sessionStorage is not available or when the quota has been exceeded or set to 0. Safari has been know to set the sessionStorage quota to 0 in private browsing windows. This was causing the agent to crash and the API to not be attached to the window.newrelic object.
https://issues.newrelic.com/browse/NR-78867
https://issues.newrelic.com/browse/NR-78872
A functional test has been added to ensure we no longer have this issue. To reproduce the error, comment out the `try..catch` wrapper added in this PR, rebuild, and load the new test page. After loading, check the window.newrelic object to see if the API methods were added.

NR-78867: Safe sessionStorage writes

---

.github/workflows/publish-apm.yml
.github/workflows/publish-release.yml
tools/jil/util/browsers-supported.json
tools/scripts/upload-to-nr.js

An update to `yargs` has disallowed the usage of `version` as an argument.  Changed to `v`

Fix APM DB script

---

CHANGELOG.md
src/common/config/state/runtime.js
src/common/wrap/wrap-history.js
src/features/spa/instrument/index.js
tests/browser/wrap-history.browser.js
tools/jil/util/browsers-supported.json

This PR introduces support for Chrome for iOS by removing feature gates that previously restricted three features: XHR, SPA and STN (session trace). It also addresses one of the chromium bugs that led to the the feature gates to begin with.
Apart from removing feature gating, the operative change is to wrap the methods of `history` directly rather than wrapping the methods of that object's prototype. This was necessary because Chrome on iOS itself modifies `history` directly, thus ignoring our changes to the prototype.
For more discussion of the bugs that led to feature gating, as well as the rationale for the change in how we wrap history methods, see the comments on related JIRA tickets.
- Remove CriOS feature gate from `xhrWrappable` in `common/config/state/runtime.js`.
- Remove …

Implement and verify support for Chrome on iOS (NEWRELIC-6276).

---

src/features/jserrors/instrument/index.js
tests/assets/unhandled-promise-rejection-readable.html
tests/functional/err/unhandled-rejection-readable.test.js

This PR attempts to preserve `unhandledPromiseRejection` messages as human-readable messages on the Error object that gets harvested. The previous strategy did not always work, because Promise.reject can pass any value, not just strings.
NEWRELIC-5921
A new test has been added that checks that unhandledPromiseRejections that pass various data types still produce human-readable Error messages.

Format unhandled promise rejection reasons as readable err messages

---

CHANGELOG.md
src/common/config/state/runtime.js

This PR adds the agent build version to the runtime object.  This has been requested by support eng team and external users. Along with `runtime.loaderType`, these properties will help identify the exact build running on the page.

Add build version to runtime obj

---

CHANGELOG.md
src/features/spa/aggregate/index.js

In some SPA applications, our code creates an interaction for the click of a link but that interaction is prematurely closed before the url change occurs. This results in missing data in NR1 since no interaction for the route change is reported.
The change stores the current interaction in memory as `state.prevInteraction` any time the code attempts to set a new node (null or otherwise). If a route change then happens, and there is no current interaction (`state.currentNode === null`), we will check for the previous interaction. If it meets requirements of not being set to be ignored and not created via the interactions API, it will be re-used and updated with the url change.
The restored interaction is re-processed and transmitted to NR1.
https://issues.newrelic.com/browse/NEWRELIC-3359 …

Adding logic for route changes outside a current interaction

---

.github/workflows/smoke-test.yml
.github/workflows/tests-polyfill.yml
src/features/utils/instrument-base.js
src/loaders/micro-agent.js

This PR cleans up warning messages about blocked scripts from CSP/ad blockers, and gets rid of false positives from cron tests
The warning no longer includes an error body + stack trace to diffuse tensions among customer that were artificially created by including that information in the message when it has nothing to do with the agent executing, and more to do with content-blocking on the page preventing lazy chunks from being imported.
Test workflows were modified to alleviate false positives that were occurring. Allowing a concrete pass-fail state is useful in these tests because they are directly linked to changelog badges, and are used to determine status for cutting a release.

Clean up warning messages and test inconsistencies

---

package-lock.json
src/common/util/global-scope.js
third_party_manifest.json
tools/testing-server/asset-server.js
webpack.config.js

This PR removes backticks from transpiled output. Some customers assign our snippet to a variable for insertion in a specific place in their app, and to avoid conflicts with single and double quotes, they enclose the script in backticks (\`). However, since we started transpiling for newer browser versions, we have template literals in our output, which conflict with backticks. We also recently added an error message containing backticks.
This change results in a very slight increase in loader size. The SPA loader, for example, is 168 bytes larger.
It also looks like the package-lock.json on main was stale. I updated it in this PR so tests could run.
[NR-86667](https://issues.newrelic.com/browse/NR-86667)
Standard automated tests apply.

Remove backticks from transpiled output (NR-86667)

---

CHANGELOG.md
src/features/session_trace/constants.js
src/features/session_trace/instrument/index.js
src/features/utils/instrument-base.js
src/features/utils/lazy-loader.js
src/loaders/api/api.js
src/loaders/micro-agent.js
webpack.config.js

This centralizes the lazy loading logic into a function that can be used by all agent types. This uses defined logic blocks and switch cases instead of template strings or string concatenation on purpose. Doing it this way ensures webpack does not need to "guess" what our chunks are and also allows us to easily name those chunks.
https://issues.newrelic.com/browse/NR-86614
All the tests cases should still pass.

NR-86614: Implementing centralized lazy loader

---

src/features/page_view_event/aggregate/index.js
src/features/page_view_event/aggregate/initialized-features.js

Following #391 , some flags required by downstream UI logic is put back into the agent to not break things.
These flags get turned into `entity.agentFeature` by ingest and then used for displays in NR1.
Pre-391 and current existing tests all ignore these flags, as it's not relevant to the browser agent.

Reverting "scrap old runtime.features from RUM query"

---

.eslintrc.js
CHANGELOG.md
src/features/jserrors/instrument/index.js
tests/assets/unhandled-promise-rejection-readable.html
tests/functional/err/unhandled-rejection-readable.test.js

This PR fixes an issue where niche browsers will throw an error when trying to set the message on the promise error.  We can avoid this by simply just returning the error if present without modifying it.
* https://newrelic-neworg.lightning.force.com/lightning/r/Case/5008W000011bs99QAA/view
* https://issues.newrelic.com/browse/NR-89675

Fix niche getter error in unhandledPromiseRejections - NR-89675

---

src/common/event-emitter/contextual-ee.js
src/common/wrap/wrap-fetch.js
src/common/wrap/wrap-promise.js
src/features/utils/instrument-base.js
src/loaders/agent.js
tests/assets/promise-instanceof.html
tests/browser/contextual-ee.browser.js
tests/browser/spa/fetch-body-propagation.browser.js
tests/browser/spa/fetch-rejections.browser.js
tests/browser/spa/single-fetch.browser.js
tests/functional/spa/basic.test.js
tools/jil/util/browsers-supported.json

Issue 409 pointed out that `instanceof` the promise returned from `async` functions failed against the global (NR wrapped) Promise.
This led to our re-evaluation of the recent Promise wrapping re-do, which attempted to leave the original Promise unmodified and instead create a prototype chain. While we are able to replace the `fetch` promise, it would seem `async()` promise constructors are not replace-able, so the end result is that we switch back to directly modifying the original promise.prototype.
This ensures that all 3 (new Promise, fetch, and async function) promises are `instanceof` our wrapped promise and gets instrumented, once again.
https://issues.newrelic.com/browse/NEWRELIC-6934
#409
Added an integration test to check the `instanceof` comparison.

NEWRELIC-6934: Re-wrap promise.prototype

---

CHANGELOG.md
jest.config.js
src/features/spa/aggregate/interaction-node.js
src/features/spa/aggregate/interaction-node.test.js
tools/jil/util/browsers-supported.json

Adding in some safety around the possibility that a SPA interaction node could `finish()` with a parent node that has been cancelled. This could cause an exception but the possibility of this happening is un-reproducible. This is a do-no-harm best-effort to ensure this error can never happen.
https://issues.newrelic.com/browse/NR-93365
https://issues.newrelic.com/browse/NR-91546
Added a jest test to reproduce and test the issue. I could not consistently reproduce the issue in integration tests.

NR-93365: Adding safety around interaction node cancelling

---

src/common/config/state/init.js
src/features/page_view_timing/instrument/index.js
tests/functional/pvt/timings.test.js

This PR puts the `Long Task` API behind a config flag under the `page_view_timing` setting.  It can be configured at `init.page_view_timing.long_task: bool` which defaults to `false`
https://issues.newrelic.com/browse/NR-95944
Long task tests needed the flag to be set to run correctly now, so that adjustment has been made to the existing tests.

Run LT behind a config flag - NR-95944

---

src/cdn/polyfills.js

As of [PR 428](https://github.com/newrelic/newrelic-browser-agent/pull/428), the `Set` object is used for `desiredFeatures`. IE 11 requires a polyfill for this object.
N/A
Standard automated tests should pass, especially polyfill tests.

Add polyfill for Set, now used for desiredFeatures.

---

tests/functional/worker/xhr-assorted.test.js

This PR addresses a race condition that was resulting in a brittle test. This was a problem with the test, not with agent code.
The `harvestRetried` test in `tests/functional/worker/xhr-assorted.test.js` would fail on `second body should include the contents of the first retried harvest` about 30% of the time. This was due to a too-short harvest interval of 2 seconds, which for module workers in particular, was causing the first AJAX harvest to capture the recently added RUM call but not the call to `/json` the test was looking for. (Previously the harvest cycle would run multiple times before picking up the call to `/json`, but after adding the RUM call for workers in PR 428, the RUM call satisfies the first harvest cycle part of the time). Increasing the interval to 5 seconds allows …

Increase harvest timeout due to race condition.

---

tools/jil/util/browsers-supported.json
tools/scripts/diff-sizes.mjs

This adds two other assets sections to the PR report that list out the released and built sizes for non-loader assets. This should make it easier for us to maintain the performance docs until we automate those doc changes.
https://issues.newrelic.com/browse/NEWRELIC-6739
Let the CI run and check the report comment on this PR.

NEWRELIC-6739: Adding other asset sizes to report

---

src/common/util/submit-data.js

Illegal Invocation errors still pop up from time to time on sendBeacon calls, even after work to bind scope to the beacon caller. There is nothing more we can do to get around this, besides failing gracefully and falling back to another call type.  This PR addresses that workflow.
Nr-95365

Handle sendBeacon more gracefully - NR-95365

---

.husky/pre-commit
src/common/config/state/runtime.js
src/common/harvest/harvest.js
src/features/metrics/aggregate/index.js
src/features/page_view_event/aggregate/index.js
tools/jil/util/browsers-supported.json

Aspect 1: The intent is to capture the length end-to-end of session traces, to be able to evaluate what the "average" session trace duration is today per "page session".
Aspect 2: This PR begins tallying bytesSent for each endpoint, which will give us raw figures per endpoint per "page session"
SMs added:
* `PageSession/Endpoint/1/BytesSent`
* `PageSession/Endpoint/Resources/BytesSent`
* `PageSession/Endpoint/Events/BytesSent`
* `PageSession/Endpoint/Jserrors/BytesSent`
* `PageSession/Feature/SessionTrace/DurationMs`

SMs - SessionTrace duration and endpoint payload sizes per page

---

.husky/pre-commit
package-lock.json
src/common/wrap/index.js
src/common/wrap/wrap-console.js
src/common/wrap/wrap-function.js
src/features/metrics/instrument/index.js
src/features/page_view_event/instrument/index.js
tests/assets/console-methods.html
tests/functional/metrics.test.js
tools/jil/util/browsers-supported.json
tools/testing-server/plugins/browserify/browserify-transform.js

This PR adds supportability metrics for assorted console methods to inform future decisions around capturing logs.
- Wraps methods `debug`, `error`, `info`, `log`, `trace`,  and `warn` on `console` in the global scope.
- Captures **count** and **size** metrics as part of metrics feature instrumentation.
- New tests assess accurate number and size of each method.
Also adds a pre-commit hook in the husky config to update the caniuse-lite database, which is what browserslist targets are based on. After updating the DB we lost `ios_saf 14.5-14.8` as targets, which introduced the need to add browserify plugin support for `class-properties` and `private-methods`.
- [NEWRELIC-7770](https://issues.newrelic.com/browse/NEWRELIC-7770)
- [Angler PR …

Capture supportability metrics for console methods (NEWRELIC-7770)

---

package-lock.json
tools/jil/util/browsers-all.json
tools/jil/util/browsers-supported.json
tools/scripts/docs-website/create-docs-pr.js

Adds a statement like this to the end of the support statement when raising the release notes PR:
`Consistent with our [browser support policy](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/#browser-types), version 1.230.0 of the Browser agent was built for and tested against these browsers and version ranges: Chrome 103-112, Edge 102-111, Safari 15-16, Firefox 102-111; and for mobile devices, Android Chrome 100 and iOS Safari 15-15.5.`
The browser versions are derived from the `browsers-supported.json` file.
[NEWRELIC-7258](https://issues.newrelic.com/browse/NEWRELIC-7258)
Dry run should produce the correct verbiage by pulling from the file `browsers-supported.json` file.

Append list of browsers to support statement (NEWRELIC-7258)

---

src/loaders/api/api.js

I am not sure about what exactly needs to be returned here but this fixes the error thrown when calling `NREUM.noticeError`.

Fix RerenceError: returnsVals is not defined

---

src/features/page_view_timing/aggregate/index.js

Adding in logic checks for object passed to the CWV callbacks to prevent accessing properties of undefined.
https://issues.newrelic.com/browse/NEWRELIC-8039
Integration tests should pass.

fix: cwv add error prevention logic

---

.eslintrc.js
src/common/util/obfuscate.js
src/features/ajax/aggregate/index.js
src/features/jserrors/aggregate/index.js
src/features/metrics/aggregate/index.js
src/features/page_action/aggregate/index.js
src/features/page_view_event/aggregate/index.js
src/features/page_view_timing/aggregate/index.js
src/features/session_trace/aggregate/index.js
src/features/spa/aggregate/index.js
src/features/utils/aggregate-base.js
src/features/utils/feature-base.js
src/features/utils/lazy-loader.js

Enabling the `no-useless-constructor` lint rule and resolving lint errors. The `AggregateBase` class was empty and so was removed. It can be added back later if and when it becomes needed for centralizing some logic across all the aggregators.
https://issues.newrelic.com/browse/NR-87754

chore: enable no-useless-constructor lint rule

---

.eslintrc.js
tests/assets/worker/js/classic-worker.js
tests/assets/worker/js/module-worker.js
tests/assets/worker/js/shared-worker.js
tools/test-builds/browser-agent-wrapper/src/worker-wrapper.js
tools/test-builds/raw-src-wrapper/src/worker-wrapper.js

Enabling the `no-eval` lint rule and placing ignore statements in the test files were we purposefully use eval in the course of integration testing.
https://issues.newrelic.com/browse/NR-87778

chore: enable no-eval lint rule

---

src/common/util/data-size.js
src/common/util/data-size.test.js

Adds jest tests for the dataSize function. Also adds some comments.
Note, there are no existing "browser" tests to replace.
[NEWRELIC-7841](https://issues.newrelic.com/browse/NEWRELIC-7841)
`npm test src/common/util/data-size.test.js`

Add jest test for data-size (NEWRELIC-7841)

---

.eslintrc.js
tools/scripts/upload-polyfills-to-nr.js

Enabling the `n/no-deprecated-api` lint rule and replacing the `util._extend` call with the `deepmerge-ts` library.
https://issues.newrelic.com/browse/NR-87765

chore: Enable n/no-deprecated-api lint rule

---

tools/scripts/docs-website/create-docs-pr.mjs

Make follow-up adjustments to the recent release automation changes.
---
:warning: This PR is a draft for now to give time for additional changes.
- Strip the conventional commit prefix and Jira issue suffix from a title.
- https://github.com/newrelic/newrelic-browser-agent/pull/491
N/A

chore: Adjust release automation changes

---

src/common/config/state/configurable.js
src/common/session/session-entity.js
src/common/timer/interaction-timer.js
src/common/timer/timer.js
src/common/timer/timer.test.js
tests/browser/config.browser.js

Internal metrics are collected for session duration and termination statistics
---
This PR adds internal SMs for Session duration (ms), expiration count, and inactivity count.  As part of this work, some inconsistencies were cleaned up in the session entity class.
NEWRELIC-8334
Existing tests should continue passing.

chore: Session entity supportability metrics - NEWRELIC-8334

---

tools/browsers-lists/browsers-all.json
tools/testing-server/index.js
tools/testing-server/logger.js
tools/testing-server/plugins/request-logger/index.js
tools/testing-server/routes/bam-apis.js
tools/wdio/args.mjs
tools/wdio/config/base.conf.mjs
tools/wdio/plugins/testing-server/launcher.mjs

Adding back support for the debug shim in the test server and improving test server logging.
---
Adding a new testing server logger class that will log out network requests and debug messages from test assets separate from the fastify built-in logger. The fastify logger is not very human readable and very verbose. When running the server or tests with the `-L` cli flag, network requests will be logged in the pattern of `{serverId} -> {requestMethod} {requestUrl}`. For debug messages from the test assets, pass the `-d` cli flag and debug messages will be logged in the pattern of `DEBUG [{licenseKey}]({messageIndex}): {debugMethod} {debugMethodParameters}`.
Examples:
`DEBUG [3984b89d-1fce-464f-a8b2-d27e7b785ae3](1): console.log: {"0":"THIS IS FOOBAR"}`
`commandServer -> POST …

chore: testing server logging

---

package-lock.json
tests/assets/ignored-error.html
tests/assets/worker/js/module-worker.js
tests/functional/disable-harvest.test.js
tests/functional/final-harvest.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json
tools/browsers-lists/extended-debugging.mjs
tools/jil/driver/TestRun.js
tools/jil/runner/args.js
tools/jil/runner/index.js
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json
tools/testing-server/routes/mock-apis.js
tools/testing-server/test-handle.js
tools/testing-server/utils/expect-tests.js
tools/wdio/args.mjs
tools/wdio/config/sauce.conf.mjs

Adding support for SauceLabs extended debugging feature.
---
This PR adds support for SauceLabs [extended debugging](https://docs.saucelabs.com/insights/debug/) feature. It also adds an extra log entry when running tests using JIL to show which test is related to which testId (license key). This will make it easier to track down tests that are failing due to BAM expect timeouts. The expects have also been updated to provide each function a proper name so the log entry for a timeout will show which BAM endpoint timed out.
N/A

chore: add support for saucelabs extended debugging

---

src/features/ajax/instrument/index.js
tests/assets/cat-same-origin.html
tests/functional/xhr/cat-cors.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json
tools/testing-server/constants.js

The agent will now set the `X-NewRelic-ID` header on XHR requests only when a truthy `xpid` value is explicitly set in the loader configuration. Previously the header was added even if undefined.
---
As described in the bug linked below, the `X-NewRelic-ID` header was getting set even when the xpid configuration value had not been set. This is likely an artifact of an earlier agent architecture in which there was no default model for the configuration, which meant `xpid` was not set except manually. Now with a model, `xpid` always exists with at least a default value of `undefined`.
- https://github.com/newrelic/newrelic-browser-agent/issues/526
- [NEWRELIC-8521](https://issues.newrelic.com/browse/NEWRELIC-8521)
- Automated tests should pass.
- The linked bug provides manual replication …

fix: Add X-NewRelic-ID header only if defined - NEWRELIC-8521

---

package-lock.json
src/features/utils/feature-base.js
tests/functional/session/config-race-condition.test.js
tools/browsers-lists/browsers-supported.json

Fix an issue where the internal runtime state of the agent was not preserved when the agent configurations were supplied after the loader had finished initializing, which caused the session to be cleared.
---
This PR ensures that the runtime object is passed through the configuration step for late-configuration cases. Although this was initially surfaced by a voided session manager instance, the runtime object holds lots of state which was likely also affected.  This will ensure that state gets preserved if we have to pass the configurations later than the runtime setters.
NEWRELIC-8733
A new JIL functional test has been added to check the state of the session query param after a late load.  This was confirmed to fail on main, and pass on this new branch.

fix: Ensure runtime is preserved for late-configuration cases

---

.github/workflows/validate-pr.yml
tools/scripts/docs-website/create-docs-pr.mjs

Makes two small non-agent changes related to release notes.
---
- No longer counts Jira issue when validating PR title length.
- Matches browser version support statement to what the docs team changes it to when the docs PR is raised.

chore: Small fixes to release notes logic

---

tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/browser-tests/package-lock.json
tools/test-builds/browser-tests/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json
tools/wdio/args.mjs
tools/wdio/bin/server.js
tools/wdio/plugins/testing-server/index.mjs
tools/wdio/plugins/testing-server/launcher.mjs

Threading the testing server for wdio.
---
This removes the testing server from the wdio main process and will start multiple instances of the testing server based on the `--concurrent` flag.
N/A
Run wdio test workflow.

chore: threading testing server for wdio

---

src/common/harvest/harvest-scheduler.js
src/common/harvest/harvest-scheduler.test.js

A early return condition in the harvest rescheduling logic in version 1.233.0 was preventing Ajax event harvest from being rescheduled in cases where no data had accumulated.
---
This PR addresses a problem where, once the harvest scheduler runs for the Ajax feature and the Ajax feature has no accumulated data, the Ajax feature no longer performs future harvests. The issue appears to be [line 92](https://github.com/newrelic/newrelic-browser-agent/blob/main/src/common/harvest/harvest-scheduler.js#L92) in the harvest scheduler where it early-returns when there is no data to send, but does not schedule the next harvest.
[NEWRELIC-8876](https://issues.newrelic.com/browse/NEWRELIC-8876)
- All tests should run.
- `npm test src/common/harvest/harvest-scheduler.test.js`
- Manual verification of …

fix: Address early return preempting XHR harvest re-schedule

---

jest.config.js
package-lock.json

Excluding the cdn loaders from jest code coverage reports.
---
Excluding the cdn loaders from the jest unit test coverage report. These files are only used as entrypoints for the cdn webpack builds and don't really need testing.
N/A

chore: exclude cdn loaders from code coverage

---

package-lock.json
src/common/util/stringify.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

Includes jest unit tests for the `common/util/stringify` module.
---
[NEWRELIC-7854](https://issues.newrelic.com/browse/NEWRELIC-7854)
`npm test src/common/util/stringify.test.js`

chore: Add jest tests for common/util/stringify (NEWRELIC-7854)

---

package-lock.json
src/common/util/submit-data.js
src/common/util/submit-data.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

Includes jest tests for the `common/util/submit-data` module and adds some JSDoc comments.
---
[NEWRELIC-7855](https://issues.newrelic.com/browse/NEWRELIC-7855)
`npm test src/common/util/submit-data.test.js`

chore: Add jest tests for common/util/submit-data (NEWRELIC-7855)

---

package-lock.json
src/common/util/get-or-set.js
src/common/util/get-or-set.test.js
tools/browsers-lists/browsers-all.json
tools/browsers-lists/browsers-supported.json

Includes jest unit tests for the `common/util/get-or-set` module, and a new JSDoc block.
---
[NEWRELIC-7848](https://issues.newrelic.com/browse/NEWRELIC-7848)
`npm test src/common/util/get-or-set.test.js`

chore: Add jest tests for common/util/get-or-set (NEWRELIC-7848)

---

package-lock.json
src/features/session_trace/aggregate/index.js
tests/functional/stn/index.test.js
tests/functional/xhr/ajax-events.test.js
tools/browsers-lists/browsers-supported.json

Removing customer and apm defined data from the session trace requests since the data is not consumed downstream and can result in 414 errors for network requests where the custom data could cause the URL to exceed the max length of 8192 bytes.
---
Removed the `ja`, `ua`, and `at` query parameters from the session trace network requests. These parameters, especially `ja`, could grow so large that it would cause the resulting URL to exceed the 8192 bytes limit. This data was never actually consumed downstream and doesn't need to be sent on any session trace request.
https://issues.newrelic.com/browse/NEWRELIC-7997
The integration tests have been updated to remove reliance on these properties. To test locally, build the agent and inject it into a test project. Verify in NR that session …

feat: remove unused data from stn requests

---

.github/workflows/publish-apm.yml
.github/workflows/publish-release.yml
.github/workflows/publish-sudo-polyfills.yml
package-lock.json
tools/browsers-lists/browsers-supported.json
tools/scripts/check-nrdb.js
tools/scripts/upload-polyfills-to-nr.js
tools/scripts/upload-to-nr.js

Remove EU DB CI actions, as that table will no longer need populating as it switches to a replication view of the prod table.
---
This PR alters the CI actions that publish the loader code to the DB specifically for the `eu` target only.
NEWRELIC-9416

chore: Remove eu db actions

---

package-lock.json
src/common/harvest/harvest.js
src/common/harvest/harvest.test.js
tests/assets/api/addPageAction-unload.html
tests/specs/ins/harvesting.e2e.js
tools/browsers-lists/browsers-supported.json
tools/saucelabs/utils.mjs

An issue from 1.234.0 has been addressed in which an illegal invocation error could occur during a final harvest as a result of calling `addPageAction` and passing `window.location` as an argument before a navigation.
---
Reverting a change from #521. Calling `addPageAction` and passing `window.location` as an argument before a navigation would result in calling `.toString` on the global `window.location`. Doing so during a page unload causes an `Illegal Invocation` error due to the global `window.location.toString()` losing it's context.
https://issues.newrelic.com/browse/NEWRELIC-9370
Test added to ensure this issue does not happen again.

fix: Fix illegal invocation error on final harvest

---

package-lock.json
tests/assets/duplicate-errors.html
tools/browsers-lists/browsers-supported.json

The asset had string literals in it.
---
Apparently we weren't running tests with `duplicate-errors.html` against IE before.
N/A
`npm run wdio -- --retry=false tests/specs/err/error-payload.e2e.js -P -b ie@11`

chore: Fix err/error-payload.e2e.js for IE 11

---

tools/browsers-lists/browsers-supported.json
tools/wdio/plugins/custom-commands.mjs

The default session.state.custom value (an empty object) was being converted to null when passed from IE in browser.execute return values.
---
Preserves empty objects in session state passed from IE via browser.execute using JSON.stringify.
N/A
`npm run wdio -- --retry=false tests/specs/session-manager.e2e.js -P -b ie@11`

chore: Fix IE problems in tests/specs/session-manager.e2e.js 

---

package-lock.json
tests/specs/err/attributes.e2e.js
tools/browsers-lists/browsers-supported.json

Intermittently WDIO was failing in IE to capture the ID of the selector used to trigger clicks.
---
The error was `Error: Malformed type for "elementId" parameter of command elementClick` and it affected a number of the tests intermittently. The new logic mostly uses browser.execute to interact directly with the scripts and elements.
Some of the tests didn't actually need to use a click event because they weren't testing a SPA click interaction.
N/A
`npm run wdio -- --retry=false tests/specs/err/attributes.e2e.js -P -b ie@11`

chore: Fix inconsistent IE issues with err/attributes.e2e.js

---

tests/specs/npm/micro-agent.e2e.js

This excludes IE from smoke tests for MicroAgent as discussed.
---
Should skip: `npm run wdio -- --retry=false tests/specs/npm/micro-agent.e2e.js -P -b ie@11`

chore: Don't test MicroAgent in IE

---

package-lock.json
tests/assets/third-party-compatibility/mootools/1.6.0-nocompat.html
tests/specs/third-party-compatibility/mootools.e2e.js

Update Mootools test to just check for success flag after running a Mootools method
---
This PR updates the Mootools test to just check for success status in an attempt to fix flakiness issues with WDIO.
`npm run wdio -- --no-retry tests/specs/third-party-compatibility/mootools.e2e.js`

chore: Change Mootools test to not rely on payloads

---

package-lock.json
tests/assets/third-party-compatibility/requirejs/2.3.6.html
tests/specs/third-party-compatibility/run-test.js

The unload checks were looking specifically for timing values but the BAM expect was for generic events, so sometimes it would pick up an XHR call instead of the timings call.
---
Changed `expectEvents` to `expectTimings`.
N/A
- `npm run wdio -- --retry=false tests/specs/third-party-compatibility/requirejs.e2e.js`
- `npm run wdio -- --retry=false tests/specs/third-party-compatibility/requirejs.e2e.js -b ios@15.2`

chore: Fix inconsistency in 3rd-party-compat WDIO tests

---

package-lock.json
src/common/constants/runtime.js
src/common/harvest/harvest.js

This is a same-version patch to #576 
---
#576 made the final harvest on page unload unreliable for IE11. This reintroduces reliability to that browser, while keeping usage of img out, 414 too-long-url at bay, and existing behavior for other browsers.
NR-139090
Existing tests are sufficient -- this fixes failing IE functional on pvt/timings.
Verify that for IE, final analytics are sent when page is dismissed like for the other browser versions.

chore: Recapture IE final harvest (dev bug) NR-139090

---

src/features/session_replay/replay-mode.js
src/features/utils/instrument-base.js
src/features/utils/instrument-base.test.js

Starting in 1.235.0, loading the agent in browsers with strict privacy settings resulted in an uncaught error in a promise. This error has been handled, and chunk load failures again result only in a warning.
---
Eliminate promise rejection.
NR-129244 // #599 
Verify that when one of the feature's aggregate import is blocked & fails, no uncaught promise is thrown.

fix: Handle chunk load promise error introduced in 1.235.0 - NR-129244

---

.github/workflows/publish-dev.yml
package-lock.json
tools/scripts/upload-ab-to-s3.js

Fix the experimental build and ship CI, which was causing errors in Staging NR1 when trying include .txt files as loaders.
---
This PR updates the a-b publish script to only include files that end with `.js` as a loader.  It was previously finding `.txt` files occasionally and including them as loaders, after running the experiment build.  This caused `newrelic does not exist` errors in staging, as the txt file does not work as a loader.
https://newrelic.slack.com/archives/C0193KAHHAS/p1687958325562219
Validate that running `Build and Publish Experiment` action on this branch does not include `.txt` loader(s) in the output.

chore: Fix experimental build in staging

---

package-lock.json
src/common/wrap/wrap-jsonp.js
src/features/page_view_event/aggregate/initialized-features.js

Patch a couple of areas that can yield reading property of undefined or null errors in the RUM call and jsonp wrapper.
---
See summary
NR-122092
NR-138554
All regression

fix: Fix potential property of undefined errors

---

src/features/jserrors/constants.js
src/features/jserrors/instrument/index.js
tests/functional/err/unhandled-rejection-readable.test.js
tests/functional/spa/errors.test.js

Removing the instantiation of the Error class in the jserrors feature for instances where a non-Error value is thrown from customer's code. In such cases, an Error instance would be created and the stack trace would point back to the agent code as the source. This causes confusion since it makes it seem like the agent code is throwing the error when that is not the case. Instead, the internal UncaughtError class will be used and no stack trace will exist.
---
Addressing PR comments from https://github.com/newrelic/newrelic-browser-agent/pull/614.
https://issues.newrelic.com/browse/NR-138375

fix: prevent invalid error stack traces

---

package-lock.json
src/features/session_replay/aggregate/index.js

To aid with UI searching, Session Replay will need to periodically checkout snapshots, which for now has been decided to be every 5 minutes.
---
This PR updates the Session Replay feature to checkout a snapshot every 5 minutes in "full" mode.
https://issues.newrelic.com/browse/NR-142816
All existing tests should continue to pass.  If desired, to reproduce locally, run in experimental mode and ensure that a snapshot (type 2) is generated at least every x minutes

chore: Session Replay - checkout every 5 minutes in full mode

---

package-lock.json
src/common/harvest/harvest.js
src/common/harvest/harvest.test.js
tools/browsers-lists/browsers-supported.json

Add warning for large payloads, which is typically caused by excessive custom attribute sizes.
---
This PR adds a check to the harvest cycle to check the body size.  If the body is large (>750kb), it will log a warning to the console noting that customers should check their custom attributes.
[NR-137463](https://issues.newrelic.com/browse/NR-137463)
A new jest test representing this case has been added to `harvest.test.js`

feat: Add warning for large payloads

---

package-lock.json
src/loaders/configure/configure.js
tests/assets/spa/multiple-custom-interactions.html
tests/specs/spa/harvesting.e2e.js
tools/browsers-lists/browsers-supported.json
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/browser-tests/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json

In cases where the customer's configuration does not include the `init.ajax.deny_list` property, the agent would not properly account for the `init.ajax.block_internal` setting and would not block ajax events for internal agent network calls.
---
In cases where the customer's configuration does not include the `init.ajax.deny_list` property, the agent would not properly account for the `init.ajax.block_internal` setting and would not block ajax events for internal agent network calls.
This may be an edge case for most of customers since most have at least the BAM endpoint in their deny list. For customers with an empty deny list in their browser entity settings, this fix will now apply the `block_internal` setting properly.
These are just related tickets. This issue was found while …

fix: Undefined deny list ignores block internal

---

src/features/spa/aggregate/index.js
tests/assets/spa/ajax-deny-list.html
tests/assets/spa/fetch-chunked.html
tests/assets/spa/fetch-simple.html
tests/specs/xhr/deny-list.e2e.js
tools/wdio/plugins/browser-matcher.mjs

The SPA feature will now properly respect the ajax deny list and block internal settings for fetch calls. In prior versions, the SPA feature only consulted the ajax deny list for XMLHttpRequest calls.
---
The SPA feature will now properly respect the ajax deny list and block internal settings for fetch calls. In prior versions, the SPA feature only consulted the ajax deny list for XMLHttpRequest calls.
https://issues.newrelic.com/browse/NR-146248
Build the agent and run the local server. The below links can be used to test the functionality.
[Block Internal Disabled](http://bam-test-1.nr-local.net:3333/tests/assets/spa/ajax-deny-list.html?loader=spa&config=eyJsaWNlbnNlS2V5IjoiMjM2YWZhNzQtZDM2NS00MWFmLWE0YjctMzUyMDY1M2YwYmQ2In0%3D&init=eyJhamF4Ijp7ImJsb2NrX2ludGVybmFsIjpmYWxzZSwiZGVueV9saXN …

fix: SPA feature respects ajax deny_list for fetch

---

package-lock.json
src/loaders/agent-base.js
src/loaders/api/api.component-test.js
src/loaders/api/api.js
tests/functional/uncat-internal-help.cjs
tools/browsers-lists/browsers-supported.json

Add api method to top-level interface to allow the setting of application version across all outgoing payloads
---
This PR adds a method to add a standardized application version property to all outgoing payloads.
https://issues.newrelic.com/browse/NR-150937
A new jest test has been added to validate this behavior.  Other browser tests checking existing API method behaviors should continue passing.

feat: Add API: setApplicationVersion

---

src/features/session_replay/aggregate/index.js
tools/webpack/configs/common.mjs
tools/webpack/configs/polyfills.mjs
tools/webpack/configs/standard.mjs
tools/webpack/configs/workers.mjs
tools/webpack/index.mjs
tools/webpack/plugins/nrba-chunking/index.mjs

Reducing the number JavaScript files the agent loads asynchronously down to a single file. This means customer's users will now only need to load one additional JavaScript file for the New Relic Browser Agent to operate. This additional JavaScript file will continue to only be loaded upon the document "load" event. This change not only reduces the number of additional requests the agent must make but also reduces the amount of code that must be loaded by eliminating duplication.
---
Header pretty much says it all. Below are the code size statistics and the CDN cost statistics are attached in the JIRA.
|Loader|# of Assets|Raw Size|GZip Size|
|---|---|---|---|
|lite|8|106 KB|29 KB|
|pro|12|172 KB|46 KB|
|spa|13|205 KB|53 KB|
|experimental|15|381 KB|110 KB|
|Loader|# of Assets|Raw Size|GZip …

feat: Reducing the agent chunk count

---

.github/actions/build-ab/index.js
.github/actions/build-ab/package.json
.github/actions/fastly-verify/index.js
.github/actions/fastly-verify/package.json
.github/actions/nr-upload/index.js
.github/actions/nr-upload/package.json
.github/actions/nr-verify/index.js
.github/actions/nr-verify/package.json
.github/actions/shared-utils/.npmrc
.github/actions/shared-utils/index.js
.github/actions/shared-utils/package.json
.github/actions/size-diff/get-stats.js
.github/actions/size-diff/package.json

---
This fixes a node import error in A/B script build action complaining of missing dependency. The shared utils are now treated as another npm dependency to prevent issue with resolving dependencies.
See https://github.com/newrelic/newrelic-browser-agent/actions/runs/6001121748/job/16275270977 for the current issue.

chore: fix workflow actions

---

.github/actions/build-ab/index.js
package-lock.json
tools/browsers-lists/browsers-supported.json

---
Removing the `current` loader from prod and eu-prod a/b scripts. We will only run the newly released loader in those environments.
N/A

chore: single loader in prod

---

package-lock.json
package.json
tools/browsers-lists/browsers-supported.json
tools/test-builds/vite-react-wrapper/package.json
tools/test-builds/vite-react-wrapper/tsconfig.types-resolver.json
tools/test-builds/vite-react-wrapper/types-resolver/browser-agent.ts
tools/test-builds/vite-react-wrapper/types-resolver/custom-agent.ts
tools/test-builds/vite-react-wrapper/types-resolver/micro-agent.ts
tools/test-builds/vite-react-wrapper/types-resolver/worker-agent.ts

Fixing issues with typescript throwing errors when trying to resolve the typings for individual features with `"moduleResolution": "node"` set in the `tsconfig.json`. `"moduleResolution": "nodenext"` and `"moduleResolution": "node16"` will enable typescript use of the `exports` field of our `package.json` but could also break other libraries and forces developers to change all local imports to include file extensions.
---
Our `package.json` contains `exports` for types but typescript only uses the `exports` field when `"moduleResolution": "nodenext"` is set in the `tsconfig.json`. This setting has other ramifications that may make it impossible for customers to use. To resolve the issue for customers that cannot use `"moduleResolution": "nodenext"`, the `typesVersions` settings have been …

fix: Issues with types resolution

---

.github/workflows/publish-dev.yml

The Publish-Dev CI is failing to publish things to the dev env when wdio coverage fails to run.  This ignores that job's status
---

chore: CI -- do not require wdio coverage success to publish

---

.github/actions/build-ab/index.js
.github/actions/build-ab/template.js
package-lock.json

Adding application version validation directly to main build of CI (staging only).  This will eliminate the need for a separate "experiment" loader just for that purpose.
---

chore: CI - Application version validation

---

.github/actions/build-ab/action.yml
.github/actions/build-ab/args.js
.github/actions/build-ab/index.js
.github/actions/build-ab/template.js
.github/workflows/publish-dev.yml
.github/workflows/publish-experiment.yml
package-lock.json

---
Non-next A/B loaders will now direct their data to a separate browser entity found in the browser NR account.
[staging](https://staging.onenr.io/0z7wky0anjL)
[dev](https://staging.onenr.io/0a7j94lKlRO)
https://issues.newrelic.com/browse/NR-152262
New A/B scripts have been manually generated and uploaded for dev and staging.

chore: Redirect non-next ab loader data

---

third_party_manifest.json
tools/test-builds/browser-agent-wrapper/package.json
tools/test-builds/browser-tests/package.json
tools/test-builds/raw-src-wrapper/package.json
tools/test-builds/vite-react-wrapper/package.json

When this PR is merged, caniuse-lite database is updated, latest browserslist for SauceLabs is retrieved, and third-party dependencies docs are updates.
---
This PR was generated with post-release-updates GitHub action.

chore: Post release repo updates

---

.github/workflows/wdio-single-browser.yml

---
Even if wdio testing failes, when coverage is enabled, coverage will always be uploaded.
https://issues.newrelic.com/browse/NR-157916

chore: always upload code coverage

---

tools/webpack/configs/common.mjs

Removing the hash from the chunk asset file name. This will allow internal and external automation to predict the file name of each asset chunk as long as the loader type and version number is known.
---
Removing the hash from the chunk asset file name. This will allow internal and external automation to predict the file name of each asset chunk as long as the loader type and version number is known.
https://issues.newrelic.com/browse/NR-160947

feat: Removing hash from chunk asset name

---

.eslintrc.js
.github/actions/build-ab/template.js
src/common/config/state/init.js
src/features/session_replay/aggregate/index.component-test.js
src/features/session_replay/aggregate/index.js
tests/assets/rrweb-record.html
tests/specs/session-replay/helpers.js
tests/specs/session-replay/mode.e2e.js
tests/specs/session-replay/rrweb-configuration.e2e.js
tests/specs/session-replay/session-state.e2e.js
tests/specs/stn/with-replay-error-mode.e2e.js
tests/specs/stn/with-session-replay.e2e.js
tools/testing-server/constants.js

Update the init settings for Session Replay to match changes in the API/DB.
---
This PR updates the init settings for SR to match the output object generated by API.  The settings previously implemented in the agent were a "best guess" until the API actually finished their work to output a config blob for session replay settings.
All existing SR and STN tests should be updated to use the new settings names and continue to pass.

chore: update settings to match API-E

---

src/common/harvest/harvest-scheduler.js
src/common/harvest/harvest-scheduler.test.js
src/features/metrics/aggregate/index.js
src/features/page_view_timing/aggregate/index.js
tests/specs/harvesting/final-harvesting.e2e.js

Fixes the final harvest behavior in cases when the RUM request fails. The initial request is meant to act as a gateway for the agent to start reporting data, and its failure should result in the agent not sending anything. As of previous version, the metrics and page view timing features do not follow this rule, and that has been corrected.
---
This cuts down on disassociated data from user page "sessions" wherein their agent never sent any RUM or interval analytics yet does sent disjoint metrics and timings that cannot be tied to anything else of said page session.
NR-138551
Tests added but can also manually verify that following a failed RUM request, nothing else gets send either on interval or on refresh (sendBeacon).

fix: Final harvest does not happen when initial RUM call fails

---

.github/workflows/nightly.yml

The workers test job does not currently run because it doesnt support the syntax of the command being passed in.  This change just finds the worker test files and passes them in as args to the command.
---

chore: Fix workers test job

---

src/features/session_replay/aggregate/index.js
tests/specs/session-replay/helpers.js
tests/specs/session-replay/payload.e2e.js
tests/specs/session-replay/session-pages.e2e.js

handle meta nodes more gracefully
---
A new discovery found that the replayer actually needs BOTH the meta node, and subsequent snapshot node in order to render properly.  This is an effort to keep those events together.
Existing tests should continue to pass.  A new test will be added to check for meta flag

chore: SR - handle meta nodes more gracefully

---

.github/actions/build-ab/action.yml
.github/actions/build-ab/args.js
.github/actions/build-ab/index.js
.github/actions/build-ab/templates/experiments.js
.github/actions/build-ab/templates/latest.js
.github/actions/build-ab/templates/postamble.js
.github/actions/build-ab/templates/released.js
.github/actions/comment-pull-request/action.yml
.github/actions/docs-pr/action.yml
.github/actions/fastly-purge/action.yml
.github/actions/fastly-verify/action.yml
.github/actions/find-pull-request/action.yml
.github/actions/internal-ab/action.yml
.github/actions/nr-upload-dev/action.yml
.github/actions/nr-upload-dev/args.js
.github/actions/nr-upload-dev/index.js
.github/actions/nr-upload/action.yml
.github/actions/nr-verify/action.yml
.github/actions/post-release-updates/action.yml
.github/actions/s3-upload/action.yml
.github/actions/shared-utils/fetch-retry.js
.github/actions/size-diff/action.yml
.github/actions/update-current/action.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-experiment.yml
.github/workflows/publish-release.yml

---
New experiments and A/B script publishing process:
- Experiments workflow will now ask which environment to publish the experiment to. Only that environment's A/B scripts will be rebuilt after the experiment is published into a sub-directory of `/experiments/{{environment}}/` in the S3 bucket.
- Experiments can still be published to both `dev` and `staging` but it must be done by running the workflow twice, once for each environment.
- The publish-release and publish-dev workflow will no longer pass different values for the currently released and next versions of the loader.
- The publish-release workflow will no longer gate the publishing of the `current` loader on …

chore: New experiments publishing process

---

src/common/harvest/harvest-scheduler.js
src/common/harvest/harvest-scheduler.test.js
src/features/metrics/aggregate/index.js
src/features/page_view_timing/aggregate/index.js

Fix an issue where metrics unloading would create an endless loop
---
Fixes endless loop related to #702

chore: fix endless metrics call

---

src/common/config/state/init.js
src/common/config/state/init.test.js
src/common/dom/query-selector.js
src/common/dom/query-selector.test.js
tests/specs/session-replay/rrweb-configuration.e2e.js

Update the block selector, mask selector, and mask input setters to handle empty strings
---
block_selector should always return [data-nr-block] as well as any customer-supplied configs in a comma delimited string.  This failed when `''` was passed as an argument, as the agent would append `,''` to the string, breaking the agent.
other configs could also benefit from being validated, so those were added here as well.
NR-162325
Tests have been added.  Can be confirmed manually by supplying `''` as the block_selector argument to init.session_replay in a test-server page and inspecting the `initalizedAgents` config property.

fix: Validation of SR configurations

---

src/common/config/state/init.js
src/common/config/state/init.test.js

One validation case was missed in PR #721 .  mask_text_selector can accept `null` as an argument and the dom query validator blocks null.
---

chore: add missed validation case

---

.github/actions/internal-ab/action.yml
.github/actions/s3-upload/action.yml
.github/actions/s3-upload/args.js
.github/actions/s3-upload/asset-cache.js
.github/actions/s3-upload/index.js

Released browser agent assets will now be delivered with a 1 year cache header. This will allow user's browsers to cache the async chunks the agent loads for much longer and eliminate performance recommendations found in synthetic performance tools like Lighthouse. This will be applied retroactively to all released versions of the agent.
---
Updating the s3-upload action to apply a 1 year cache header to versioned released asset files uploaded to the root of our s3 bucket.
https://issues.newrelic.com/browse/NR-149717

feat: Applying new cache headers to assets

---

src/features/session_replay/aggregate/index.js

Add a SM when the SR feature cannot send due to DOM size
---
https://issues.newrelic.com/browse/NR-163032

chore: add SM when SR cant send due to size

---

src/common/config/state/init.js

Only warn if the block config is not an empty string, which is the default supplied by the API if not set
---

chore: SR validation - only warn if not empty string

---

src/common/config/state/init.js
src/common/config/state/init.test.js

Modify mask_text_selector setter
---
A result of bug testing led to decision that the `mask_text_selector` config should now do the following:
* if no config (undefined) is provided --> `*`
* if any value is provided (including null)--> use that value, but append `[nr-data-mask]`
Tests have been updated to match and other pre-existing SR tests should continue to pass

chore: Modify mask_text_selector setter

---

src/features/utils/instrument-base.js

A failure to import and initialize a feature could block the agent from draining data out of the event emitter, which prevents the agent from making any successful calls.  This fix allows the event emitter to drain even when an individual feature fails to initialize.
---
A failure to import and initialize a feature could block the agent from draining data out of the event emitter, which prevents the agent from making any successful calls.  This fix allows the event emitter to drain even when an individual feature fails to initialize.  This is also tangentially related to the Session Replay feature failing to import and blocking the agent on polyfill builds. 
This PR would replace the need for #729 if deemed appropriate
All tests should continue passing

fix: Drain event emitter even when feature fails to initialize

---

src/cdn/polyfills/lite.js
src/cdn/polyfills/pro.js
src/cdn/polyfills/spa.js

Add more control over the polyfill builds by explicitly building the agent instance
---
This is necessary to exclude Session Replay entirely from the polyfill build.  This should be evaluated if this is the desired behavior.

chore: Add more control over the polyfill builds

---

.github/workflows/wdio-single-browser.yml
src/features/session_replay/aggregate/index.js

Add messaging to signal why a replay aborted, which could happen for a number of reasons.
---
This PR adds messaging to signal why a replay aborted
Tests should be unaffected

feat: Add messaging about Session Replay abort behavior

---

tools/jil/webpack.modular.js
tools/shared/serializer.js
tools/testing-server/constants.js
tools/testing-server/index.js
tools/testing-server/plugins/agent-injector/config-transform.js
tools/testing-server/plugins/agent-injector/init-transform.js
tools/testing-server/plugins/bam-parser/index.js
tools/testing-server/plugins/deserialize-body/index.js
tools/testing-server/routes/command-apis.js
tools/testing-server/routes/tests-index.js
tools/testing-server/test-handle.js
tools/testing-server/utils/url.js
tools/wdio/plugins/testing-server/index.mjs
tools/wdio/plugins/testing-server/launcher.mjs
tools/wdio/plugins/testing-server/test-handle-connector.mjs
tools/wdio/runner.mjs

---
Pre-existing use of serialize-anything was refactor into a central module agnostic of the underlying serializer used. Url configruation passing via query param switched to using this module. The body of requests to the command server for the few api's also switched to using serializer.
[NR-136508](https://issues.newrelic.com/browse/NR-136508)
That all existing test works, both jil and wdio.

chore: Use serialize-any on url config and command body

---

src/common/session/session-entity.component-test.js
src/common/session/session-entity.js
src/features/session_replay/aggregate/index.component-test.js
src/features/session_replay/aggregate/index.js
tests/specs/session-manager.e2e.js
tools/wdio/plugins/custom-commands.mjs

Add logic to set firstChunk flag and replay mode on new replays more reliably.
---
This PR increases reliability of SR payload decoration in two ways:
* it adds logic to decorate firstChunk flags better while running in error mode
* it adds logic to ensure replay mode syncs across tab changes
https://newrelic.slack.com/archives/C04QZSS6XPV/p1695774682575609?thread_ts=1695766285.826099&cid=C04QZSS6XPV
Existing tests should continue to pass

fix: Set Session Replay first chunk flags more reliably

---

.github/actions/size-diff/get-stats.js
.github/actions/size-diff/report-settings.js

---
Since release 1.240.0 where the SR feature was included in the PRO and SPA builds, the size diff table on PRs has been incorrectly using the wrong asset size when calculating the async chunk diff. Since the recorder chunk appears in the JSON stats file first, it was being used in the calculation due to poor string replacement logic in the size diff script.
The updated script uses a regular expression and takes into account the version of the agent stats are being retrieved for to ensure the correct asset stats are used in the diff. The regular expression also contains support for the hash that was removed from the file names in version 1.241.0 allowing us to compare …

chore: fix size diff action script

---

src/common/session/session-entity.js
src/features/session_replay/aggregate/index.js
tests/specs/session-replay/session-pages.e2e.js

Tap session entity into storage event listener for stateful changes across tabs.
---
There are certain cases where the agent needs to update when changes happen in backgrounded tabs. Utilizing the storage API allows for updates from other tabs.
A test has been added to ensure that a backgrounded tab could terminate an existing session replay

fix: Tap session entity into storage api for changes across tabs

---

src/loaders/configure/configure.js
src/loaders/configure/public-path.js

Tweaks the feature added in v1.240.0 wherein the agent code became proxy-able. It worked correctly in expecting that the protocol (i.e. `https://`) is included in the configuration input, but we have since decided that it can be excluded in conformity with the proxy beacon field that only accepts a host string.
---
Both proxy.beacon and proxy.assets should follow the format `<hostname>[:<port>]` now, without protocol specified (will default to https).
#659 
Existing proxy.e2e.js suffices.

fix: Re-update assets proxy to accept host URL strings

---

src/features/spa/aggregate/index.js

Improving context isolation for events the SPA feature tracks to allow for multiple agent bundles to live on the same page. This is only intended for internal New Relic usage at this time and should not affect customers.
---
When running multiple agent bundles on the same page, we get two initial page load interactions but only one interaction for all soft navigations. This was caused by the SPA feature not scoping the scope object it was adding to the events. Adding scoping now results in both agent bundles sending their own interactions for soft navigations.
https://issues.newrelic.com/browse/NR-152262

fix: Isolate browser interaction node

---

babel.config.js
package-lock.json
package.json
src/common/constants/__mocks__/env.js
src/common/constants/env.cdn.js
src/common/constants/env.js
src/common/constants/env.npm.js
src/features/session_replay/aggregate/index.js

Bump rrweb dependency version to 2.0.0.11 and include in Session Replay payload metadata dynamically
---
This PR updates the rrweb dependency version and updates the build process to include it dynamically instead of as a hard-coded constant value.
https://newrelic.slack.com/archives/C04QZSS6XPV/p1696953790363509
All existing tests should continue to pass

feat: Bump rrweb to 2.0.0.11 and make constant dynamic at build time

---

src/features/session_replay/aggregate/index.js

Ensure that Session Replay node injection does not cause desynchronized timestamps for blob payloads 
---
This PR ensures that injected nodes (meta injection) do not get out of order due to processing sequencing.
https://newrelic.slack.com/archives/C04QZSS6XPV/p1695766285826099
Tests should continue to pass

fix: Fix invalid timestamps

---

src/loaders/api/api.component-test.js
src/loaders/api/api.js

Allow boolean values to be supplied to newrelic.setCustomAttribute() API calls.
---
Old versions of the agent allowed boolean values for setCustomAttribute, which did not match our documentation.  An effort was conducted some time ago to align the agent with the docs, and booleans were forcibly denied.  This is causing some migration issues for some customers, and there is no clear reason to exclude booleans from this API.
https://new-relic.atlassian.net/browse/NR-171312
Tests have been updated to account for the change

feat: Allow boolean values in setCustomAttribute

---

src/common/vitals/first-input-delay.js
src/common/vitals/largest-contentful-paint.js
src/common/vitals/vital-metric.js
src/common/vitals/vital-metric.test.js
src/features/page_view_timing/aggregate/index.component-test.js
src/features/page_view_timing/aggregate/index.js
src/features/page_view_timing/aggregate/index.test.js

Add client network information to all PageViewTiming events in New Relic. The attributes currently only exist on LCP and FI event types and will now be reported with all others such as load and pagehide events.
---
FR to add network attributes to other pvt nodes. It'll be shown now via NRQL and may be picked up by UI in the future to highlight the at-the-time network conditions when certain metrics are captured.
NR-168402
Modified existing tests.

feat: Add network info to all page view timing events

---

tests/specs/stn/payload-metadata.e2e.js

---
Just making test previously merged by #765 work for Safari too

chore: Tweak payload-metadata test for safari

---

package-lock.json
src/features/utils/feature-base.js
src/features/utils/instrument-base.js
tools/test-builds/vite-react-wrapper/package.json
tools/test-builds/vite-react-wrapper/tsconfig.json

Fixing missing type declarations in the feature utilities that show up when skibLibCheck is not enabled in the tsconfig.
---
Fixing missing type declarations in the feature utilities that show up when skibLibCheck is not enabled in the tsconfig. This also enabled lib checking in the vite wrapper test project to ensure this is not an issue in the future.
TBD

fix: Fix missing type declarations

---

.github/actions/update-current/index.js

---
The cache header was still being based on the versioned loader name instead of the `current` name.

chore: Fix the cache header for current loader

---

src/common/session/session-entity.js
src/features/session_replay/aggregate/index.component-test.js
src/features/session_replay/aggregate/index.js
tests/specs/session-replay/harvest.e2e.js

Add current session's running duration to all outgoing session replay payloads for use with ingest estimations
---
This PR adds the current session's running duration to all outgoing payloads.  Intended to be digested by using latest(session.durationMs) via NRQL for ingest estimation purposes.
NR-173704
Tests have been updated to account for the new property

feat: Add session durationMs to Session Replay payloads

---

.browserslistrc
.github/workflows/wdio-all-browsers.yml
tools/browsers-lists/browsers-supported.json
tools/browsers-lists/sauce-browsers.mjs

---
Temporarily pinning our iOS support to 15.5 or later. SauceLabs does not have VMs available for iOS 15.6 or 15.7 so we cannot test those browsers at the moment. Once iOS 15.x drops out of our `last 10 iOS versions` query, we can revert this.

chore: Pin iOS testing to >= 15.5

---

src/features/session_replay/aggregate/index.js
src/loaders/configure/nonce.js
tests/specs/session-replay/helpers.js

Expose library versions used to capture session replay data, to help sync visualizations in the UI Replayer components across version migrations.
---
This PR exposes the rrweb lib version used to capture the reply data to a public namespace to be used for UI syncing purposes.
https://new-relic.atlassian.net/browse/NR-178304
Tests have been updated to account for the change

feat: Expose library versions used to capture session replay data

---

src/features/session_replay/aggregate/index.js
src/loaders/configure/nonce.js
tests/specs/session-replay/helpers.js

Add relative timestamps to Session Replay payloads to allow for server-side clock skew adjustments and improve the API pagination experience.
---
This PR adds the `rst` param, which is seen on all other browser agent payloads, as well as a relative representation of the first payload node to allow for server-side clock skew adjustments if the server time and the rst time differ drastically.
NR-177602
Tests have been updated to account for the extra params

feat: Add relative timestamps to Session Replay payloads

---

src/features/session_replay/aggregate/index.js

Report enduser.id if set with Session Replay data to improve faceting the Session Replay UX
---
This PR adds the enduser id to outgoing SR payloads to help facilitate increased faceting in Session Replay UXs.
https://new-relic.atlassian.net/browse/NR-180218

feat: Report enduser.id with Session Replay

---

src/features/session_trace/aggregate/index.js
tests/specs/stn/with-session-replay.e2e.js

Fixing an issue where an uncaught error or calls to the `noticeError` API would force session trace to begin collecting and harvesting data, even though session trace and session replay were disabled via the RUM response.
---
With the recent session replay API merge, an error thrown on a page or passed in using the `noticeError` API method would cause session trace to switch to full mode. This was due to session trace not accounting for the current session replay mode when switching modes. If session replay is disabled, session trace should not switch modes at all from it's initial mode.
https://newrelic.pagerduty.com/incidents/Q05RP88T92MSAS/
https://github.com/newrelic/newrelic-browser-agent/pull/803
Full suite passed locally. Seeking merge due to time constraints for active incident

fix: Fix issue with errors forcefully triggering session traces

---

src/common/ids/unique-id.js
src/common/ids/unique-id.test.js

Fix non-random hexadecimal generation when using the webcrypto api, which in turn creates non-random traceIds, that always end in 00
---
A bug in the generation of random hexadecimal values when using `webcrypto` means the traceIds used for the distributed tracing spans are not fully random, and all traceIds will end in `00`. The W3C spec says this value should be random, and this can cause issues for organizations who are enforcing browser span sampling by using drop rules versus the last characters of the spans. 
The cause is a double out of bounds, once when iterating over an array using `++var` instead of `var++` and second when the size of the hex value is 32 characters, due to the `Uint8Array` used for the webcrypto random number generation length being hardcoded to `31`.
Issue: …

fix: traceids not random when using `webcrypto`

---

.github/actions/s3-upload/args.js
.github/actions/update-current/args.js
.github/actions/update-current/index.js
.github/workflows/publish-internal.yml

---
Fixes the issue with the dry run flag not working and an issue with the internal release script not using the correct parameters based on selected environment.
https://new-relic.atlassian.net/browse/NR-185891

chore: fix dry run automation

---

src/loaders/agent-base.js

Fix warning messages given by API calls made before the agent has initialized
---
The Agent gave an incorrect message for `setUserId` when called before the agent was initialized.  This change aligns all API calls to give the same generic message.
NR-186348
All tests should be unaffected

fix: Fix API Warning Messages

---

src/common/config/state/init.js
src/common/config/state/init.test.js

Allow empty strings to be provided for Session Replay masking values.  This will help the UI/API provide sane fallbacks for never-set values.
---
This PR sets the SR mask state to the default `[data-nr-mask]` if an empty string is provided
NR-184724
A new basic test case has been added to validate this behavior

feat: Allow empty string for Session Replay masking value

---

.github/actions/s3-upload/index.js
tools/test-builds/library-wrapper/package.json

---
Updated the s3-upload action to first check if any of the files being uploaded have a long-term cache policy and already exist in the s3 bucket. If a file is found matching these two criteria, the action will fail and prevent the uploading of the files.
https://new-relic.atlassian.net/browse/NR-185887

chore: prevent s3-upload of existing files

---

.github/actions/s3-upload/index.js

---
It was found in the last release that all the size report html files had a mime type of `application/javascript`. This was due to a mistake in the s3 upload code where the mime lookup was being based on the file directory location instead of the file name.
N/A

chore: fix s3 upload mime lookup

---

src/common/ids/unique-id.js

Fixes a regression which caused all trace ids generated to end in a 0.
---
A previous fix for trace ids ending in 00 had a commit added that provided tests and some other fixes, unfortunately this commit partially reverted the 00 fix, causing the traceids to end in 0.
Note: The added tests do not seem to detect issues with the randomness of the trace ids and this PR does not attempt to remedy this.
https://github.com/newrelic/newrelic-browser-agent/issues/854
Please see (https://github.com/newrelic/newrelic-browser-agent/pull/825) for detailed testing instructions.

fix: TraceId generation regression (non-random trace ids)

---

src/common/harvest/harvest.js
src/common/harvest/harvest.test.js
src/common/url/encode.js

Added a flag to mark harvests as having occurred during an active session replay. This will aid cross-feature querying in NR1.
---
This PR adds the `hr` flag to note that a payload "has replay".  This was already implemented in Session Traces so this extends that pattern to all payloads. This is a very simple implementation, only reading from the session entity at harvest time to determine the replay mode.
NR-189641
Tests should continue to pass

feat: Add a flag to note that a payload occurred during a replay

---

src/features/session_replay/shared/recorder.js

Add a fallback to the currentBufferTarget for cases where the preload buffer has been cleared 
---
This PR sets the currentBufferTarget to the preload buffer only if it exists.  This should alleviate an edge-case issue where the payloadBytesEstimation throws an error because the buffer target does not exist.
https://new-relic.atlassian.net/browse/NR-215642

fix: Add fallback for currentBufferTarget

---

src/features/session_replay/shared/recorder.js
src/loaders/agent-base.js
src/loaders/agent.js
tests/dts/api.test-d.ts
tests/specs/npm/index.e2e.js
tools/test-builds/browser-agent-wrapper/src/browser-agent.js
tools/test-builds/browser-agent-wrapper/src/custom-agent-lite.js
tools/test-builds/browser-agent-wrapper/src/custom-agent-pro.js
tools/test-builds/browser-agent-wrapper/src/custom-agent-spa.js
tools/test-builds/raw-src-wrapper/src/browser-agent.js
tools/test-builds/raw-src-wrapper/src/custom-agent-lite.js
tools/test-builds/raw-src-wrapper/src/custom-agent-pro.js
tools/test-builds/raw-src-wrapper/src/custom-agent-spa.js
tools/test-builds/vite-react-wrapper/src/newrelic.ts

Fix an issue where the NPM wrapping of the agent would not bubble the APIs up to the top-level of the instance, causing invalid warnings to log.
---
This PR makes sure that the top level instance calls the internal APIs directly instead of relying on object assignment.
https://new-relic.atlassian.net/browse/NR-216981
New tests have been added to validate that NPM builds have access to the top level api methods

fix: Bubble Up API Methods to Top-Level Instance For NPM

---

src/features/metrics/aggregate/index.js
src/features/session_replay/aggregate/index.component-test.js
src/features/session_replay/aggregate/index.js
src/features/session_replay/shared/recorder.js
src/features/session_replay/shared/stylesheet-evaluator.js
tests/specs/session-replay/session-pages.e2e.js
tests/specs/session-replay/session-state.e2e.js
tools/wdio/plugins/custom-commands.mjs

Force agent to send preloaded session replay payloads if present at load time.
---
This PR forces the agent to harvest at agg load time if there are preload payloads.  This alleviates an issue where the payload would race with standard payloads at unload time.
New tests have been added and old tests have been modified to account for earlier harvests

fix: Fix deferred Session Replay payloads

---

src/common/drain/drain.js
src/common/drain/drain.test.js
src/common/event-emitter/contextual-ee.component-test.js
src/common/event-emitter/contextual-ee.js
src/common/harvest/harvest.js
src/common/harvest/harvest.test.js
src/features/page_view_event/aggregate/index.js
src/features/utils/instrument-base.js
src/features/utils/instrument-base.test.js
src/loaders/api/api.js
tests/assets/adblocker-assets.html
tests/assets/adblocker-ingest.html
tests/specs/adblocker.e2e.js

Fixed memory leaks caused by request resolve failure (e.G. due to adblocker)
---
On our website ( playbook.com ), some users were noticing severe performance degredation when uploading big files. Memory usage grew, and cancelling of the upload did not resolve the issue, eventually causing in a crash of the upload or the website itself.
After investigation, we were able to pin down the issue to the New Relic Browser Agent. However, the issue only occured when adblock (in my case: uBlock Origin) was enabled.
We noticed that two URLs specifically were being blocked: `https://js-agent.newrelic.com/nr-spa-1.245.0.min.js` and `https://bam.nr-data.net/`. 
(Note: Issue occured also with newest version of Browser Agent)
The issue itself is not actually related to uploading - this only made the …

fix: Fix adblock memory leak

---

src/features/session_replay/aggregate/index.component-test.js
src/features/session_replay/aggregate/index.js

Capture supportability metrics sounding Session Replay configuration usage to improve user experiences around configuration of the agent's Session Replay feature.
---
NR-221612
Angler -> https://source.datanerd.us/agents/angler/pull/545
A jest test has been updated to account for moving the configuration getters out of the flag promise for better DRY mechanics.

feat: Capture Internal Metrics for Session Replay Configurations

---

src/features/jserrors/instrument/index.js
tests/assets/js-error-syntax-error.html
tests/specs/err/index.e2e.js

Aligning the data reported for uncaught syntax errors across modern browsers. Chrome specifically fails to include the file name and line number in instances of SyntaxError. This could also cause issue in the New Relic error inbox where Chrome syntax errors were not being properly grouped.
---
For uncaught instances of SyntaxError, we now purposefully extract the error details from the error event itself instead of passing the `event.error` object through the event emitter. This ensure we extract the file name and line number for all browsers.
While IE is tested in the new e2e tests, IE does not provide an `event.error` property so all uncaught exceptions are reported as instances of our internal `UncaughtError` class.
https://new-relic.atlassian.net/browse/NR-190314 …

feat: align browser reported uncaught syntax errors

---

src/common/config/state/init.js
src/features/session_replay/aggregate/index.js

Detect if the default config values have been altered at runtime.  This is useful to evaluate what the reasonable defaults are across a customer base over time to provide a better UX.
---
This PR also contains a change to the SR init to align the defaults to the UI and API, of 10% and 100%

feat: Report config changes away from default state for UX improvement

---

src/features/session_replay/shared/recorder.js

Safe-guarded a race condition where an asynchronous call to fix a stylesheet could trigger the agent to try to force a snapshot after it has already stopped recording due to a visibility change.
---
The agent makes an async call to attempt to fix non-inlinable stylesheets, but this operation is asynchronous.  If anything triggers the agent to stop recording before the async job resolves, it will errantly attempt to take a snapshot with no active recording.  This behavior safe-guards that in two ways with a status check and a try/catch.
https://newrelic.slack.com/archives/C04QZSS6XPV/p1707505446130859

fix: Add safe logic to snapshots

---

README.md

No summary
---
Replace "New Relic One" with simply "New Relic"
https://new-relic.atlassian.net/browse/NR-137449

chore: Remove "One" from "New Relic One"

---

tools/jil/package-lock.json

Updates to testing packages needed to enable FOSSA scanning.
---
Update tools/jil/package-lock.json to a v3 lockfile
This change enables our license scanning tool, FOSSA, to run without errors. This tool will soon be required for all public repos. 
The lockfile is already in a valid format, only the version number needs to be changed. 
N/A
This has been validated with a local run of the FOSSA CLI. The tool ran successfully.

chore: Enable FOSSA by updating package-lock to v3

---

src/common/session/session-entity.component-test.js
src/common/session/session-entity.js

When a session expires or becomes inactive while the user does not have the page open and they re-open the page, that is now treated as a new session.
---
We had an issue where off-page expiration or timeouts of session resulted in the next on-page load to initialize a session that isn't new (i.e. `isNew` false). This is not intended and has been fixed.
https://new-relic.atlassian.net/browse/NR-230914
New jest test cases added to check for correct program flow and `isNew` value rather than with entire agent. This suffices to get the behavior we want.

fix: Page load after session timeouts don't start new session

---

babel.config.js

Fixing some import overrides in our NPM package build to prevent imports existing that include code reliant on webpack globals. This will resolve the error `Uncaught ReferenceError: __webpack_require__ is not defined` when using the NPM package in a project that does not use webpack.
---
Our import overrides for the couple of files that access webpack globals was not being applied correctly. This resulted in imports for code that relied on webpack globals in the NPM package. If the customer is not using webpack, this will result in a runtime error.
https://new-relic.atlassian.net/browse/NR-233660
I could not find a good way to test this issue in an automated way. To verify manually, search the `dist` directory for imports of `nonce` and `public-path`

fix: Fix webpack imports in npm package

---

.github/actions/build-ab/templates/experiments.js
.github/actions/build-ab/templates/latest.js

---
Updating our internal A/B scripts to enable the feature flag for blocking the collection of ajax metrics for domains in the deny list.
https://new-relic.atlassian.net/browse/NR-239922

chore: Enabling bam ajax metrics blocking internally

---

src/common/config/state/runtime.js
src/common/harvest/harvest.js
src/common/harvest/harvest.test.js

Add a counter which increments after every harvest. This will be used in a future effort to curate a unique harvest ID for API paging purposes.
---
This PR adds a harvestCount int to the runtime object, which increments every time `_send` is completed.  `_send` is used under the hood by all harvest methods to send data.  The plan for the future will be to concat this harvestCount with the `ptid` and `session` values to create a unique harvest identifier on blob-consumer payloads.
https://new-relic.atlassian.net/browse/NR-238623
https://new-relic.atlassian.net/browse/NR-238628
A new, simple jest test has been added to confirm this behavior.  WDIO test should be added later when implemented in outgoing harvests

feat: maintain a harvestCount for use later with harvestId

---

.github/workflows/eslint.yml
.github/workflows/jest.yml
.github/workflows/jil-single-browser.yml
.github/workflows/nightly.yml
.github/workflows/post-release-updates.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-experiment.yml
.github/workflows/publish-internal.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request-checks.yml
.github/workflows/repolinter.yml
.github/workflows/wdio-single-browser.yml

---
Change GH actions inside workflows to use v4 of setup-node and checkout instead of v3.
https://new-relic.atlassian.net/browse/NR-247055
https://new-relic.atlassian.net/browse/NR-247052
Same tests

chore: Upgrade setup-node and checkout to v4

---

src/features/metrics/aggregate/index.component-test.js
src/features/metrics/aggregate/index.js

Send SM when long task config setting is set to enabled for internal eval.
---
Angler edit: https://source.datanerd.us/agents/angler/pull/563
https://new-relic.atlassian.net/browse/NR-248731

chore: SM for long task

---

src/common/timing/time-keeper.js
src/common/timing/time-keeper.test.js
src/features/page_view_event/aggregate/index.js

Removing reliance on the browser resources API for the calculation of New Relic server time. On site with many resource requests, there was a small chance that the RUM network call would be flushed from the resources API cache before we could capture it and calculate server time.
---
Simplifying the NR server time calculation to use our own captured start and end times for the RUM network request. On our internal NR site, we were rarely seeing an error related to the time keeper not being able to calculate server time. The cause was found to be the RUM call missing from the resources API buffer. This is most likely because there is a max buffer size in the browser after which the browser starts dropping older resource requests.
We decided to not use a more precise method of setting up a …

fix: Server Timing - Remove reliance on performance API

---

.github/actions/size-diff/action.yml
.github/workflows/jest.yml
.github/workflows/pull-request-checks.yml
.github/workflows/wdio-single-browser.yml

---
Change GH actions inside workflows to use v4 of codecov-action and upload-artifact instead of v3.
https://new-relic.atlassian.net/browse/NR-253209
https://new-relic.atlassian.net/browse/NR-253206

chore: Upgrade codecov and upload-artifact to v4

---

src/features/page_view_timing/aggregate/index.component-test.js
src/features/page_view_timing/aggregate/index.js

`cumulativeLayoutShift` can now be queried for (with that as its `timingName`) as its own PageViewTiming event in New Relic. The additional attribution are a part of these events, and the values are more reflective of true end-session CLS scores.
---
Uncomment cls timing node for attribution.
https://new-relic.atlassian.net/browse/NR-239252
Full test suite

feat: Send CLS as timing node additionally

---

src/features/session_replay/aggregate/index.js

Track Session Replay harvest attempts to aid in debugging Session Replay abort rates.
---
https://source.datanerd.us/agents/angler/pull/566
https://newrelic.slack.com/archives/C04QZSS6XPV/p1712681150748099?thread_ts=1712353671.785849&cid=C04QZSS6XPV

chore: Add Metric Tracking Session Replay Harvest Attempts

---

src/common/harvest/harvest.js
src/features/session_trace/aggregate/index.js
src/loaders/configure/configure.js
tests/functional/stn/index.test.js
tests/specs/harvesting/index.e2e.js
tests/specs/stn/retry-harvesting.e2e.js
tests/specs/stn/with-session-replay.e2e.js
tests/unit/common/harvest/harvest.test.js

Generate PTID in agent instead of in RUM response.  This allows PageView events to be decorated with a page trace ID.
---
This abstracts the action of generating our own PTID out of the ST merge PR into a standalone PR
NR-166514
NR-167098
Affected tests have been updated

feat: Generate PTID in Agent

---

src/common/constants/runtime.js
src/common/timing/time-keeper.js
src/features/session_replay/aggregate/index.js
src/features/session_replay/shared/recorder-events.js
src/features/session_replay/shared/recorder.js
src/features/session_replay/shared/utils.js
tests/specs/nr-server-time.e2e.js

Ensure Session Replay timestamps are only ever adjusted once and fix correction factor to alleviate timeOrigin inconsistencies
---
This PR ensures that SR timestamps are only ever adjusted once, and that the origin time they use to correct the issue does not fall victim to a known timeOrigin bug in Chromium and Firefox browsers. 
* https://issues.chromium.org/issues/40866530
* https://bugzilla.mozilla.org/show_bug.cgi?id=1710762

fix: stabilize timestamp corrections

---

src/common/harvest/harvest.js
src/features/session_trace/aggregate/index.js
src/loaders/configure/configure.js
tests/functional/stn/index.test.js
tests/specs/harvesting/index.e2e.js
tests/specs/stn/retry-harvesting.e2e.js
tests/specs/stn/with-session-replay.e2e.js
tests/unit/common/harvest/harvest.test.js

Revert a change causing Trace to begin harvest even when the rum flag given is `0`.
---
This reverts commit af7b6764f40cb1ddfb3ab2ca16d05d8e4f459f4e.
Escalation https://newrelic.slack.com/archives/C0193KAHHAS/p1713186294566949 & #emergency-room on 15/4/2024

fix: Revert "Generate PTID in Agent"

---

src/features/soft_navigations/aggregate/index.js
tests/components/soft_navigations/api.test.js
tests/components/soft_navigations/index.test.js

Address a couple scenarios of memory being not released by the soft navigation harvest cycle.
---
Release memory in the following scenarios (jest test cases):
- when harvest is blocked (cors, adblock, etc.)
- when harvest is fully successful
https://new-relic.atlassian.net/browse/NR-256262
Split 1 file into 2 + added

fix: Soft navigations memory leak on harvest

---

.eslintrc.js
src/loaders/agent.js
tests/dts/agent.test-d.ts
tests/dts/api.test-d.ts

Fixing incorrect type declarations for the constructor parameters of the Agent class.
---
Fixing incorrect type declarations for the constructor parameters of the Agent class.
https://github.com/newrelic/newrelic-browser-agent/issues/952

fix: Agent class type declarations

---

src/features/jserrors/aggregate/index.js
src/features/session_replay/aggregate/index.js
tests/specs/session-replay/adjacent-payloads.e2e.js

In scenarios where the SessionReplay feature was preloaded but a recording was never started, errors happening on the page would be improperly decorated with the `hasReplay` flag.
---
This introduces a pre-harvest cross-feature communication event within the JSErrors feature. When a harvest occurs, the JSErrors feature will send out the `cfc.jserrors` event with an object containing information about the errors being harvested.
The SessionReplay feature has been updated to listen to the `cfc.jserrors` event and decorate the event payload with a `hasReplay` flag in the aggregate. The flag will be true only if the aggregate loaded, the aggregate has a running harvest scheduler, the aggregate has a recorder initialized, the mode is in `FULL`, the aggregate is not blocked, and the aggregate …

fix: JSEerrors harvest hasReplay decoration

---

src/common/harvest/harvest.js
src/features/jserrors/aggregate/index.js
tests/assets/rrweb-duplicate-errors-split.html
tests/components/spa/initial-page-load.test.js
tests/specs/session-replay/mode.e2e.js

Change the error aggregation method to consider errors with a hasReplay flag separately to ensure timestamps are always correct. Decorate each aggregation set with hasReplay directly instead of a request-level query param
---
This PR abstracts the aggregation of errors with hasReplay to their own set, which ensures that the `firstOccurrenceTimestamp` is not applied to duplicate errors that may have happened outside of a replay's import logic.
https://new-relic.atlassian.net/browse/NR-260137
New tests have been added which check that duplicated errors are buckets and decorated correctly.

feat: Decorate errors with hasReplay individually

---

src/features/jserrors/aggregate/index.js
tests/specs/err/error-payload.e2e.js

JSErrors that happen multiple times throughout a page's life will now receive a timestamp unique to the agent harvest cycle instead of always reporting the timestamp of the first occurrence of that error.
---
Modified the JSErrors feature to cache the error timestamp per harvest cycle instead of per page lifecycle.
https://new-relic.atlassian.net/browse/NR-261440

feat: JSErrors timestamped per harvest

---

src/common/vitals/vital-metric.js
tests/unit/common/vitals/cumulative-layout-shift.test.js

Add check to prevent null and undefined web-vitals values from being reported 
---
This PR prevents the vital-metric class from updating/emitting if provided a nullish value.  This was only observed in practice during some wdio test runs (blocking some PRs intermittently) -- And we don't exactly understand why web-vitals would even emit a nullish value -- But this is a simple fix that should prevent issues later if this is actually happening in the wild since we should not be reporting null values.
NR-260221
Unit test has been updated to ensure nullish values are not reported to the subscribers

fix: Prevent null CLS

---

src/common/config/state/runtime.js
src/features/session_replay/aggregate/index.js
tests/specs/session-replay/helpers.js

Adds a unique harvest ID to Session Replay payloads to support better indexing and querying on the platform.
---
This PR is partially abstracted out of the ST merge PR (#821), as that is currently blocked
NR-238623
Test platform has been updated to check for harvestID in all SR tests

feat: Add harvestId to Session Replay payloads

---

src/features/utils/instrument-base.js
src/loaders/api/api.js
tests/components/api.test.js
tests/specs/api.e2e.js

The `start()` method in agent API no longer accepts an argument. It will forcibly start all features that were marked `autoStart: false` in the configuration that has not yet started when it is called. If `page_view_event` had this property set to false, the agent will not send anything until `start` is called.
---
No. more. feature-specific start(). This is due to use case feedback and unneeded complexity with all the possible auto/manual start permutations.
https://new-relic.atlassian.net/browse/NR-260970
Edited

fix: Remove API start()'s features param

---

.eslintrc.js
src/common/vitals/time-to-first-byte.js
src/features/page_view_event/aggregate/index.js
tests/assets/iframe/cross-origin.html
tests/assets/iframe/iframe.html
tests/assets/iframe/same-origin.html
tests/specs/rum/index.e2e.js
tests/webview-specs/ios/index.e2e.js
tools/testing-server/index.js
tools/testing-server/plugins/cache-interceptor/index.js
tools/testing-server/utils/expect-tests.js

Resolve a bug that prevented the agent from running in cross-origin iFrames for Firefox and Safari due to how the browsers implement context security.
---
If the agent is running inside an iframe, it will skip subscribing to the `onTTFB` event. If the iframe is cross-origin, some browsers will block access to the `responseStart` property of the navigation performance entry. This was caused by a change in the [WebVitals](https://github.com/GoogleChrome/web-vitals) library to treat `0` as an [invalid timestamp value](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/isInvalidTimestamp.ts#L21-L24).
https://new-relic.atlassian.net/browse/NR-262293
https://github.com/GoogleChrome/web-vitals/issues/275

fix: Run inside cross-origin iframes for firefox/safari

---

src/features/jserrors/aggregate/index.js
tests/specs/err/error-payload.e2e.js

Short circuit the execution of the noticeError API if an argument is not supplied
---
This also tangentially fixes an issue introduced in #1014  
A new test has been added

fix: Prevent noticeError() API from running if not given an argument

---

src/common/session/session-entity.js
src/common/timing/time-keeper.js
tests/specs/nr-server-time.e2e.js
tests/unit/common/timing/time-keeper.test.js

Allow first tab to fully instantiate a time correction to take precedence
---
https://newrelic.slack.com/archives/C04QZSS6XPV/p1715357189958959
Existing tests have been updated

fix: Adjust session entity to not race between tabs

---

src/features/session_trace/aggregate/index.js
src/features/session_trace/aggregate/trace/storage.js
tests/components/session_trace/index.test.js

Fix an instance of undefined error in Session Trace feature introduced in v1.259.0. Harvest will now no longer be attempted if there are no trace nodes to send.
---
Fix a scenario wherein `stns` is undefined and causing problem when `.length` property is accessed for it. Instead, prepareHarvest will early exit when such is the case.
https://new-relic.atlassian.net/browse/NR-270488
Component test added

fix: Undefined stns in blob Trace

---

src/common/wrap/wrap-logger.js
src/loaders/api/api-methods.js
src/loaders/api/api.js
tests/components/api.test.js
tests/specs/api.e2e.js
tests/specs/npm/index.e2e.js
tests/unit/loaders/api/api.test.js

Observe existing logging functions and report through event emitter for later processing when capturing log events.
---
** NOTE ** please review #1052 first, as this PR is branched from that.
NR-251149
New jest tests have been added

feat: Add wrapLogger API method for wrapping 3rd party loggers

---

src/common/config/state/init.js
tests/unit/common/config/state/init.test.js

Add default configuration settings to be used for upcoming logging feature
---
The init block to control the logging feature
[NR-251150](https://new-relic.atlassian.net/browse/NR-251150)
A generic test has been added to validate that the init block returns the props and default vals that are expected 
[NR-251150]: https://new-relic.atlassian.net/browse/NR-251150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Logging Configurations

---

tests/util/basic-checks.js
tools/browser-matcher/common-matchers.mjs

---
LT android all (2): 
SL android all (2): 
https://new-relic.atlassian.net/browse/NR-277051
`npm run wdio -- -f merged --lt -b "android@*" --concurrent 10`

chore: android@* passing with LT

---

src/features/session_replay/aggregate/index.js

for evaluation of SR payload splitting effort
---

chore: add SM with data size for aborts

---

.github/workflows/wdio-single-browser.yml
tools/wdio/args.mjs
tools/wdio/config/lambdatest.conf.mjs
tools/wdio/runner.mjs

---
Defaulting wdio to run against LambdaTest while still supporting SauceLabs with a cli flag.
https://new-relic.atlassian.net/browse/NR-254321

chore: default tests to lambdatest

---

.github/workflows/wdio-all-browsers.yml
.github/workflows/wdio-single-browser.yml
tools/wdio/config/lambdatest.conf.mjs

---
Webview tests has also been limited to android & ios latest only.
* LT has connection issues with ios 16.0 on these tests
* Android 9 is not supported -- only 11 & 14 (at this point in time, could change?)
* Android web automation device list is not applicable to app automation as the capabilities array differs
* Atm, these tests only pass with plugin tunnel (enabling `-T` flag), not with underpass application for local dev ([slack thread](https://newrelic-external.slack.com/archives/C0749JVME86/p1718904970442849?thread_ts=1718733672.426799&cid=C0749JVME86))
https://new-relic.atlassian.net/browse/NR-280345
Run PR checks

chore: Add app automation for webview tests

---

src/common/wrap/wrap-function.js
src/common/wrap/wrap-logger.js
tests/assets/logs-api-wrap-logger-rewrapped.html
tests/components/logging/instrument.test.js
tests/specs/logging/harvesting.e2e.js

Adding a fix after observing an issue internally where re-wrapping a logging function after the agent has already wrapped it will break the scoped context.
---
A new test has been added to confirm this behavior

chore: Enforce no re-wrapping with log wrappers

---

src/features/spa/aggregate/index.js

Patch cases wherein SPA `.end()` can throw exception on a finished or full interaction. `.end` still force finishes an interaction.
---
SPA node `.child` function can return a null value if the interaction is already finished or if there are 128+ children nodes. This caused a chained `finish()` call on it to throw in  `.end` of API. This has been fixed via optional chaining which has minimal impact on the functionality of `.end` aside from not adding a customEnd node to the ixn.
https://new-relic.atlassian.net/browse/NR-268147

fix: Reading finish of null in SPA

---

src/features/utils/__mocks__/agent-session.js
src/features/utils/__mocks__/feature-base.js
src/features/utils/aggregate-base.js
src/features/utils/instrument-base.js
tests/specs/npm/index.e2e.js
tools/testing-server/plugins/test-handle/index.js
tools/wdio/plugins/custom-commands.mjs

Fixing an issue where an unhandled promise rejection could be thrown from the agent when using the npm package if the session manager async chunk get blocked or fails to setup a session.
---
If the session manager chunk is blocked, the agent was throwing an unhandled promise rejection error and the agent was failing to harvest a lot of other data. To fix the issue, a check has been added to prevent the session trace aggregate `initialize` function from running.
This issue could also happen if the session entity or the session initialization code threw an exception. I have added an `ierr` for those scenarios so we and customers can get better clarity on if/when/why the session manager is failing.
https://new-relic.atlassian.net/browse/NR-281861
#1075
To test locally, use the …

fix: Unhandled promise rejection for session import

---

src/features/session_replay/instrument/index.js
src/features/session_replay/shared/__mocks__/utils.js
src/features/session_replay/shared/utils.js
src/features/utils/instrument-base.js
tests/specs/session-replay/mode.e2e.js
tests/specs/session-replay/session-pages.e2e.js
tests/specs/session-replay/sr-api.e2e.js
tests/unit/features/session_replay/shared/utils.test.js

Patch a case of recordReplay not restarting session replay. Customers can now programatically continue the session replay after a hard page navigation.
---
Change old smart-attempt logic to exclude SR agg from loading if existing session mode is off to always load as long as session entity itself was initialized and exists. This ensure the aggregate is around to listen for recordReplay calls which forces the start of replay regardless of existing session mode being off (as long as entitlements are valid).
https://new-relic.atlassian.net/browse/NR-285311
Run new test file w/ old build; new test will fail with mode still being 0. Run it with PR build, new test passes with mode 1.

fix: recordReplay will restart replays on same session page loads

---

tests/specs/api.e2e.js
tests/specs/csp.e2e.js
tools/browsers-lists/lt-desktop-latest-vers.json
tools/browsers-lists/lt-mobile-supported.json
tools/browsers-lists/lt-update-supported.mjs
tools/testing-server/constants.js
tools/testing-server/index.js
tools/testing-server/network-capture.js
tools/testing-server/plugins/test-handle/index.js
tools/testing-server/routes/bam-apis.js
tools/testing-server/routes/command-apis.js
tools/testing-server/test-handle.js
tools/wdio/config/lambdatest.conf.mjs
tools/wdio/plugins/testing-server/network-capture-connector.mjs
tools/wdio/plugins/testing-server/test-handle-connector.mjs

---
Redesigned the network expects in our integration tests. Tests can now setup network captures before executing any browser commands. The network capture instances will capture all network traffic for the specific test allowing us to verify how many times a BAM api is called, check for calls to BAM apis happened, and wait for BAM api calls to happen. This resolves the race condition we were seeing with the existing network expects logic and ensures the capture is setup prior to loading the test page.
https://new-relic.atlassian.net/browse/NR-283311
Two spec files have been updated in this PR to use the new network capture feature in place of the old network expect. You …

chore: redesign network expects

---

src/loaders/api/api.js

Adding a safeguard to prevent an exception from being thrown when browser agent APIs are called before the agent is fully initialized.
---
Adding a safeguard to prevent an exception from being thrown when browser agent APIs are called before the agent is fully initialized.
https://new-relic.atlassian.net/browse/NR-276448
#1057 
The issue cannot be reproduced.

fix: safeguard api calls

---

src/features/session_trace/aggregate/index.js

Fixed an issue where session trace stopping on one tab while the same site was opening in another tab could result in the second tab throwing an exception when attempting to call `stopTimer()` on an undefined harvest scheduler.
---
Calls to `stopTimer`  from the `SESSION_EVENTS.UPDATE` ee event could result in attempting to call `stopTimer` on an undefined harvest scheduler. Added an optional chaining to the call.
https://new-relic.atlassian.net/browse/NR-286373
#1095

fix: address call to stopTimer on undefined scheduler

---

src/common/drain/drain.js
tests/specs/cleanup-on-halt.e2e.js
tests/specs/harvesting/disable-harvesting.e2e.js
tests/specs/session-replay/initialization.e2e.js
tests/specs/session-replay/session-state.e2e.js
tests/specs/session-trace/trace-nodes.e2e.js
tests/specs/soft_navigations/integration.e2e.js
tests/unit/common/drain/drain.test.js

Plug a memory leak in Session Trace and other features. When entitlement or enable flag from RUM request returns a 0 for a feature, the agent will now release the reference to the events buffer under that feature so it can be garbage collected.
---
The pre-load cycle of the agent sets up listeners and buffers events in a backlog and an internal handlers object to be flushed and processed after the page loads. It was discovered that if the RUM call getting made post-load returns a `0` for an applicable feature, those things are never cleared for such feature. This caused the backlog for instance to indefinitely hold onto events awaiting processing, consuming memory. This fix will flush those events in such cases when the features are not activated via the `deregisterDrain` call made by …

fix: Release backlog memory when features are blocked by RUM

---

tests/specs/err/attributes.e2e.js
tests/specs/err/bucketing.e2e.js
tests/specs/err/circular.e2e.js
tests/specs/err/custom-handler.e2e.js
tests/specs/err/error-payload.e2e.js
tests/specs/err/index.e2e.js
tests/specs/err/retry-harvesting.e2e.js
tests/specs/err/scripts-and-callbacks.e2e.js

---
Migrating the e2e tests in `tests/specs/err` to use the network capturing functionality.
https://new-relic.atlassian.net/browse/NR-287578

chore: migrate err e2e tests to network capture

---

tools/browser-matcher/matcher-rule.mjs
tools/wdio/config/lambdatest.conf.mjs
tools/webpack/env.mjs
tools/webpack/loaders/istanbul/index.mjs

---
This removes the old `import ... assert ...` keyword usage in favor of `require`. The `assert` keyword was added in [Node 16](https://nodejs.org/docs/latest-v16.x/api/esm.html#json-modules) but the keyword was changed in [Node 18](https://nodejs.org/docs/latest-v18.x/api/esm.html#import-attributes) to `with`. The `assert` keyword for imports was removed in Node 22 causing builds of our project to fail when running with Node 22.
The replacement implementation creates a `require` function using `module.createRequire(import.meta.url)`. This is supported all the way back to Node 12 and is not marked `experimental` in any way within the Node docs. This should be a stable …

chore: remove old assert import keyword

---

docs/warning-codes.md
src/common/drain/drain.js
src/common/util/console.js
src/features/page_view_event/aggregate/index.js
src/features/utils/aggregate-base.js
tests/assets/no-app-id-after.html
tests/assets/no-app-id-before.html
tests/assets/no-license-key-after.html
tests/assets/no-license-key-before.html
tests/components/api.test.js
tests/components/page_view_timing/index.test.js
tests/specs/harvesting/disable-harvesting.e2e.js
tests/unit/common/util/console.test.js
tests/unit/features/utils/aggregate-base.test.js

Shut down initialization of the agent if improperly configured. Agents must be provided a valid licenseKey and applicationID at runtime.
---
Shut down the agent with a new warning code if invalid licenseKey or App ID are provided.  Also fixed an issue where the warning code did not link correctly.
NR-257211
Tests have been updated to reflect the new behavior

feat: Shut down agent if improperly configured

---

docs/supportability-metrics.md
src/features/metrics/aggregate/index.js
tests/assets/video-player.html

Adds a SM tracking when `<video>` elements are seen, combining those observed at window load time with a DOM query with those subsequently observed with a mutation observer
---
NR-293248

chore: add video sm

---

docs/supportability-metrics.md
src/common/timing/time-keeper.js
src/features/page_view_event/aggregate/index.js
tests/specs/nr-server-time.e2e.js
tools/wdio/plugins/custom-commands.mjs

Shut down the agent when unable to read a correctly formatted date header for the page view event harvest. This prevents harvesting data with wildly inaccurate timestamps. This should only happen with third-party or non-agent code has tampered with the ajax response headers.
---
Adding supportability metrics to track when the calculated time diff is >= 12 hours, >= 6 hours, or >= 1 hour.
https://new-relic.atlassian.net/browse/NR-295258
https://source.datanerd.us/agents/angler/pull/600

fix: Prevent agent using invalid date header

---

docs/supportability-metrics.md
src/features/page_view_event/aggregate/index.js
tests/specs/nr-server-time.e2e.js

---
Removing the NRTime supportability metrics that are no longer needed and/or could not be harvested when the agent shuts down.

chore: Remove NRTime SMs

---

tests/specs/rum/index.e2e.js
tests/specs/rum/retry-harvesting.e2e.js
tests/specs/rum/under-session.e2e.js

---
Migrating the rum spec tests to use network capturing instead of network expects.
https://new-relic.atlassian.net/browse/NR-287587

chore: Migrating rum specs to use network capture

---

src/loaders/agent-base.js

Fix an issue where the logging API method would always result in an uninitialized agent warning and would not capture the log.
---
When configuring and using the new Logging feature it always warns that it's not initialized. I am able to get it to work if I change logInfo to log.
[](https://github.com/newrelic/newrelic-browser-agent/issues/1146)
Tested it locally and now I am seeing logging in my NR dashboard

fix: Updated Logging API function

---

tests/specs/third-party-compatibility/jspdf.e2e.js
tests/specs/third-party-compatibility/mootools.e2e.js
tests/specs/third-party-compatibility/run-test.js

---
Migrating the third party spec tests to use network capturing instead of network expects.
https://new-relic.atlassian.net/browse/NR-287596

chore: migrate third party specs to network capture

---

.github/workflows/wdio-all-browsers.yml
.github/workflows/wdio-single-browser.yml
test.sh
tests/specs/graphql-metadata.e2e.js
tests/specs/loaders.e2e.js
tests/specs/metrics.e2e.js
tests/specs/proxy.e2e.js
tests/specs/session-manager.e2e.js
tests/specs/stack-trace.e2e.js
tests/specs/web-worker-scope.e2e.js
tests/util/basic-checks.js
tools/wdio/config/lambdatest.conf.mjs

---
Migrate `specs/*.e2e.js` specs to use network capture.
https://new-relic.atlassian.net/browse/NR-287597

chore: migrate specs to use network capture

---

src/features/session_replay/shared/recorder.js

Decrease the time spent waiting by triggering Session Replay mutation observer wrapping on the DOMContentLoaded event instead of the previously used window load event. This ensures wrapping is completed before the load chain.
---
NR-300929

feat: Configure Session Replay to wait for DOMContentLoaded

---

.eslintrc.js
src/common/drain/drain.js
src/common/util/console.js
tests/unit/common/drain/drain.test.js

Ensure that the drain target is a valid event emitter to ensure that the `.on` method exists and will not throw errors.
---
https://newrelic.slack.com/archives/C0193KAHHAS/p1724879485394419
New unit test has been added to validate the behavior

fix: Ensure drain target is a valid event emitter before subscribing

---

src/features/metrics/aggregate/index.js
src/features/metrics/constants.js
src/features/metrics/instrument/index.js
tests/specs/websockets/metrics.e2e.js

Fix websocket problems and breakage in application using other third party libraries dealing with sockets by removing the wrapping introduced in version 1.265.0.
---
Removing websocket wrapping for now to resolve integration issues (incomplete interface or bad wrapping) in 1.265.0.
https://new-relic.atlassian.net/browse/NR-310559

fix: Disable websocket wrapping

---

src/features/utils/event-buffer.js

Removed a nullish coalescing assignment in a class getter -- which even though is claimed to be supported -- behaved badly in old versions of webkit browsers like Safari 15, some versions of Mobile Safari, and old chromium iOS browsers that use webkit.
---
Changed statement in `EventBuffer.js` class
https://new-relic.atlassian.net/browse/NR-312050
Fixes #1174 
Validated manually using LambdaTest with browser outside of supported table.  Ideally, tested using an experiment build and affected customer(s)

fix: Remove nullish coalescing inside getter

---

package.json
src/loaders/browser-agent.js
tests/unit/loaders/browser-agent.test.js

Add the Soft Navigations limited preview feature to the default `Browser Agent` loader accessible via NPM.
---
https://new-relic.atlassian.net/browse/NR-305645

feat: add soft navigations to Browser-Agent loader

---

docs/supportability-metrics.md
src/common/config/init.js
src/features/session_replay/aggregate/index.js
src/features/session_replay/shared/recorder.js
src/features/session_replay/shared/stylesheet-evaluator.js
tests/specs/session-replay/rrweb-configuration.e2e.js
tests/unit/common/config/init.test.js

The agent reports internal metadata about the status of stylesheets on the page when collecting session replay information. This process was spotty and the logic has been improved to make the metadata more consistent.  The ability to turn off "inlining" the stylesheets has been removed, as that behavior is required for the UI to re-render the replay.
---
* `inline_stylesheets` has been removed and all dependencies of that config have been updated/removed
* `fix_stylesheets` now solely depends on the config, or the status of the stylesheetEvaluator module.
* the stylesheetEvaluator has been updated to run more performantly in a way that will also let the agent decorate the `inlinedAllStylesheets` flag more consistently
NR-305647
Please review [this Angler …

feat: Improve notifications of stylesheet status for session replay

---

package-lock.json
package.json
src/common/vitals/interaction-to-next-paint.js
src/common/vitals/largest-contentful-paint.js
tests/unit/common/vitals/interaction-to-next-paint.test.js
tests/unit/common/vitals/largest-contentful-paint.test.js

Upgrade to web-vitals v4.  For more info, please see https://github.com/GoogleChrome/web-vitals/blob/main/docs/upgrading-to-v4.md.
---
In this PR, we are upgrading to current latest web-vitals lib (v4.2.3) following the web-vitals upgrade [doc](https://github.com/GoogleChrome/web-vitals/blob/main/docs/upgrading-to-v4.md).
Notable changes:
**INP**
- `eventType` is renamed to `interactionType` to avoid keyword conflict within NR
- Add `interaction*` equivalents for other `event*` attrs in use
- `event*` attrs are preserved for backwards compatibility to be EOL'd at a later time
**LCP**
- Add `resourceLoadTime` as replacement for `resourceLoadDuration`
- `resourceLoadDuration` is preserved for backwards compatibility to be EOL'd at a later time …

feat: Upgrade to web-vitals v4

---

docs/warning-codes.md
src/common/util/stringify.js
src/features/utils/event-buffer.js
tests/unit/common/util/stringify.test.js
tests/unit/features/utils/event-buffer.test.js

An internal mechanism used to convert objects to strings would return undefined if an exception was thrown during the process. This could lead downstream users of that method to throw errors if they expected the output to be a string. The utility method now always returns a string.
---
This utility method now always returns a string, empty if failed, and the string output of the object if successful. 
NR-316691
Existing tests should continue to pass.  A new unit test is added to check for exception value.

fix: Stringify now returns an empty string if failed to transform

---

src/features/session_replay/aggregate/index.js
src/features/session_replay/shared/recorder.js

The customMasker method of the Session Replay feature has been fixed to be more reliable with DOM elements that do not fit web-standards, as to not throw errors when processing.  Initial Replay harvests will now be gated until a valid snapshot is taken.
---
This PR has been named the way it has to encapsulate SR bug fix changes that span across this PR and some that were rolled into #1190.  It has been named this way to aid with the release notes.
https://new-relic.atlassian.net/browse/NR-314446
Tests should continue to pass

fix: Improve reliability of customMasker

---

src/features/generic_events/aggregate/index.js

Fixed an issue where the generic events buffer was not clearing when unloading. This affected a small portion of experiences where the agent was "unloading" due to the page losing focus, but not actually closing.  Subsequent harvests when the page was re-focused would have the potential for duplicated data.
---
NR-319565
Existing tests should continue to pass

fix: Force generic events feature to clear buffer when unloading

---

src/features/session_replay/aggregate/index.js
src/features/session_trace/aggregate/index.js
tests/specs/session-replay/payload.e2e.js
tests/specs/session-trace/payload-metadata.e2e.js
tests/specs/util/helpers.js

To aid with troubleshooting Session Replay and Session Trace, page url will be included in the respective payload's query string under `attributes.pageUrl`.
---
In this PR, we are adding the page URL to the query string of the corresponding Session Replay and Session Trace payloads under `attributes.pageUrl`.  The page URL will be added last, so if the total payload size exceeds current limit (5000), then truncation may occur.
https://new-relic.atlassian.net/browse/NR-268394
- Added a test condition to the Session Replay standard payload unit test
- Manually tested and confirmed presence of URL in payload:
Session Replay
(screenshot - to be added)
Session Trace
(screenshot - to be added)

chore: Add page url to Session Replay and Session Trace payloads

---

README.md
src/features/spa/instrument/index.js
src/loaders/agent-base.js

Added documentation to readme, typings, and JSDOC in the agent source code to document the deprecation of the SPA v1 feature and the `createTracer` API tied to it.
---
NR-224097
Tests should be unaffected

chore: Add createTracer and SPA deprecation notices to browser agent

---

docs/supportability-metrics.md
src/features/jserrors/aggregate/index.js
src/features/jserrors/aggregate/internal-errors.js
tests/specs/err/error-payload.e2e.js
tests/unit/features/jserrors/aggregate/internal-errors.test.js

Handle Security Policy Errors encountered by session replay when browser APIs have been natively disabled.  This was also observed to happen in Chromium browsers that completely disabled cookie storage.  Supportability metrics about agent internal errors are now captured as a biproduct of this work to help facilitate future improvements.
---
All errors thrown from either the `rrweb` library directly or the wrapping `nr-recorder` module will be handled through the new internal handler.
All instances of internal errors will now generate a supportability metric instead of an unused `ierr` harvest.  There are a few basic categories added as part of this pr.  More categories can be added later as needs arise
NR-316093
Tests have been updated to evaluate the new behavior

fix: Handle Session Replay Security Policy Errors

---

src/features/jserrors/aggregate/internal-errors.js
tests/unit/features/jserrors/aggregate/internal-errors.test.js

Fix a test that was missed and caught by the nightly test runner.  The test stopped working with the addition of the internal errors evaluator, specifically if a circular error passed through the evaluator where a string check was made when there is no string type message.
---

chore: fix circular error in handler

---

src/features/generic_events/aggregate/index.js
src/features/generic_events/instrument/index.js
src/features/jserrors/aggregate/index.js
src/features/metrics/aggregate/index.js
src/features/session_replay/aggregate/index.js
src/features/session_trace/aggregate/index.js
src/features/session_trace/instrument/index.js
src/features/soft_navigations/aggregate/index.js
src/features/spa/aggregate/index.js
src/features/utils/aggregate-base.js
src/features/utils/feature-base.js

Moves the `deregisterDrain` method in order to standardize the implementation pattern to match the drain method.
---
Moves the `deregisterDrain` method in order to standardize the implementation pattern to match the drain method. Aggregate and instrument features should now use `this.deregisterDrain()` instead of importing the method itself. This is done to make it easier to call the `deregisterDrain` method regardless of feature in a consistent manner like the `drain` method (which currently only works for aggregate methods).
https://new-relic.atlassian.net/browse/NR-297543
Make sure tests pass. The agent needs to function identically to before.

feat: Move deregisterDrain method to feature-base

---

src/common/harvest/harvest-scheduler.js
src/common/unload/eol.js
src/features/page_view_timing/aggregate/index.js
tests/unit/common/harvest/harvest-scheduler.test.js

Remove `pageHide` from page end-of-lifecycle listener since browser agent support for Safari 14.4 is deprecated
---
Previously in support of Safari 14.4, we had retained the subscription to `pageHide` event for detecting when a page is entering a hidden state.  Safari 14.4 has now aged out of our current supported versions, so we are removing the `pageHide` logic.  Page unloads should now be detected via `visibilitychange` events across all supported browsers.
[NR-292875](https://new-relic.atlassian.net/browse/NR-292875)
Ran `final-harvesting.e2e.js` to ensure tests are passing
Run pull-request-checks on PR branch to ensure everything still passes <-- ISSUES FOUND (TODO)
[NR-292875]: https://new-relic.atlassian.net/browse/NR-292875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

feat: Remove 'pageHide' from page end-of-lifecycle listener

---

tools/browser-matcher/common-matchers.mjs

Add Firefox versions 122 and above to LCP test matcher since versions 122 and above now support collection of LCP web vital timings.
---
Add Firefox versions 122 and above to LCP test matcher since versions 122 and above now support collection of LCP web vital timings. CLS matcher now uses a separate SpecMatcher object.
These changes are needed to keep test consistency with browser additions and features. Web standards change constantly on what browsers support what standard and we need to keep up to date on them.
https://new-relic.atlassian.net/browse/NR-328547
Make sure tests pass. Check that Firefox 122+ is additionally tested for:
- LCP is not collected on hidden pages for rum agent
- LCP is not collected on hidden pages for spa agent

feat: Add Firefox to LCP test matcher

---

src/common/constants/__mocks__/runtime.js
src/common/constants/runtime.js
src/common/util/submit-data.js
tests/unit/common/constants/runtime.test.js
tests/unit/common/util/submit-data.test.js

Removes the supportsSendBeacon runtime property from our agent code. We no longer officially support browsers that cannot use the sendBeacon method, so there's no point in checking for it.
---
Removes the supportsSendBeacon runtime property from our agent code. This is done to tidy up the agent code and shorten the agent payload size a little bit.
https://new-relic.atlassian.net/browse/NR-259634
Make sure tests pass.

feat: Remove supportsSendBeacon runtime property

---

src/features/session_trace/aggregate/trace/storage.js
tests/components/session_trace/aggregate.test.js

Remove an outdated reference to `agentRuntime` variable in the Trace feature released in 1.270.0. It caused undefined errors in sub-cases wherein max harvest nodes were reached.
---
The if-check causing the undefined error has been changed to checking the mode on the feature instance instead of the runtime session reference, as this makes more sense. By effect, this also remove & fixes the problem in 1.270.0
https://new-relic.atlassian.net/browse/NR-331791
Jest test added that would detect issue with storeSTN logic, and the problematic check by extension.

fix: Remove undefined agentRuntime in Session Trace

---

src/common/config/runtime.js
src/features/logging/shared/log.js
src/features/spa/aggregate/index.js
src/features/spa/aggregate/interaction.js
tests/components/logging/aggregate.test.js

Corrects naming for the Logging pageUrl attribute by using the original url of the page instead of the url of when the event happens. Removes origin attribute from the runtime model object.
---
Corrects the naming for the Logging `pageUrl` attribute by using the original url of the page instead of the url of when the event happens. The original url of the page is also referred to as `initialLocation`. A test has been added to check that the `pageUrl` attribute in the Log object is `initialLocation`.
Removes origin attribute from the runtime model object by cleaning up usage of `runtime.origin` in spa feature. The `initialLocation` constant is a direct replacement for it.
These changes are for cleaning up the agent code.
https://new-relic.atlassian.net/browse/NR-320541
Make sure tests …

fix: Correct naming for logging pageUrl attribute

---

src/features/utils/instrument-base.js

Lazy loaded modules that are blocked from loading by third party tools such as adblocking mechanisms will issue a warning to console instead of throwing an error.
---
NR-335501

fix: Ensure all lazy loaded modules issue warning instead of errors

---

src/features/jserrors/shared/cast-error.js
tests/assets/unhandled-promise-rejection-falsy-reason.html
tests/assets/unhandled-promise-rejection-readable.html
tests/specs/err/scripts-and-callbacks.e2e.js
tests/unit/features/jserrors/shared/cast-error.test.js

The agent will not report unhandled promise rejections that lack a reason property as they cannot generate sufficient stack trace or messaging information for debugging.
---
NR-329400
New tests have been added to validate the behavior

feat: Ignore unhandled promise rejections that lack a valid reason

---

src/features/soft_navigations/instrument/index.js
tests/assets/soft-nav-interaction-on-click.html

Remove wrap-events module from usage for soft navigation feature. This is part of an effort to cleanup code in the agent.
---
Remove wrap-events module from usage for soft navigation feature. This is part of an effort to cleanup code in the agent.
I also added the "soft_nav" feature flag to the `soft-nav-interaction-on-click.html` asset file. I want to be sure it's testing the soft_nav feature there.
https://new-relic.atlassian.net/browse/NR-250813
Make sure tests pass.

feat: Remove wrap-events usage from soft nav

---

src/features/logging/aggregate/index.js
src/features/logging/constants.js
tests/components/logging/aggregate.test.js
tests/specs/cleanup-on-halt.e2e.js
tests/specs/harvesting/disable-harvesting.e2e.js
tests/specs/logging/harvesting.e2e.js
tools/testing-server/constants.js

Aggregate logging events according to the `log` flag received from rum call to BCS.
---
Part 2 of the auto-logging feature work. This work will enable the logging feature to be controlled via BCS, which is ultimately based on user settings from UI (on/off, sampling, log level).
https://new-relic.atlassian.net/browse/NR-323597
Extended existing logging aggregate unit and e2e tests around handling the flag.  Includes tests for each logging mode to ensure log messages of equal or higher levels are collected.  For example, if the `log` flag = 3 (INFO), then collect `console.error`, `console.warn`, `console.info`, and `console.log` events.
Extended existing tests to ensure no harvests when rum flag = 0 and events are drained.

feat: Aggregate log events based on rum flag

---

package-lock.json
package.json
src/features/session_replay/shared/recorder.js
tests/specs/err/error-payload.e2e.js

Upgrade underlying session replay libraries to latest version which addresses some known bugs. This change also removes the error swallower inside the session replay module and instead handles all session replay errors at the window level to allow for external libraries to observe known errors to induce fallback behaviors, such as those implemented in CSS-as-JS libraries.
---

feat: Upgrade SessionReplay libraries to latest version

---

.github/actions/build-ab/templates/released.js
src/features/generic_events/aggregate/index.js
tests/components/generic_events/aggregate/index.test.js
tests/specs/ins/harvesting.e2e.js

To avoid behavior that could lead to more network requests than necessary, generic events will now harvest early only if the max payload size is reached. This represents an increase from 64kb to 1MB.
---

fix: Harvest generic events when max size is reached

---

tests/specs/util/helpers.js
tools/testing-server/plugins/agent-injector/debug-shim.js

The current logging shim output of the test server alters Ajax and resource payloads when enabled because it generates network requests to capture the log messages. This change introduces a global array that intercepts and stores log messages in it that can be fetched on the fly with a browser execute statement. 
---
An example of how to use this would be something like:
1. *anywhere* in your test add the included helper method
- `console.log(await getDebugLogs())`
This will return the current state of the log message buffer.  Anytime something like `console.log` is called in the test execution step (client side), the log buffer will be populated with the contents.  You must start the test server with the `-d` flag as before for the shim to be injected into the page.

chore: improve testing server debug shim

---

src/common/session/session-entity.js
src/features/logging/aggregate/index.js
src/features/session_replay/aggregate/index.js
src/features/utils/aggregate-base.js
src/features/utils/instrument-base.js
tests/components/session-entity.test.js
tests/components/session-helpers.js
tests/specs/harvesting/disable-harvesting.e2e.js
tests/specs/harvesting/index.e2e.js
tests/specs/logging/harvesting.e2e.js
tests/specs/logging/session-pages.e2e.js
tests/specs/npm/micro-agent.e2e.js
tests/specs/session-manager.e2e.js
tests/specs/util/helpers.js
tools/wdio/plugins/custom-commands.mjs

This is another part of the work for the auto-logging feature.  The auto-logging mode should stay consistent within a given session and will auto-disable upon session expiration after 4 hours or session inactivity after 30 minutes.
---
The auto-logging mode should stay consistent within a given [session](https://docs.newrelic.com/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking/) and will auto-disable upon session expiration after 4 hours or session inactivity after 30 minutes.
If cookies are not enabled, then the logging mode for each page will be set independently based on the rum response.
https://new-relic.atlassian.net/browse/NR-341932
Added/updated relevant tests for logging with regards to session

feat: Persist logging flag in session

---

src/common/wrap/wrap-logger.js
tests/assets/logs-api-wrap-logger-rewrapped.html
tests/components/logging/instrument.test.js
tests/specs/logging/harvesting.e2e.js

This will support the rollout of the auto-logging feature without disrupting customers that may currently be using `wrapLogger` to wrap the `console` object.
---
Currently, once an object's method is wrapped, it is blocked from being re-wrapped.  With the auto-logging feature, the browser agent's internal wrapping for `console` will be triggered before any other wrappers that may be invoked via `wrapLogger`.  This creates a small potential change in behavior if customers are already using `wrapLogger` to wrap the `console` object. 
So the logging context is now modifiable, such that log api wrappers can overwrite the custom attributes sent along with the log events.  For a given wrapped method, attributes supplied by the last wrapper will "win". …

feat: Allow logs api wrapper to update custom attributes

---

src/features/ajax/instrument/index.js

A syntax error was introduced that would cause xhr readystate fallback checks to always capture.
---
Contributor @steve-cunnew found an issue in the code base where a typo was introduced.  This likely was not noticed because it was nearly always truthy, leading to expected behavior. This affects an edge case.
https://newrelic.slack.com/archives/C0193KAHHAS/p1733483033474939
Tests should continue to pass

fix: Fix syntax error in fallback when tracking xhr readyState

---

src/features/generic_events/aggregate/index.js
tests/assets/user-actions-modified-window.html
tests/specs/ins/harvesting.e2e.js

Force the agent to not capture target-level attributes for window-level UserActions. Customers can set window-level variables that mimic HTML element attributes like type or tagName. This change prevents the potential capture of those attributes as part of blur or focus user actions tied to the window.
---

fix: Ignore reserved attribute names on UserActions tied to the window

---

tests/specs/spa/harvesting.e2e.js
tools/wdio/plugins/browser-matcher.mjs
tools/wdio/plugins/testing-server/launcher.mjs

Added a matcher method to skip tests or entire test suites when collecting coverage with istanbul.  Istanbul has shown to cause issues with specific SPA tests.  Now you can skip tests when collecting coverage by including the method `withoutCoverage()` on `describe` blocks and `it` calls.
---
NR-315950

chore: create test matcher that can skip test suites with coverage

---

.github/workflows/branch-cleanup.yml
.github/workflows/delete-experiment.yml

GitHub Actions require the `actions/checkout` package in order for workflows to run.
---
In this PR, include the following missing dependencies that are required for the `delete-experiment` and `branch-cleanup` actions to run:
- `actions/checkout` - always required essentially
- `actions/setup-node` - since our actions will require `node` to run
https://new-relic.atlassian.net/browse/NR-347721
Replicated workflow in a private repo and successfully tested:
**Delete Experiment**
```
Prepare all required actions
Run ./.github/actions/s3-delete
Run npm install --prefix $GITHUB_ACTION_PATH/..
npm warn deprecated formidable@1.[2](https://github.com/ptang-nr/test-browser-app/actions/runs/12484778541/job/34842658805#step:5:2).6: Please upgrade to latest, formidable@v2 or formidable@v3! Check …
```

chore: Add missing GHA deps

---

src/common/harvest/harvester.js
src/features/metrics/aggregate/index.js
src/features/utils/aggregate-base.js
tests/components/metrics/aggregate.test.js
tests/components/setup-agent.js

Prevent Metrics feature from harvesting on interval after changes in v1.278.0. This reverts its behavior back to sending only final harvests.
---
https://new-relic.atlassian.net/browse/NR-356543
New component test added for this case

fix: Make Metrics harvest only on EoL for new Harvester

---

src/common/util/obfuscate.js
src/features/metrics/aggregate/index.js
src/features/utils/aggregate-base.js
tests/components/spa/serializer.test.js
tests/specs/metrics.e2e.js
tests/specs/obfuscate.e2e.js
tests/unit/common/util/obfuscate.test.js
tests/unit/features/soft_navigations/aggregate/initial-page-load-interaction.test.js
tests/unit/features/soft_navigations/aggregate/interaction.test.js

Fix an issue where obfuscation rules are not honored if added after the agent has initialized.  Some user cases require obfuscation rules to be dynamically added, this change will allow that behavior -- as long as the obfuscation rules are added to `newrelic.initializedAgents[index].init.obfuscate`
---
This is related to an ongoing incident
A new test has been added that validates that obfuscation rules can be added later and still affect outgoing payloads.

fix: Change obfuscator to read dynamically from configuration

---

src/common/harvest/harvester.js
tests/specs/ajax/retry-harvesting.e2e.js
tests/specs/err/retry-harvesting.e2e.js
tests/specs/ins/retry-harvesting.e2e.js
tests/specs/pvt/retry-harvesting.e2e.js
tests/specs/session-trace/retry-harvesting.e2e.js
tests/specs/soft_navigations/retry-harvesting.e2e.js
tests/specs/spa/retry-harvesting.e2e.js

Agent will begin to retry harvests to the endpoints that failed for the following additional status codes: 502, 504, and 512-530. This is suggested by New Relic ingest teams as a possibility to recapture lost data in these marginal cases.
---
Harvester now will attempt to retry the following codes in total: 408, 429, 500, 502-504, 512-530.
Metrics track if a former failed attempt subsequently succeeded or failed on next attempt, split by the former returned HTTP code.
https://new-relic.atlassian.net/browse/NR-137499
Angler update: https://source.datanerd.us/agents/angler/pull/657
Retry e2es were updated. New SMs are tested in the PVT retry spec file (only).

feat: Add HTTP codes for harvest retry attempts

---

src/common/config/init.js
src/features/generic_events/aggregate/index.js
tests/assets/marks-and-measures-detail.html
tests/components/generic_events/aggregate/index.test.js
tests/specs/ins/harvesting.e2e.js
tests/unit/common/config/init.test.js

The `detail` property of `PerformanceMark` and `PerformanceMeasure` events will now be captured in New Relic `BrowserPerformance` under the `entryDetail` attribute.  If `detail` is an object, it and any nested objects within it will be flatten into string path keys prefixed with `entryDetail`. See [the PR](https://github.com/newrelic/newrelic-browser-agent/pull/1332) for elucidation.
---
This PR is to support changes requested by the platform team to be utilized in conjunction with MFE POC.
Flattening examples:
- `detail: { foo: { bar: 'baz' }, other: 'hello' }` will create an attribute on the BrowserPerformance event called `entryDetail.foo.bar: 'baz'` and another attribute called `entryDetail.other: 'hello'`. 
- Other non-object data types provided to the `detail` option will be …

feat: Capture details in marks and measures

---

src/loaders/agent.js
src/loaders/micro-agent-base.js
src/loaders/micro-agent.js

Removes the agentIdentifier argument from the Agent and MicroAgent class constructors. The agentIdentifier should always be a random hex string to guarantee uniqueness across agent instances.
---
The agentIdentifier argument was removed from the Agent and MicroAgent constructors. This excludes the feature classes which need the agentIdentifier passed in from the agent reference. There is no public documentation on setting the agentIdentifier manually as far as I'm aware.
https://new-relic.atlassian.net/browse/NR-352908
Make sure tests pass.

feat: Remove agentIdentifier argument from agent constructors

---

.github/actions/build-ab/templates/postamble.js

Please see this [thread](https://newrelic.slack.com/archives/G019T80B1EJ/p1738948320495519) for more context if needed
---
This POC will generate attributes `pressure` and `pressureImpact` on all data, and generate a new event `BrowserPressure` on each status change.  This is for validation purposes only and will be removed from postamble at a future time.

chore: add browser pressure poc to postamble script

---

src/common/wrap/wrap-function.js
src/common/wrap/wrap-websocket.js
src/features/metrics/aggregate/index.js
src/features/metrics/constants.js
src/features/metrics/instrument/index.js
tests/components/wrappings/wrap-websocket.test.js
tests/specs/websockets/metrics.e2e.js
tools/test-builds/library-wrapper/package.json
tools/test-builds/library-wrapper/src/reconnecting-websocket.js
tools/test-builds/library-wrapper/src/robust-websocket.js
tools/test-builds/library-wrapper/webpack.config.js

Re-implement wrap-websocket code using ES6 extends syntax into the agent. This will allow supportability metrics to be reportable from websocket API usage.
---
We're re-implementing the wrap-websocket code into the agent that was taken out in 1.265.1 patch to address deploy issues. The new implementation uses ES6 extends syntax to include static class constants and all the properties of the original WebSocket object. Tests are included that cover usage with the third-party libraries `robust-websocket` and `reconnecting-websocket`.
https://new-relic.atlassian.net/browse/NR-311646
Make sure tests pass.

feat: Re-implement wrap-websocket into agent

---

tests/specs/websockets/metrics.e2e.js

See [this slack thread](https://newrelic.slack.com/archives/G019T80B1EJ/p1739374405314629) for more context
---

chore: Exclude ios & safari from websocket metrics tests

---

src/features/metrics/aggregate/index.js
src/features/metrics/instrument/index.js
tests/specs/websockets/metrics.e2e.js

Removing websocket wrapping and metrics. WS instrumentation may be re-implemented behind a feature flag at a later time.
---
Post-discussion with team, we're removing ws wrapping again for now rather than introduce a FF system until a later time.
#1387

fix: Removing websocket wrapping & SM

---

src/features/session_replay/shared/stylesheet-evaluator.js
tests/unit/features/session_replay/shared/stylesheet-evaluator.test.js

Nullish values in the global `styleSheets` API can break implementations with the weakMap object tracking their status, throwing an error similar to `TypeError: Invalid value used in weak set at WeakSet.add...`.  This fix checks that the value is acceptable before adding.
---
There appears to be a TypeError in the browser agent https://staging.onenr.io/0gR7nN1OZwo. We should ensure the object is a CSSStyleSheet before adding it.

fix: Guard against non-CSSStyleSheet when fixing sheets for replay

---

src/features/jserrors/shared/cast-error.js
tests/unit/features/jserrors/shared/cast-error.test.js

Remove an issue that caused `Unhandled Promise Rejection:` prefixes on casted error messages to be duplicated if already supplied on rejection reason messages.
---
A new unit test was added to validate that prefixes are not duplicated

fix: Deduplicate Prefixes on Unhandled Promise Rejection Messages

---

src/features/ajax/instrument/index.js
tests/components/setup-agent.js

XHR headers will be checked for the deprecated New Relic CAT header before calling `getResponseHeader`, which throws a console error if it does not exist for cross-origin requests.
---
`getResponseHeader` behavior when dealing with a nonexistent header:
* It doesn’t show the error in console ("Refuse to get unsafe header") if the XHR is deemed same-origin (by browser). This only throws if it’s cross-origin request. If header DNE, it returns null.
* There is a test for “xhr_no_cat” that doesn’t return CAT header in response. But it doesn’t throw because it requests from the same origin [:3333]/xhr_no_cat as the test-server.
* Even if it requests from cross-origin (say, another port), it still won’t throw if it’s listed in `Access-Control-Expose-Headers` … which is the case for all response …

fix: Console error on some cross-origin requests without NR CAT header

---

src/features/logging/aggregate/index.js

Fixes a typo in the session update handler for logging feature. The `loggingMode` which controls feature output will be correctly set after its session mode value is updated from another tab or window.
---

fix: Logging mode on session update

---

src/features/session_replay/shared/recorder.js
src/features/session_replay/shared/utils.js
tests/specs/session-replay/rrweb-configuration.e2e.js
tests/unit/features/session_replay/shared/utils.test.js

There is an edge case where whitespace was being masked, which interferes with the layout/styling in session replays.
---
In this PR, we address the edge case by allowing the whitespace to return as-is when it's not a password field.
https://new-relic.atlassian.net/browse/NR-379491
Added unit test for `customMasker` function
Manually tested session replay on customer's site using rrweb REPL

fix: Session Replay text masking for whitespace

---

src/common/wrap/wrap-events.js
src/features/session_trace/aggregate/trace/storage.js
tests/assets/event-listener-mousemove.html
tests/specs/session-trace/trace-nodes.e2e.js

There may be an edge case where a site performance can be impacted if the browser agent picked up `mousemove` events via `addEventListener`.
---
In this PR, we are excluding `mousemove` events from SessionTrace instrumentation to reduce potential processing burden from high occurrences of said event.  
https://new-relic.atlassian.net/browse/NR-381325
- Manually tested via adding a event listener for the `mousemove` event and confirming the event has been ignored successfully.
- Added an e2e test to ensure no `mousing` event is detected for `mousemove` event

feat: Reduce noise from `mousemove` events

---

docs/warning-codes.md
src/features/session_replay/shared/recorder.js

Warn users if fix_stylesheet is off so that they can follow steps to ensure their replays don't get mangled.
---
https://new-relic.atlassian.net/browse/NR-317321

chore: Add warning if fix_stylesheet is off

---

src/features/utils/aggregate-base.js
src/features/utils/nr1-debugger.js
src/loaders/agent-base.js
src/loaders/agent.js
src/loaders/api/api.js
src/loaders/api/apiAsync.js
src/loaders/configure/configure.js
src/loaders/micro-agent-base.js
src/loaders/micro-agent.js
tests/components/api.test.js
tests/components/apiAsync.test.js
tests/components/page_view_timing/index.test.js
tests/unit/features/page_view_timing/aggregate/index.test.js
tests/unit/features/utils/aggregate-base.test.js
tests/unit/loaders/api/api.test.js

The `.api` property of full and micro agents have been removed. The browser API methods are instead moved to the agent instance itself for ease of targeted access. This includes a minor fix of runtime `loaderType` for agents that are re-configured after load.
---
Instead of:
```js
agent: {
features: ...,
info: ...,
api: {
setErrorHandler: () => {},
setAPI: () => {},
...
},
...
}
```
The API will now be:
```js
agent: {
features: ...,
info: ...,
setErrorHandler: () => {},
setAPI: () => {},
...
}
```
`mainOrMicroAgent.api.___` will still work as it will redirect up a level and call `mainOrMicroAgent.___`.
https://new-relic.atlassian.net/browse/NR-172955

feat: Erase .api property on agent instance

---

src/common/dispatch/global-event.js
src/common/harvest/harvester.js
src/common/util/feature-flags.js
src/features/utils/event-store-manager.js
src/loaders/api/api.js
src/loaders/configure/configure.js
tests/assets/event-listener-newrelic.html
tests/assets/inspection-events.html
tests/specs/api.e2e.js
tests/specs/rum/index.e2e.js

There is an edge case where if there is a listener on the `newrelic` event (as described in the install [docs](https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/#browser_delay)) and any API call is invoked inside this listener, it will trigger an infinite loop. 
---
In this PR, we are deprecating the `loaded` detail attribute and replacing it with `drained`.
CURRENT/EXISTING USAGE
```
window.addEventListener("newrelic", (evt) => {
if (evt.detail.loaded) {
// you can start using newrelic.interaction(), etc. now
}
});
```
TO-BE USAGE
```
window.addEventListener("newrelic", (evt) => {
if (evt.detail.drained && evt.name === 'load') {
// you can start using newrelic.interaction(), etc. now
}
});
``` …

fix: Patch `newrelic` event detail

---

tools/wdio/config/base.conf.mjs

Improves console reports for test results by only printing spec files containing test failures instead of all spec files.
---
This PR changes a config setting in the spec reporter called `onlyFailures`. When set to `true`, it only prints out spec reports for test files that have a failing test. It used to print every single spec file result at the end regardless of passing or failure which made it difficult to find the tests that failed. This change results in a lot less noise at the bottom of the console log which makes it easy now to find test failures.
JIRA: https://new-relic.atlassian.net/browse/NR-250731
Look at the console report at the end of testing. Should now only have test failures reported (if there are any). It will still show a count of how many tests failed/passed.

chore: Improve test result console report

---

src/features/logging/aggregate/index.js
tests/components/logging/aggregate.test.js

If the logging feature aborted before the agent had set up the event buffer, it could throw errors.  This was addressed by checking for the presence of the event buffer before running methods against it.
---
See customer thread here https://newrelic.slack.com/archives/G019T80B1EJ/p1744722309280769
A new unit test has been added that validates that calling `abort` while an event buffer does not exist will not throw errors

fix: Solve race condition in logging abort

---

.github/actions/build-ab/templates/released.js

This PR sets the harvest interval to 5 seconds `internally` in NR1 envs to see if product analytics issues decrease with a smaller event buffer.
---
https://new-relic.atlassian.net/browse/NR-403791?atlOrigin=eyJpIjoiN2U1NjRiZWM0YTYzNGQxNTgyMTM5ZjYzOGRhNDEyOWQiLCJwIjoiaiJ9

chore: decrease harvest interval to 5 to see if staging issues narrow

---

.github/actions/build-ab/templates/postamble.js

Adding some rudimentary automation and bot detection to dev and staging to prep for AI hackathon experiments
---
https://newrelic.slack.com/archives/C08FN66CX35/p1746197662375469
We should see attribution come up in staging data once merged to main (assuming we see non-human traffic hit dev/staging)

chore: AI hackathon prep

---

src/common/config/configurable.js
src/common/config/runtime.js
tests/unit/common/config/runtime.test.js

This PR updates the configure call to only warn if the attribute fails to exist.  In the off chance that `checkConfiguration` is called in the aggregate base and forces a re-configure, the `getter` used for `harvestCount` can be attempted to be overset and throw a console warning. This warning is misleading, as that getter does not cause issues and does in fact still exist. You can see this in action [here](https://docs.newrelic.com/). A new test has been added to ensure this case does not log a warning anymore.
---

chore: Do not warn unless config actually fails to exist

---

docs/warning-codes.md
src/loaders/api/addToTrace.js
tests/components/api.test.js

Events created with addToTrace API, which have an invalid UNIX timestamp, emit a warning and return without creating the event.
---
Added safeguards for `addToTrace()` API call. It was possible to have negative timestamps before with misuse. This PR does not create the event if the timestamps are negative. A warning is emitted of error code 61 if the timestamps are invalid.
At first I thought that the requirements were to only check that the arguments of the method are valid timestamps, but it makes more sense to me to check that the timestamps in the event creation are valid.
JIRA: https://new-relic.atlassian.net/browse/NR-366078
Make sure tests pass

fix: Add safeguards for addToTrace

---

src/features/generic_events/aggregate/index.js

The `entryName` attribute of resource type `BrowserPerformance` events will now have a cleaner URL, removing the hash fragment from reported URLs.
---
https://new-relic.atlassian.net/browse/NR-418312

fix: Clean BrowserPerformance entryName for resources

---

tests/specs/graphql-metadata.e2e.js
tools/test-builds/library-wrapper/src/apollo-client.js
tools/testing-server/routes/mock-apis.js

Point the graphql tests to our internal testing service with a new mocked endpoint instead of relying on a demo service, which has recently gone down and caused test failures.
---
`graphql-metadata.e2e.js` should now pass

chore: fix broken gql test service

---

src/common/drain/drain.js
src/common/window/load.js
src/features/page_view_event/instrument/index.js
tests/assets/inspection-events.html
tests/specs/inspection-events.e2e.js

Adds new inspection events to the agent. These events include the drain event, window lifecycle events such as navigate, load, DOMContentLoaded, and the session event which emits on changes to the agent's session state.
---
Adds new inspection events to the agent. These are new events not originally outlined in the CDD. The 'origin' event mentioned in the JIRA ticket is excluded due to too much code effort and not enough of a use case to have it.
drain event: Emits when the agent drains for a particular feature
```
{
agentIdentifier,
type: 'lifecycle',
name: 'drain',
feature: group
}
```
window lifecycle events:
```
{
timeStamp: evt.timeStamp,
loaded: evt.target.document.readyState === 'complete',
type: 'window',
name: 'navigate' | 'load' | 'DOMContentLoaded'
data: evt.target.location + …
```

feat: Add more inspection events

---

docs/warning-codes.md
src/loaders/api-base.js
src/loaders/api/finished.js
tests/assets/api/finished.html
tests/components/api.test.js
tests/specs/api.e2e.js

Fixes an issue where the `finished` api was creating a `timeSinceLoad` value for PageAction data as the unix timestamp instead of a relative time value in seconds from the page origin.
---
#1502 
Tests have been updated to check that page actions create the correct timeSincePageLoad values

fix: Fix .finished API timeSinceLoad value

---

src/features/soft_navigations/aggregate/initial-page-load-interaction.js
src/features/soft_navigations/aggregate/interaction.js
src/features/spa/aggregate/interaction.js
tests/specs/soft_navigations/payloads.e2e.js
tests/specs/spa/payloads.e2e.js
tests/specs/spa/zonejs.e2e.js
tests/unit/features/soft_navigations/aggregate/initial-page-load-interaction.test.js
tests/webview-specs/android/index.e2e.js
tests/webview-specs/ios/index.e2e.js

Update BrowserInteractions to use document.referrer for previousUrl values on initialPageLoad interactions instead of mirroring previousUrl and targetUrl. This enables better functionality for user journeys and provides more insight on page linkages.
---
Please review this attribute dictionary PR related to this PR https://source.datanerd.us/docs-eng/attribute-dictionary/pull/137
Original thread --> https://newrelic.slack.com/archives/C08235DFQU9/p1749246923068169
Tests have been updated to check that previousURL values are using the document referrer

feat: Update BrowserInteraction previousUrl definition

---

src/common/wrap/wrap-events.js
src/features/generic_events/aggregate/user-actions/interactive-elements.js
tests/components/wrappings/wrap-events.test.js
tests/unit/features/generic_events/aggregate/user-actions/interactive-elements.test.js

Extends `wrap-events` to track which buttons and links have click event handlers. 
---
This is a first step towards helping track dead clicks on interactive elements, which are mainly buttons and links at the moment. Any click event handlers added via `addEventListener` for buttons and links will be stored in a lookup, key = element reference, value = handler function reference.  The lookup can be used later on to verify if a user click is going to "do something" vs. is a dead click.
[NR-422169](https://new-relic.atlassian.net/browse/NR-422169)
- Added unit tests for InteractiveElements 
[NR-422169]: https://new-relic.atlassian.net/browse/NR-422169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Track click handlers of interactive elements

---

.github/workflows/publish-dev.yml
.github/workflows/pull-request-checks.yml

This PR removes the e2e coverage runners (but not the underlying mechanisms that support that behavior), which have been failing and not providing insight.  After some time allowing for evaluation, the underlying mechanisms needed for coverage tests should be removed.
---

chore: remove coverage runners

---

src/features/ajax/instrument/distributed-tracing.js
tests/specs/ajax/distributed-tracing.e2e.js

Addressed a bug where the agent was able to capture distributed traces, even when `distributed_tracing: false` was supplied in the configuration.
---
[NR-432936](https://new-relic.atlassian.net/browse/NR-432936)
New test has been added to ensure the `.disabled` field is checked
[NR-432936]: https://new-relic.atlassian.net/browse/NR-432936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Address issue keeping distributed traces from being disabled

---

src/features/jserrors/aggregate/cause-string.js
src/features/jserrors/aggregate/index.js
src/features/jserrors/shared/cast-error.js
tests/assets/js-error-cause.html
tests/specs/err/error-payload.e2e.js
tests/unit/features/jserrors/aggregate/cause-string.test.js
tests/unit/features/jserrors/shared/cast-error.test.js
tools/browser-matcher/common-matchers.mjs
tools/browsers-lists/lt-mobile-supported.json

Detect and report the cause attribute on captured JavaScriptError events.  If the cause is an instance of an Error, the stack trace will be captured, otherwise the stringified contents of the cause will be reported. This will be queryable in JavaScriptError events under the attribute `cause`.
---
https://new-relic.atlassian.net/browse/NR-414116?atlOrigin=eyJpIjoiODY2NDUxZTIwMTUxNGQ0YWFkMDU0M2JmMDkxNzBkOWYiLCJwIjoiaiJ9
New tests have been added to validate the various cause cases.

feat: Add error cause detection

---

src/features/session_replay/aggregate/index.js
tests/components/session_replay/aggregate.test.js

Ensure the agent manually calculates the first and last timestamps of a SessionReplay payload before harvesting to help improve consistency on the UI replayer.
---
https://new-relic.atlassian.net/browse/NR-428135?atlOrigin=eyJpIjoiNWZiYmZjM2UxMDJkNDQyMzg3ZDVkOGMxOWFmZDkwYzEiLCJwIjoiaiJ9
new unit test has been added to validate the new method.

fix: Calculate first and last timestamps from raw data

---

src/features/utils/event-store-manager.js
tests/assets/inspection-events.html
tests/specs/inspection-events.e2e.js

Removes the event buffer inspection event to avoid a memory leak on using console.log with the `newrelic` window event listener.
---
Inspection events can cause an endless loop if a console log is detected and reported in the callback, causing a memory leak. To remedy this, we remove the buffer event as it is not worth the risk to customer applications.
JIRA: https://new-relic.atlassian.net/browse/NR-444882
Make sure tests pass, especially inspection events tests.

fix: Remove event buffer inspection event

---

src/features/session_replay/aggregate/index.js
src/features/session_replay/instrument/index.js
src/features/session_replay/shared/recorder-events.js
src/features/session_replay/shared/recorder.js
src/features/session_replay/shared/utils.js
src/features/utils/event-buffer.js
tests/components/session_replay/aggregate.test.js
tests/components/session_replay/instrument.test.js
tests/components/setup-agent.js
tests/specs/nr-server-time.e2e.js
tests/specs/session-replay/sr-api.e2e.js
tests/unit/features/session_replay/shared/recorder.test.js
tests/unit/features/session_replay/shared/utils.test.js

Remove the reporting of the __newrelic meta attribute from outgoing replay payloads.  This is being conducted as a measure to help save billable bytes for customers and reduce cost of use for Session Replay functionalities.
---
This PR removes the __newrelic attribute from outgoing payloads, but as a byproduct of that, a number of internal mechanisms were able to be changed, simplified, or removed in a sort of "domino effect" to reduce build burden and performance impacts on enduser machines:
1. The agent now uses the contextual ee to buffer preloaded recording data.
2. Because the agent can buffer the data until the features are fully initialized (by way of the ee), it can now: 
- assume that the timekeeper should always exist when processing rrweb data.
- get rid of the need for …

feat: remove newrelic meta attribute

---

tests/components/generic_events/aggregate/index.test.js

---
Discovered while investigating a Jest test [failure](https://github.com/newrelic/newrelic-browser-agent/actions/runs/17276249751) in another PR.
- Switched to spies to allow `triggerHarvestFor` to run for other tests
- Restored PO to not trigger extra BrowserPerformance entries in later tests
**Issue 1**
`should record marks when enabled` + `should record measures when enabled` tests would fail when run as standalone tests but pass if run as part of the component test
The mock restore wasn't taking effect in the `'should harvest early if will exceed 1mb'` and `'should not harvest if single event will exceed 1mb'` tests.
(in this screenshot, the `'should harvest early …

chore: Fix hidden deps between component tests

---

src/features/jserrors/aggregate/index.js
src/features/soft_navigations/aggregate/index.js
src/features/soft_navigations/aggregate/interaction.js
tests/components/ajax/with-softnav.test.js
tests/components/jserrors/with-softnav.test.js
tests/components/soft_navigations/aggregate.test.js

`JavascriptError` and `AjaxRequest` events will be correctly tied to `BrowserInteraction` when long tasks do/does not happen and extend the interaction. Ultimately, events that start before the final end time of an interaction will be associated to it, inclusive of long tasks.
---
(3 of 3 modifying soft navigation heuristic.) During the waiting window of an interaction monitoring for long tasks, JS errors and network requests still occur, and will initially be associated with the interaction that's "pending finish". In the event that there's ultimately no long task, those jse & ajax falling within this window are freed from ixn association and returned to their standalone features. On contrary, if a long task does occur which extends the interaction, they too will become part of the …

feat: Associate JSErrors and AjaxRequest to extended soft nav interactions

---

src/features/session_replay/aggregate/index.js
src/features/session_replay/shared/recorder.js
tests/assets/rrweb-api-record-no-call.html
tests/specs/session-replay/sr-api.e2e.js

Fixes an issue where a late-called recordReplay API call would not successfully harvest data.
---
This was discovered after testing various cases in a smoke test for UI changes.
Tests have been improved to catch harvest data.

fix: Fix recordReplay API inconsistencies
